/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class AlertInfo;

__attribute__((visibility("hidden")))
@interface ActionManager : NSObject {
@private
	AlertInfo *mAlertInfo;	// 4 = 0x4
}
+ (void)cleanup;	// 0x33931750
+ (id)instance;	// 0x33931784
- (id)init;	// 0x33930868
- (id)alertMessage;	// 0x33930ac8
- (id)alertType;	// 0x33930b40
- (id)alertUrlString;	// 0x33930a68
- (void)dealloc;	// 0x339317d8
- (id)getAlert;	// 0x33930afc
- (id)getDictionary;	// 0x3393098c
- (BOOL)haveAlert;	// 0x3393084c
- (void)registerAlert:(id)alert error:(unsigned)error priority:(unsigned)priority;	// 0x33930f0c
- (void)registerAlert:(id)alert error:(unsigned)error status:(unsigned)status priority:(unsigned)priority;	// 0x33930e18
- (void)registerAlertByPriority:(id)priority;	// 0x33931930
- (void)registerBadCredentialsErrorAlert:(id)alert error:(unsigned)error priority:(unsigned)priority;	// 0x339312bc
- (void)registerBadCredentialsErrorAlert:(id)alert error:(unsigned)error status:(unsigned)status priority:(unsigned)priority;	// 0x339311c8
- (void)registerErrorAlert:(id)alert error:(unsigned)error priority:(unsigned)priority;	// 0x339310e4
- (void)registerErrorAlert:(id)alert error:(unsigned)error status:(unsigned)status priority:(unsigned)priority;	// 0x33930ff0
- (void)registerFatalErrorAlert:(id)alert error:(unsigned)error priority:(unsigned)priority;	// 0x3393166c
- (void)registerFatalErrorAlert:(id)alert error:(unsigned)error status:(unsigned)status priority:(unsigned)priority;	// 0x33931578
- (void)registerNoNetworkErrorAlert:(id)alert error:(unsigned)error priority:(unsigned)priority;	// 0x33931494
- (void)registerNoNetworkErrorAlert:(id)alert error:(unsigned)error status:(unsigned)status priority:(unsigned)priority;	// 0x339313a0
- (void)registerUrlAlert:(id)alert urlStr:(id)str error:(unsigned)error priority:(unsigned)priority;	// 0x33930d1c
- (void)registerUrlAlert:(id)alert urlStr:(id)str error:(unsigned)error status:(unsigned)status priority:(unsigned)priority;	// 0x33930c10
- (void)removeAlert;	// 0x33931838
- (id)stringActioninJson;	// 0x339308fc
@end

