/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "NccpHandlerDelegate.h"
#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface AppNccpHandlerDelegate : NSObject <NccpHandlerDelegate> {
}
- (id)init;	// 0x339303f8
- (void)dealloc;	// 0x339303bc
- (void)reportErrorMessage:(id)message;	// 0x339305e0
- (void)reportInvalidCredentials;	// 0x33930510
- (void)reportNetworkingError;	// 0x33930434
- (void)reportUnrecoverableError;	// 0x339303b8
- (void)reportUnsupportedSoftwareVersion:(id)version;	// 0x339304bc
- (BOOL)startTransaction;	// 0x339303ac
- (void)stopTransaction;	// 0x339303b4
@end

