/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library
#import "AppleTV-Structs.h"

@class BRHeaderControl, BRAirportNetwork, BRWaitSpinnerControl, BRTextControl;
@protocol ATVAPTestResultDelegate;

@interface ATVAPTestController : BRController {
@private
	BRWaitSpinnerControl *_spinner;	// 56 = 0x38
	BRAirportNetwork *_network;	// 60 = 0x3c
	BOOL _testFailed;	// 64 = 0x40
	id<ATVAPTestResultDelegate> _delegate;	// 68 = 0x44
	BRHeaderControl *_header;	// 72 = 0x48
	BRTextControl *_prompt;	// 76 = 0x4c
}
- (id)initForNetwork:(id)network notifying:(id)notifying;	// 0x338ea0c5
- (void)_testFinished:(id)finished;	// 0x338ea4e9
- (void)_testInternetConnection;	// 0x338ea4b9
- (void)dealloc;	// 0x338ea00d
- (void)setFrame:(CGRect)frame;	// 0x338ea2d1
- (void)wasExhumed;	// 0x338e9f95
- (void)wasPushed;	// 0x338e9fd1
@end

