/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRMenuController.h> // Unknown library
#import "ATVAPTestResultDelegate.h"
#import "ATVAPPasswordEntryDelegate.h"
#import "BRMenuListItemProvider.h"
#import "BRTextFieldDelegate.h"

@class BRAirportNetwork, BRAirportNetworksProvider, NSArray, NSString;
@protocol ATVAPNetworkSelectionDelegate;

@interface ATVAPNetworkMenuController : BRMenuController <ATVAPTestResultDelegate, ATVAPPasswordEntryDelegate, BRTextFieldDelegate, BRMenuListItemProvider> {
@private
	id<ATVAPNetworkSelectionDelegate> _delegate;	// 100 = 0x64
	NSArray *_networks;	// 104 = 0x68
	BRAirportNetwork *_selectedNetwork;	// 108 = 0x6c
	NSString *_otherNetworkName;	// 112 = 0x70
	NSString *_attemptedPassword;	// 116 = 0x74
	BOOL _isCollectingNetworks;	// 120 = 0x78
	BRAirportNetworksProvider *_networksProvider;	// 124 = 0x7c
}
- (id)initWithNotifying:(id)notifying;	// 0x338e96dd
- (void)_associateWithNetworkCompleted:(id)networkCompleted;	// 0x338e9b75
- (void)_collectPasswordForNetwork:(id)network;	// 0x338e9061
- (void)_collectWirelessNetworks;	// 0x338e91cd
- (void)_networkHasBeenCollected:(id)collected;	// 0x338e8cad
- (void)_networkStateChanged:(id)changed;	// 0x338e89f1
- (void)_networksHaveBeenCollected:(id)collected;	// 0x338e8dc1
- (void)_selectNetwork:(id)network usingPassword:(id)password;	// 0x338e8f61
- (void)_showFailedNetworkConnection:(id)connection error:(id)error;	// 0x338e9469
- (void)_updateMenuWidth;	// 0x338e999d
- (void)dealloc;	// 0x338e9305
- (float)heightForRow:(long)row;	// 0x338e89e9
- (long)itemCount;	// 0x338e8a6d
- (id)itemForRow:(long)row;	// 0x338e8a91
- (void)itemSelected:(long)selected;	// 0x338e9245
- (id)otherNetworkListItem;	// 0x338e9629
- (void)passwordEntered:(id)entered forNetwork:(id)network;	// 0x338e8c19
- (BOOL)rowSelectable:(long)selectable;	// 0x338e89ed
- (void)testCompleted:(BOOL)completed;	// 0x338e8c71
- (void)textDidChange:(id)text;	// 0x338e89e5
- (void)textDidEndEditing:(id)text;	// 0x338e8b49
- (id)titleForRow:(long)row;	// 0x338e93d1
@end

