/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVAsyncNetworkTest : NSObject {
}
+ (void)performAsyncTest;	// 0x338eaa25
- (id)_performTest;	// 0x338eab39
- (void)_testCompleted:(id)completed;	// 0x338ea945
- (void)dealloc;	// 0x338eaae5
@end

