/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library

@class NSMutableArray;
@protocol ATVAirTunesManagerDelegate;

@interface ATVAirTunesManager : BRSingleton {
@private
	id<ATVAirTunesManagerDelegate> _delegate;	// 4 = 0x4
	NSMutableArray *_speakersPendingConnection;	// 8 = 0x8
	NSMutableArray *_speakersPendingDisconnection;	// 12 = 0xc
}
+ (void)setSingleton:(id)singleton;	// 0x3389d891
+ (id)singleton;	// 0x3389d885
- (id)init;	// 0x3389e1b1
- (void)_connectionFailedToAuth:(id)auth;	// 0x3389d8bd
- (void)_connectionFinished:(id)finished;	// 0x3389d985
- (void)_connectionStarted:(id)started;	// 0x3389d9bd
- (id)_connectionStatus;	// 0x3389e2d1
- (void)_retryConnection:(id)connection;	// 0x3389e365
- (id)_supportedMediaTypes;	// 0x3389dad5
- (BOOL)airTunesAvailableForAsset:(id)asset;	// 0x3389e081
- (id)cachedPasswordForSpeaker:(id)speaker;	// 0x3389dca5
- (void)connectSpeaker:(id)speaker withPassword:(id)password saved:(BOOL)saved andDisconnectOthers:(BOOL)others;	// 0x3389de65
- (void)connectionFinishedForSpeaker:(id)speaker;	// 0x3389dda1
- (void)connectionStartedForSpeaker:(id)speaker;	// 0x3389dde1
- (void)dealloc;	// 0x3389e11d
- (void)disconnectSpeaker:(id)speaker;	// 0x3389de45
- (void)disconnectionFinishedForSpeaker:(id)speaker;	// 0x3389dd21
- (void)disconnectionStartedForSpeaker:(id)speaker;	// 0x3389dd61
- (int)numRemoteSpeakers;	// 0x3389e061
- (id)remoteSpeakerInfoAtIndex:(int)index;	// 0x3389e041
- (id)remoteSpeakerInfoForAllConnectedSpeakers;	// 0x3389debd
- (id)remoteSpeakerInfoForSpeakerID:(id)speakerID;	// 0x3389dfbd
- (void)setAirTunesManagerDelegate:(id)delegate;	// 0x3389e0e5
- (void)setCachedPassword:(id)password forSpeaker:(id)speaker;	// 0x3389dbbd
- (void)setControlEnabledFromRemoteSpeakers:(BOOL)remoteSpeakers;	// 0x3389de21
- (id)speakersWithConnectionsPending;	// 0x3389d89d
- (id)speakersWithDisconnectionsPending;	// 0x3389d8ad
@end

