/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVAPPasswordEntryDelegate.h"
#import "BRMenuListItemProvider.h"
#import <BRMenuController.h> // Unknown library

@class BRAirportNetwork;

__attribute__((visibility("hidden")))
@interface ATVAPWEPPasswordMenuController : BRMenuController <BRMenuListItemProvider, ATVAPPasswordEntryDelegate> {
@private
	BRAirportNetwork *_network;	// 100 = 0x64
	long _passwordType;	// 104 = 0x68
	id<ATVAPPasswordEntryDelegate> _delegate;	// 108 = 0x6c
}
- (id)initForNetwork:(id)network notifying:(id)notifying;	// 0x338ea795
- (void)dealloc;	// 0x338ea6cd
- (float)heightForRow:(long)row;	// 0x338ea5b5
- (long)itemCount;	// 0x338ea5ad
- (id)itemForRow:(long)row;	// 0x338ea715
- (void)itemSelected:(long)selected;	// 0x338ea641
- (void)passwordEntered:(id)entered forNetwork:(id)network;	// 0x338ea5bd
- (BOOL)rowSelectable:(long)selectable;	// 0x338ea5b9
- (id)titleForRow:(long)row;	// 0x338ea5b1
@end

