/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRControl.h> // Unknown library

@class BRWaitSpinnerControl, BRTextControl;

__attribute__((visibility("hidden")))
@interface ATVAirTunesConnectionControl : BRControl {
@private
	BRControl *_background;	// 40 = 0x28
	BRWaitSpinnerControl *_spinner;	// 44 = 0x2c
	BRTextControl *_text;	// 48 = 0x30
}
- (id)init;	// 0x3389d531
- (void)dealloc;	// 0x3389d4c5
- (void)layoutSubcontrols;	// 0x3389d69d
- (void)setStatus:(id)status;	// 0x3389d655
@end

