/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRTextEntryController.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVAPNameEntryController : BRTextEntryController {
}
- (id)init;	// 0x338e8869
@end

