/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRControl.h> // Unknown library

@class BRImageControl, BRTextControl;

__attribute__((visibility("hidden")))
@interface ATVBSRLayer : BRControl {
@private
	BRImageControl *_appleLogo;	// 40 = 0x28
	BRTextControl *_currentResolutionLabel;	// 44 = 0x2c
	BRTextControl *_countDownToNextResolutionLabel;	// 48 = 0x30
	BRTextControl *_canYouSeeTheAppleLogoLabel;	// 52 = 0x34
}
- (id)init;	// 0x338a2989
- (id)_bsrCountDownLabelAttributes;	// 0x338a2e0d
- (id)_centeredTextAttributesForAttributes:(id)attributes;	// 0x338a2731
- (void)dealloc;	// 0x338a2825
- (void)layoutSubcontrols;	// 0x338a2b65
- (void)setCurrentResolutionString:(id)string;	// 0x338a28a5
- (void)setSecondsLeftBeforeNextDisplayModeChangeString:(id)string;	// 0x338a278d
@end

