/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "ATVScreenSaverPluginProtocol.h"

@class BRControl;

__attribute__((visibility("hidden")))
@interface ATVBlackScreenSaver : NSObject <ATVScreenSaverPluginProtocol> {
@private
	BRControl *_blackShroudOfDeath;	// 4 = 0x4
}
- (id)init;	// 0x338f6545
- (void)dealloc;	// 0x338f64fd
- (id)screenSaverControl;	// 0x338f64e9
- (void)setScreenSaverAutoFired:(BOOL)fired;	// 0x338f64f9
@end

