/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library

@class BRPanelControl, NSTimer, BRMerchant, BRControl;

@interface ATVCatalogApplianceController : BRController {
@private
	BRPanelControl *_contentContainer;	// 56 = 0x38
	id _storeObject;	// 60 = 0x3c
	BRControl *_catalogControl;	// 64 = 0x40
	BOOL _controllerToSwapOnActivate;	// 68 = 0x44
	long _state;	// 72 = 0x48
	NSTimer *_timer;	// 76 = 0x4c
	BOOL _isDirty;	// 80 = 0x50
	BOOL _isVolatile;	// 81 = 0x51
	BOOL _autoPlay;	// 82 = 0x52
	BRMerchant *_merchant;	// 84 = 0x54
	Class _catalogAgent;	// 88 = 0x58
}
@property(assign, nonatomic) BOOL autoPlay;	// G=0x3389e661; S=0x3389e671; @synthesize=_autoPlay
@property(readonly, retain) BRControl *catalogControl;	// G=0x3389e691; converted property
@property(readonly, retain) BRPanelControl *contentContainer;	// G=0x3389e681; converted property
@property(retain) id storeObject;	// G=0x3389e609; S=0x3389effd; converted property
+ (id)control;	// 0x3389f305
+ (id)controlWithMerchantLikeControl:(id)merchantLikeControl;	// 0x3389f335
+ (void)initialize;	// 0x3389f381
- (id)init;	// 0x3389f1fd
- (void)_controlCreated:(id)created;	// 0x3389f789
- (void)_enterCompleteState;	// 0x3389e971
- (void)_enterErrorState;	// 0x3389ec45
- (void)_enterWaitingForControlState;	// 0x3389eb75
- (void)_enterWaitingForInitialState;	// 0x3389ecb1
- (void)_handleWaitingForControlAction:(int)controlAction;	// 0x3389e8f5
- (void)_showWaitTimer:(id)timer;	// 0x3389e92d
- (void)_swapInNewController:(id)newController;	// 0x3389e6c1
- (void)_updateStateForAction:(int)action;	// 0x3389e8a1
- (id)accessibilityLabel;	// 0x3389f565
- (void)addControls;	// 0x3389e6ad
// declared property getter: - (BOOL)autoPlay;	// 0x3389e661
// converted property getter: - (id)catalogControl;	// 0x3389e691
// converted property getter: - (id)contentContainer;	// 0x3389e681
- (void)controlWasActivated;	// 0x3389f0b5
- (void)controlWasDeactivated;	// 0x3389f065
- (void)dealloc;	// 0x3389f169
- (void)didEnterErrorState;	// 0x3389e6b5
- (id)errorContent;	// 0x3389f661
- (BOOL)isNetworkDependent;	// 0x3389e605
- (void)layoutSubcontrols;	// 0x3389f4ad
- (void)markAsDirty;	// 0x3389e641
- (BOOL)recreateOnReselect;	// 0x3389e629
- (void)refreshDirtyPage;	// 0x3389ecf5
// declared property setter: - (void)setAutoPlay:(BOOL)play;	// 0x3389e671
- (void)setCatalogAgent:(Class)agent;	// 0x3389e651
- (void)setMerchant:(id)merchant;	// 0x3389f41d
// converted property setter: - (void)setStoreObject:(id)object;	// 0x3389effd
- (void)setStoreObject:(id)object changeState:(BOOL)state;	// 0x3389ef25
- (void)setStoreObject:(id)object fromMerchant:(id)merchant;	// 0x3389f035
- (BOOL)shouldAllowControllerContent;	// 0x3389e6bd
- (BOOL)shouldAllowTransitionOnSwap;	// 0x3389e6b9
- (BOOL)shouldShowWaitContent;	// 0x3389e6a9
- (id)storeMerchant;	// 0x3389e619
// converted property getter: - (id)storeObject;	// 0x3389e609
- (void)updateContent:(id)content;	// 0x3389eda1
- (id)waitContent;	// 0x3389ee41
- (float)waitContentDelay;	// 0x3389e6a1
- (void)willEnterCompleteState;	// 0x3389e6b1
@end

