/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVEvaluation.h"


__attribute__((visibility("hidden")))
@interface ATVClientVersionEvaluation : ATVEvaluation {
}
- (BOOL)_arrayContainsZeroValues:(id)values;	// 0x338e7005
- (id)_versionArrayFromString:(id)string;	// 0x338e7091
- (BOOL)eq:(id)eq;	// 0x338e72e5
- (BOOL)gt:(id)gt;	// 0x338e71a5
- (BOOL)gte:(id)gte;	// 0x338e7105
- (BOOL)lt:(id)lt;	// 0x338e7145
- (BOOL)lte:(id)lte;	// 0x338e70c5
- (BOOL)neq:(id)neq;	// 0x338e7185
@end

