/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPhotoMediaCollection.h> // Unknown library


@interface ATVDefaultPhotos : BRPhotoMediaCollection {
@private
	int _photosType;	// 44 = 0x2c
}
+ (id)appleDefaultPhotos:(int)photos;	// 0x338a20f5
+ (id)appleDefaultPhotosCollection:(int)collection;	// 0x338a2061
- (id)initWithPhotosType:(int)photosType;	// 0x338a1f71
- (id)collectionID;	// 0x338a1f45
- (id)collectionName;	// 0x338a1fd9
- (id)mediaAssets;	// 0x338a1fad
@end

