/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDotMacProvider.h"

@class ATVInternetPhotosAccount, NSSet, NSArray;

__attribute__((visibility("hidden")))
@interface ATVDotMacProviderForAccount : ATVDotMacProvider {
@private
	ATVInternetPhotosAccount *_account;	// 28 = 0x1c
	NSSet *_ignoredMediaCollectionTypes;	// 32 = 0x20
	NSArray *_dataWithTypeDividers;	// 36 = 0x24
	BOOL _disableTypeDividers;	// 40 = 0x28
}
@property(readonly, retain) ATVInternetPhotosAccount *account;	// G=0x338b6311; converted property
@property(retain) NSSet *ignoredMediaCollectionTypes;	// G=0x338b6331; S=0x338b6639; converted property
+ (id)providerForAccount:(id)account;	// 0x338b6b4d
- (id)initWithAccount:(id)account;	// 0x338b87e1
- (id)_data;	// 0x338b67a1
- (id)_dataWithTypeDividers;	// 0x338b680d
- (BOOL)_handlesObject:(id)object;	// 0x338b66a9
- (void)_updateDataCount;	// 0x338b6681
// converted property getter: - (id)account;	// 0x338b6311
- (id)dataAtIndex:(long)index;	// 0x338b69f9
- (long)dataCount;	// 0x338b6a55
- (void)dealloc;	// 0x338b6a79
- (id)hashForDataAtIndex:(long)index;	// 0x338b6961
// converted property getter: - (id)ignoredMediaCollectionTypes;	// 0x338b6331
- (void)setDisableTypeDividers:(BOOL)dividers;	// 0x338b6321
// converted property setter: - (void)setIgnoredMediaCollectionTypes:(id)types;	// 0x338b6639
@end

