/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBaseParserDelegate.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVDotMacRecentAlbumsRSSFeedDelegate : BRBaseParserDelegate {
@private
	NSMutableArray *_recentAlbums;	// 12 = 0xc
	NSMutableDictionary *_currentAlbumInfo;	// 16 = 0x10
}
@property(readonly, retain) NSMutableArray *recentAlbums;	// G=0x339059ed; converted property
+ (id)delegate;	// 0x33905ad1
- (id)init;	// 0x33905a75
- (void)dealloc;	// 0x33905a19
- (void)endItem;	// 0x3390583d
- (void)endLink;	// 0x33905739
- (void)endPubDate;	// 0x33905b11
- (void)endTitle;	// 0x339057ed
// converted property getter: - (id)recentAlbums;	// 0x339059ed
- (void)startEnclosureWithAttributes:(id)attributes;	// 0x33905885
- (void)startItemWithAttributes:(id)attributes;	// 0x339059b1
@end

