/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableData, ATVTCPControlReceiver;

__attribute__((visibility("hidden")))
@interface ATVDirectionalRemoteConnectionHandler : NSObject {
@private
	ATVTCPControlReceiver *_controlReceiver;	// 4 = 0x4
	unsigned _receiverDecryptionKey;	// 8 = 0x8
	NSMutableData *_remainderData;	// 12 = 0xc
	id _delegate;	// 16 = 0x10
}
@property(assign) id delegate;	// G=0x338f0d3d; S=0x338f0d4d; converted property
- (id)init;	// 0x338f0df9
- (id)_checkDataIntegrity:(id)integrity;	// 0x338f110d
- (unsigned long)_decryptReceivedWord:(unsigned long)word;	// 0x338f14ed
- (void)_processTouchCommand:(id)command;	// 0x338f1799
- (void)_promptReceived:(id)received;	// 0x338f0e6d
- (void)_setupControlReceiver:(id)receiver encryptionKey:(unsigned long)key;	// 0x338f130d
- (void)allConnectionsClosed:(id)closed;	// 0x338f12dd
- (void)dealloc;	// 0x338f0d5d
// converted property getter: - (id)delegate;	// 0x338f0d3d
- (void)newBytesReceived:(id)received data:(id)data;	// 0x338f1501
// converted property setter: - (void)setDelegate:(id)delegate;	// 0x338f0d4d
@end

