/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library


@interface ATVDiskSpaceManager : BRSingleton {
}
+ (void)setSingleton:(id)singleton;	// 0x338a2275
+ (id)singleton;	// 0x338a2269
- (id)init;	// 0x338a22b5
- (id)_volumeSizeStringForSize:(unsigned long long)size;	// 0x338a22e1
- (void)dealloc;	// 0x338a2289
- (unsigned long long)mediaCapacity;	// 0x338a26a5
- (id)mediaCapacityString;	// 0x338a254d
- (unsigned long long)mediaFreeSpace;	// 0x338a2619
- (id)mediaFreeSpaceString;	// 0x338a2521
- (unsigned long long)primaryStreamedMediaRepositorySize;	// 0x338a25b5
- (unsigned long long)primaryStreamedMediaRespositoryMaxFileSize;	// 0x338a258d
- (unsigned long long)shortContentStreamedMediaRepositorySize;	// 0x338a2281
- (unsigned long long)shortContentStreamedMediaRespositoryMaxFileSize;	// 0x338a2579
@end

