/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAccount.h> // Unknown library


@interface ATVDotMacManagedAccount : BRAccount {
}
- (void)authenticate;	// 0x338b6375
- (id)type;	// 0x338b63f5
- (void)willBeDeleted;	// 0x338b6379
@end

