/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBackgroundTask.h> // Unknown library

@class BRDownloadManager;

@interface ATVDownloadsPeriodicCheckForPurchasesMonitor : BRBackgroundTask {
@private
	BRDownloadManager *_downloadManager;	// 44 = 0x2c
	BOOL _currentlyPerformingAccountAuthentication;	// 48 = 0x30
	BOOL _currentlyPerformingAutomaticCheckForDownloads;	// 49 = 0x31
	int _failedAuthCount;	// 52 = 0x34
}
+ (BOOL)isCurrentlyAuthenticatingAccount;	// 0x338a46d1
+ (BOOL)isCurrentlyCheckingForDownloads;	// 0x338a46c1
- (id)initWithInterval:(double)interval delay:(double)delay userInfo:(id)info taskType:(int)type;	// 0x338a482d
- (void)_accountAuthenticationDidComplete:(id)_accountAuthentication;	// 0x338a4a6d
- (void)_acquisitionFailure:(id)failure;	// 0x338a4915
- (void)_checkForPurchases;	// 0x338a4c05
- (void)_checkingForPurchasesDidComplete:(id)_checkingForPurchases;	// 0x338a4719
- (void)dealloc;	// 0x338a47bd
- (void)enable;	// 0x338a46e1
- (BOOL)perform:(id)perform;	// 0x338a4c81
@end

