/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSArray, NSMutableArray;
@protocol BRControlFactory;

@interface ATVDotMacRecentAlbumsProvider : NSObject <BRProvider> {
@private
	NSMutableArray *_accountsBeingLoaded;	// 4 = 0x4
	NSArray *_mostRecentAlbums;	// 8 = 0x8
	NSMutableArray *_accountProviders;	// 12 = 0xc
	NSMutableArray *_collectionProviders;	// 16 = 0x10
	NSMutableArray *_collectionsBeingLoaded;	// 20 = 0x14
	id<BRControlFactory> _controlFactory;	// 24 = 0x18
	BOOL _queryInProgress;	// 28 = 0x1c
	double _lastQueryTime;	// 32 = 0x20
}
+ (id)cacheFolderPath;	// 0x33906d09
+ (id)mainMenuProvider;	// 0x33906d4d
+ (id)standardProvider;	// 0x33906d8d
- (id)initForMainMenu:(BOOL)mainMenu;	// 0x33906b1d
- (void)_accountsInserted:(id)inserted;	// 0x339070e5
- (void)_accountsRemoved:(id)removed;	// 0x33906431
- (void)_aggregateRecentAlbums:(id)albums forAccountName:(id)accountName;	// 0x33905f11
- (void)_collectionImageUpdated:(id)updated;	// 0x3390667d
- (void)_collectionProviderUpdated:(id)updated;	// 0x33906809
- (void)_loadAccounts;	// 0x33907169
- (void)_loadCollection:(id)collection;	// 0x33905e89
- (void)_loadRSSFeedWithAccountName:(id)accountName;	// 0x33906129
- (void)_loadRecentAlbumsFromCache;	// 0x33906dcd
- (void)_networkChanged:(id)changed;	// 0x33906389
- (BOOL)_okToFetchNewData;	// 0x3390624d
- (id)_persistentAccountNames;	// 0x33906619
- (void)_removeRecentCachedAlbumsFromAccount:(id)account;	// 0x33907221
- (void)_rssFeedRequestReady:(id)ready;	// 0x339073f5
- (void)_saveRecentAlbumsToCache;	// 0x33905b79
- (void)_sortCollectionsBeingLoaded;	// 0x33905cdd
- (id)controlFactory;	// 0x33905b69
- (id)dataAtIndex:(long)index;	// 0x33906a11
- (long)dataCount;	// 0x33906a31
- (void)dealloc;	// 0x33906a51
- (id)hashForDataAtIndex:(long)index;	// 0x339069e1
- (void)reload;	// 0x339069b5
@end

