/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDotMacParserDelegate.h"

@class NSDictionary, NSDate, NSArray;

__attribute__((visibility("hidden")))
@interface ATVDotMacAccountDelegate : ATVDotMacParserDelegate {
@private
	NSArray *_albumOrder;	// 24 = 0x18
	NSArray *_videoOrder;	// 28 = 0x1c
	NSArray *_slideshowOrder;	// 32 = 0x20
	NSDate *_modDate;	// 36 = 0x24
	NSDictionary *_startSelectors;	// 40 = 0x28
	NSDictionary *_endSelectors;	// 44 = 0x2c
}
@property(readonly, retain) NSDictionary *endSelectors;	// G=0x338abbf5; converted property
@property(readonly, retain) NSDate *modDate;	// G=0x338abc05; converted property
@property(readonly, retain) NSDictionary *startSelectors;	// G=0x338abbe5; converted property
- (id)init;	// 0x338ace85
- (void)__atv_end_dotmac_iMovieUserOrder;	// 0x338acc11
- (void)__atv_end_dotmac_keyImagePath;	// 0x338aca4d
- (void)__atv_end_dotmac_posterPath;	// 0x338ac8fd
- (void)__atv_end_dotmac_redacted;	// 0x338ac9dd
- (void)__atv_end_dotmac_title;	// 0x338acac9
- (void)__atv_end_dotmac_type;	// 0x338acb01
- (void)__atv_end_dotmac_userHidden;	// 0x338ac96d
- (void)__atv_end_dotmac_useritemguid;	// 0x338ac935
- (void)__atv_end_dotmac_userorder;	// 0x338accf9
- (void)__atv_end_dotmac_videoDurationLrg;	// 0x338ac7ad
- (void)__atv_end_dotmac_videoDurationMed;	// 0x338ac81d
- (void)__atv_end_dotmac_videoDurationSmall;	// 0x338ac88d
- (void)__atv_end_dotmac_videoPathLrg;	// 0x338ac7e5
- (void)__atv_end_dotmac_videoPathMed;	// 0x338ac855
- (void)__atv_end_dotmac_videoPathSmall;	// 0x338ac8c5
- (void)__atv_end_dotmac_viewIdentifier;	// 0x338acb39
- (void)__atv_end_dotmac_webImagePath;	// 0x338aca15
- (void)__atv_end_iphoto_userHidden;	// 0x338ac9a5
- (void)__atv_end_slideshowUserOrder;	// 0x338acba9
- (void)__atv_end_title;	// 0x338acb71
- (void)__atv_end_updated;	// 0x338ad341
- (void)__atv_start_link:(id)link;	// 0x338aca85
- (id)_publicMedia;	// 0x338abc15
- (void)_updateEntriesWithDateTaken:(id)dateTaken withType:(id)type;	// 0x338ad545
- (void)dealloc;	// 0x338acde1
- (id)displayName;	// 0x338abd61
// converted property getter: - (id)endSelectors;	// 0x338abbf5
- (id)listOfAlbumInfos;	// 0x338ac5c5
- (id)listOfAlbumInfosAlphabetically;	// 0x338ac509
- (id)listOfAlbumInfosUserSort;	// 0x338ad4bd
- (id)listOfVideoInfos;	// 0x338ac30d
- (id)listOfVideoInfosAlphabetically;	// 0x338ac251
- (id)listOfVideoInfosUserSort;	// 0x338ad435
- (id)mediaUserSort;	// 0x338ac731
// converted property getter: - (id)modDate;	// 0x338abc05
- (id)mostRecentAlbumInfo;	// 0x338abe01
- (id)slideshowInfos;	// 0x338ac085
- (id)slideshowInfosAlphabetically;	// 0x338abfc9
- (id)slideshowInfosUserSort;	// 0x338ad3ad
// converted property getter: - (id)startSelectors;	// 0x338abbe5
@end

