/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVInternetPhotosCollection.h"
#import "ATVDotMacAuthentication.h"

@class ATVDotMacSecondaryAccount, NSString;

@interface ATVDotMacCollection : ATVInternetPhotosCollection <ATVDotMacAuthentication> {
@private
	ATVDotMacSecondaryAccount *_secondaryAccount;	// 64 = 0x40
	BOOL _requiresAuthentication;	// 68 = 0x44
	NSString *_keyImageDotMacIdentifier;	// 72 = 0x48
	BOOL _initialAuthCheckComplete;	// 76 = 0x4c
}
@property(assign) BOOL initialAuthCheckComplete;	// G=0x338aea9d; S=0x338aeaad; converted property
@property(retain) NSString *keyImageDotMacIdentifier;	// G=0x338af32d; S=0x338af269; converted property
@property(assign) BOOL requiresAuthentication;	// G=0x338aea7d; S=0x338aea8d; converted property
@property(retain) ATVDotMacSecondaryAccount *secondaryAccount;	// G=0x338af1b5; S=0x338af085; converted property
- (id)initWithCollectionInfo:(id)collectionInfo;	// 0x338aee6d
- (id)archivableCollectionInfo;	// 0x338aebd9
- (void)dealloc;	// 0x338aee11
- (id)imageProxy;	// 0x338aeabd
// converted property getter: - (BOOL)initialAuthCheckComplete;	// 0x338aea9d
- (BOOL)isAuthenticated;	// 0x338aea69
- (id)keyAsset;	// 0x338af3e1
// converted property getter: - (id)keyImageDotMacIdentifier;	// 0x338af32d
- (id)mediaTypes;	// 0x338aeb5d
- (id)photoAssets;	// 0x338aed9d
// converted property getter: - (BOOL)requiresAuthentication;	// 0x338aea7d
// converted property getter: - (id)secondaryAccount;	// 0x338af1b5
// converted property setter: - (void)setInitialAuthCheckComplete:(BOOL)complete;	// 0x338aeaad
// converted property setter: - (void)setKeyImageDotMacIdentifier:(id)identifier;	// 0x338af269
// converted property setter: - (void)setRequiresAuthentication:(BOOL)authentication;	// 0x338aea8d
// converted property setter: - (void)setSecondaryAccount:(id)account;	// 0x338af085
@end

