/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRPhotoProviderForCollection.h"
#import "ATVDotMacProvider.h"

@class ATVDotMacCollection;

@interface ATVDotMacProviderForCollection : ATVDotMacProvider <BRPhotoProviderForCollection> {
@private
	ATVDotMacCollection *_collection;	// 28 = 0x1c
	BOOL _vendPhotoDataOnly;	// 32 = 0x20
}
@property(readonly, retain) ATVDotMacCollection *collection;	// G=0x338b6341; converted property
@property(assign) BOOL vendPhotoDataOnly;	// G=0x338b6365; S=0x338b6355; converted property
+ (id)providerForCollection:(id)collection;	// 0x338b65f9
+ (id)temporaryProviderForCollection:(id)collection;	// 0x338b65b9
- (id)initWithCollection:(id)collection;	// 0x338b65a1
- (id)initWithCollection:(id)collection isTemporaryProvider:(BOOL)provider;	// 0x338b86d1
- (id)_data;	// 0x338b645d
- (BOOL)_handlesObject:(id)object;	// 0x338b6415
- (BOOL)canHaveZeroData;	// 0x338b6351
// converted property getter: - (id)collection;	// 0x338b6341
- (void)dealloc;	// 0x338b64d9
- (id)hashForDataAtIndex:(long)index;	// 0x338b64a5
// converted property setter: - (void)setVendPhotoDataOnly:(BOOL)only;	// 0x338b6355
// converted property getter: - (BOOL)vendPhotoDataOnly;	// 0x338b6365
@end

