/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVInternetPhotosMonitor.h"

@class BRBackgroundTask;

@interface ATVDotMacMonitor : ATVInternetPhotosMonitor {
@private
	BRBackgroundTask *_backgroundTask;	// 32 = 0x20
}
@property(readonly, retain) BRBackgroundTask *backgroundTask;	// G=0x338b267d; converted property
+ (void)initialize;	// 0x338b5155
+ (void)setSingleton:(id)singleton;	// 0x338b2665
+ (id)singleton;	// 0x338b2659
- (id)init;	// 0x338b50dd
- (void)_addCollectionForTemporaryDataMonitoring:(id)temporaryDataMonitoring;	// 0x338b26bd
- (id)_authenticationsForAccountWithName:(id)name;	// 0x338b2995
- (void)_collectionLoadFailure:(id)failure newCollectionInfo:(id)info status:(int)status;	// 0x338b2e9d
- (id)_dataForRelativePath:(id)relativePath forAccountWithName:(id)name secondaryAccount:(id)account;	// 0x338b57b1
- (BOOL)_isAccountRegisteredForDataMonitoring:(id)dataMonitoring;	// 0x338b2701
- (void)_performAccountIconImageLoad:(id)load;	// 0x338b2d7d
- (void)_performAccountLoad:(id)load;	// 0x338b4561
- (void)_performAccountMediaLoad:(id)load;	// 0x338b3e39
- (void)_performAssetCoverArtImageLoad:(id)load;	// 0x338b2e5d
- (void)_performAssetFullSizeImageLoad:(id)load;	// 0x338b2e3d
- (void)_performAssetImageLoad:(id)load sizeKey:(id)key;	// 0x338b2a59
- (void)_performAssetThumbnailImageLoad:(id)load;	// 0x338b2e7d
- (void)_performAuthenticateCollection:(id)collection;	// 0x338b46c9
- (void)_performCollectionAssetsLoad:(id)load;	// 0x338b3d9d
- (void)_performCollectionAssetsLoadForPhotoCollection:(id)photoCollection;	// 0x338b3665
- (void)_performCollectionAssetsLoadForVideoCollection:(id)videoCollection;	// 0x338b2f81
- (id)_queryParamsForPath:(id)path;	// 0x338b289d
- (void)_saveAuthenticationForAccountWithName:(id)name secondaryAccount:(id)account;	// 0x338b27bd
- (id)_transactionForAccountWithName:(id)name path:(id)path depth:(int)depth secondaryAccount:(id)account;	// 0x338b5a9d
- (int)_xmlDataForRelativePath:(id)relativePath withDepth:(int)depth forAccountWithName:(id)name withParserDelegate:(id)parserDelegate;	// 0x338b29fd
- (id)_xmlDataForRelativePath:(id)relativePath withDepth:(int)depth forAccountWithName:(id)name withParserDelegate:(id)parserDelegate secondaryAccount:(id)account requiresAuthentication:(BOOL)authentication;	// 0x338b53d1
- (void)authenticateCollection:(id)collection withUserName:(id)userName password:(id)password;	// 0x338b4f29
// converted property getter: - (id)backgroundTask;	// 0x338b267d
- (void)cancelAuthenticateForCollection:(id)collection;	// 0x338b4b59
- (void)cancelLoadAccountIconForAccount:(id)account;	// 0x338b4941
- (void)cancelLoadAccountWithName:(id)name;	// 0x338b4b01
- (void)cancelLoadAssetsForCollection:(id)collection;	// 0x338b51b5
- (void)cancelLoadCoverArtImageForAsset:(id)asset;	// 0x338b4a21
- (void)cancelLoadFullSizeImageForAsset:(id)asset;	// 0x338b49b1
- (void)cancelLoadMediaForAccount:(id)account;	// 0x338b52c5
- (void)cancelLoadThumbnailImageForAsset:(id)asset;	// 0x338b4a91
- (void)dealloc;	// 0x338b505d
- (void)loadAccountIconForAccount:(id)account;	// 0x338b4bc9
- (void)loadAccountWithName:(id)name;	// 0x338b4ec9
- (void)loadAssetsForCollection:(id)collection;	// 0x338b4dc9
- (void)loadCoverArtImageForAsset:(id)asset;	// 0x338b4cc9
- (void)loadFullSizeImageForAsset:(id)asset;	// 0x338b4c49
- (void)loadMediaForAccount:(id)account;	// 0x338b4e49
- (void)loadThumbnailImageForAsset:(id)asset;	// 0x338b4d49
- (void)removeAccountWithName:(id)name;	// 0x338b4ff1
- (id)taskContext;	// 0x338b2671
@end

