/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library
#import "AppleTV-Structs.h"
#import "BRTextFieldDelegate.h"

@class BRHeaderControl, NSString, BRTextControl, ATVIPv4AddressEntryControl;
@protocol ATVDottedQuadEntryDelegate;

@interface ATVDottedQuadEntryController : BRController <BRTextFieldDelegate> {
@private
	id<ATVDottedQuadEntryDelegate> _delegate;	// 56 = 0x38
	ATVIPv4AddressEntryControl *_editor;	// 60 = 0x3c
	BRTextControl *_prompt;	// 64 = 0x40
	BRHeaderControl *_header;	// 68 = 0x44
	NSString *_dottedQuad;	// 72 = 0x48
}
@property(retain) NSString *dottedQuad;	// G=0x338ba015; S=0x338ba025; converted property
- (id)initWithTitle:(id)title prompt:(id)prompt label:(id)label notifying:(id)notifying;	// 0x338ba1d1
- (id)accessibilityLabel;	// 0x338ba599
- (void)dealloc;	// 0x338ba141
// converted property getter: - (id)dottedQuad;	// 0x338ba015
// converted property setter: - (void)setDottedQuad:(id)quad;	// 0x338ba025
- (void)setFrame:(CGRect)frame;	// 0x338ba381
- (void)setIcon:(id)icon horizontalOffset:(float)offset kerningFactor:(float)factor;	// 0x338ba111
- (void)textDidChange:(id)text;	// 0x338ba011
- (void)textDidEndEditing:(id)text;	// 0x338ba079
@end

