/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPhotoMediaAsset.h> // Unknown library

@class ATVDotMacSecondaryAccount, NSString;

__attribute__((visibility("hidden")))
@interface ATVDotMacAsset : BRPhotoMediaAsset {
@private
	NSString *_parentAccountName;	// 36 = 0x24
	NSString *_parentCollectionIdentifier;	// 40 = 0x28
	ATVDotMacSecondaryAccount *_secondaryAccount;	// 44 = 0x2c
	NSString *_dotMacIdentifier;	// 48 = 0x30
	NSString *_dateString;	// 52 = 0x34
}
@property(retain) NSString *dotMacIdentifier;	// G=0x338ae3e9; S=0x338ae325; converted property
@property(retain) NSString *parentAccountName;	// G=0x338ae6d9; S=0x338ae615; converted property
@property(retain) NSString *parentCollectionIdentifier;	// G=0x338ae561; S=0x338ae49d; converted property
@property(retain) ATVDotMacSecondaryAccount *secondaryAccount;	// G=0x338ae851; S=0x338ae78d; converted property
+ (id)assetWithParentAccountName:(id)parentAccountName parentCollectionIdentifier:(id)identifier secondaryAccount:(id)account assetInfo:(id)info;	// 0x338ae1d9
- (id)initWithParentAccountName:(id)parentAccountName parentCollectionIdentifier:(id)identifier secondaryAccount:(id)account assetInfo:(id)info;	// 0x338ae229
- (void)configureWithAssetInfo:(id)assetInfo;	// 0x338adfc1
- (id)dateTaken;	// 0x338ae905
- (void)dealloc;	// 0x338ae149
// converted property getter: - (id)dotMacIdentifier;	// 0x338ae3e9
- (id)imageProxy;	// 0x338ae109
- (BOOL)isLocal;	// 0x338adfbd
- (id)mediaType;	// 0x338ae129
// converted property getter: - (id)parentAccountName;	// 0x338ae6d9
// converted property getter: - (id)parentCollectionIdentifier;	// 0x338ae561
// converted property getter: - (id)secondaryAccount;	// 0x338ae851
// converted property setter: - (void)setDotMacIdentifier:(id)identifier;	// 0x338ae325
// converted property setter: - (void)setParentAccountName:(id)name;	// 0x338ae615
// converted property setter: - (void)setParentCollectionIdentifier:(id)identifier;	// 0x338ae49d
// converted property setter: - (void)setSecondaryAccount:(id)account;	// 0x338ae78d
@end

