/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDotMacAsset.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ATVDotMacVideoAsset : ATVDotMacAsset {
@private
	long _duration;	// 56 = 0x38
	NSString *_title;	// 60 = 0x3c
	NSString *_mediaURL;	// 64 = 0x40
	NSString *_description;	// 68 = 0x44
}
@property(assign) long duration;	// G=0x338b8fb9; S=0x338b8fc9; converted property
@property(retain) NSString *mediaURL;	// G=0x338b948d; S=0x338b93c9; converted property
@property(retain) NSString *title;	// G=0x338b9315; S=0x338b9251; converted property
+ (id)assetWithParentAccountName:(id)parentAccountName parentCollectionIdentifier:(id)identifier secondaryAccount:(id)account assetInfo:(id)info;	// 0x338b901d
- (void)configureWithAssetInfo:(id)assetInfo;	// 0x338b9541
- (void)dealloc;	// 0x338b906d
// converted property getter: - (long)duration;	// 0x338b8fb9
- (BOOL)hasVideoContent;	// 0x338b8fd9
- (id)mediaDescription;	// 0x338b919d
- (id)mediaType;	// 0x338b8ffd
// converted property getter: - (id)mediaURL;	// 0x338b948d
- (void)setDescription:(id)description;	// 0x338b90d9
// converted property setter: - (void)setDuration:(long)duration;	// 0x338b8fc9
// converted property setter: - (void)setMediaURL:(id)url;	// 0x338b93c9
// converted property setter: - (void)setTitle:(id)title;	// 0x338b9251
// converted property getter: - (id)title;	// 0x338b9315
@end

