/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPhotoImageProxy.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVDotMacImageProxy : BRPhotoImageProxy {
}
+ (id)imageProxyForAsset:(id)asset;	// 0x338b1ba9
+ (id)imageProxyForCollection:(id)collection;	// 0x338b1b65
- (void)cancelImageRequestsForImageSizes:(int)imageSizes;	// 0x338b1989
- (id)imageForImageSize:(int)imageSize;	// 0x338b1a2d
- (id)imageIDForImageSize:(int)imageSize;	// 0x338b1b11
@end

