/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDotMacParserDelegate.h"

@class NSDictionary, NSDate;

__attribute__((visibility("hidden")))
@interface ATVDotMacVideoDelegate : ATVDotMacParserDelegate {
@private
	NSDate *_modDate;	// 24 = 0x18
	NSDictionary *_startSelectors;	// 28 = 0x1c
	NSDictionary *_endSelectors;	// 32 = 0x20
}
@property(readonly, retain) NSDictionary *endSelectors;	// G=0x338b99b1; converted property
@property(readonly, retain) NSDate *modDate;	// G=0x338b99c1; converted property
@property(readonly, retain) NSDictionary *startSelectors;	// G=0x338b99a1; converted property
- (id)init;	// 0x338b9ce1
- (void)__atv_end_dotmac_description;	// 0x338b9bcd
- (void)__atv_end_dotmac_posterPath;	// 0x338b9b5d
- (void)__atv_end_dotmac_title;	// 0x338b9c05
- (void)__atv_end_dotmac_videoDurationLrg;	// 0x338b9a0d
- (void)__atv_end_dotmac_videoDurationMed;	// 0x338b9a7d
- (void)__atv_end_dotmac_videoDurationSmall;	// 0x338b9aed
- (void)__atv_end_dotmac_videoPathLrg;	// 0x338b9a45
- (void)__atv_end_dotmac_videoPathMed;	// 0x338b9ab5
- (void)__atv_end_dotmac_videoPathSmall;	// 0x338b9b25
- (void)__atv_end_dotmac_webImagePath;	// 0x338b9b95
- (void)__atv_end_title;	// 0x338b9c3d
- (void)__atv_end_updated;	// 0x338b9fd5
- (void)dealloc;	// 0x338b9c75
// converted property getter: - (id)endSelectors;	// 0x338b99b1
// converted property getter: - (id)modDate;	// 0x338b99c1
// converted property getter: - (id)startSelectors;	// 0x338b99a1
- (id)videoName;	// 0x338b99d1
@end

