/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"


@interface ATVDetailedMetadataControlFactory : NSObject <BRControlFactory> {
}
+ (id)factory;	// 0x338a1739
- (void)_populateActors:(id)actors forControl:(id)control;	// 0x338a1335
- (void)_populateDirectors:(id)directors forControl:(id)control;	// 0x338a12a9
- (void)_populateMovieDetails:(id)details forControl:(id)control isTrailer:(BOOL)trailer;	// 0x338a1769
- (void)_populateProducers:(id)producers forControl:(id)control;	// 0x338a121d
- (id)_setupBaseDetailedMetadataControl:(id)control;	// 0x338a14e9
- (id)_setupMusicDetailedMetadataControl:(id)control;	// 0x338a14ad
- (void)_setupSpecificDetailedMetadataControl:(id)control forControl:(id)control2;	// 0x338a1399
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338a15f1
@end

