/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library

@class BRDownloadManager;
@protocol BRMediaAsset;

@interface ATVDownloadsMonitor : BRSingleton {
@private
	BRDownloadManager *_downloadManager;	// 4 = 0x4
	id<BRMediaAsset> _currentAsset;	// 8 = 0x8
}
+ (void)setSingleton:(id)singleton;	// 0x338a4015
+ (id)singleton;	// 0x338a4009
- (id)init;	// 0x338a40fd
- (void)_backgroundProcessingAllowableStateChanged:(id)changed;	// 0x338a43d9
- (void)_downloadStateChangedObserver:(id)observer;	// 0x338a4021
- (void)_downloadsChangedObserver:(id)observer;	// 0x338a4269
- (void)_pauseAllDownloads;	// 0x338a44dd
- (void)_resumePausedDownloads;	// 0x338a4435
- (void)dealloc;	// 0x338a4079
- (void)setCurrentAsset:(id)asset;	// 0x338a45c5
@end

