/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRDisplayInfoLoader.h"
#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVDotMacDisplayInfoLoader : NSObject <BRDisplayInfoLoader> {
@private
	id _object;	// 4 = 0x4
}
@property(retain) id object;	// G=0x338b15ed; S=0x338b179d; converted property
+ (id)displayInfoLoaderWithForObject:(id)object;	// 0x338b17d5
- (void)cancelLoadDisplayInfo;	// 0x338b15fd
- (void)dealloc;	// 0x338b1825
- (id)defaultImage;	// 0x338b186d
- (void)loadDisplayInfo;	// 0x338b16cd
// converted property getter: - (id)object;	// 0x338b15ed
// converted property setter: - (void)setObject:(id)object;	// 0x338b179d
@end

