/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBaseParserDelegate.h> // Unknown library

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVDotMacParserDelegate : BRBaseParserDelegate {
@private
	NSMutableArray *_entries;	// 12 = 0xc
	BOOL _entryCreated;	// 16 = 0x10
	int _curIndex;	// 20 = 0x14
}
@property(readonly, retain) NSMutableArray *entries;	// G=0x338b5f99; converted property
+ (id)delegate;	// 0x338b60c9
- (id)init;	// 0x338b6059
- (void)__atv_end_entry;	// 0x338b5d51
- (void)__atv_start_entry:(id)entry;	// 0x338b5fc5
- (id)_selectorForElement:(id)element qName:(id)name end:(BOOL)end;	// 0x338b5d79
- (void)dealloc;	// 0x338b6011
- (id)endSelectors;	// 0x338b5d75
// converted property getter: - (id)entries;	// 0x338b5f99
- (id)modDate;	// 0x338b5d4d
- (void)parser:(id)parser didEndElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name;	// 0x338b5dc9
- (void)parser:(id)parser didStartElement:(id)element namespaceURI:(id)uri qualifiedName:(id)name attributes:(id)attributes;	// 0x338b5e79
- (void)setEntryObject:(id)object forKey:(id)key;	// 0x338b5f31
- (id)startSelectors;	// 0x338b5d71
@end

