/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVEvaluation : NSObject {
}
+ (id)evaluationWithName:(id)name;	// 0x338e74d5
+ (void)initialize;	// 0x338e74f5
+ (void)registerEvaluation:(id)evaluation withName:(id)name;	// 0x338e74b5
- (BOOL)evaluateValue:(id)value usingOperator:(id)anOperator;	// 0x338e7549
- (SEL)selectorForOperator:(id)anOperator;	// 0x338e73d9
@end

