/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSDate, NSString;

@interface ATVFavorite : NSObject {
@private
	NSDate *_dateAdded;	// 4 = 0x4
	NSString *_title;	// 8 = 0x8
	NSString *_itemID;	// 12 = 0xc
}
@property(copy) NSDate *dateAdded;	// G=0x33901bad; S=0x33901bf5; @synthesize=_dateAdded
@property(copy) NSString *itemID;	// G=0x33901bdd; S=0x33901c45; @synthesize=_itemID
@property(copy) NSString *title;	// G=0x33901bc5; S=0x33901c1d; @synthesize=_title
+ (id)favoriteFromDictionary:(id)dictionary;	// 0x33901c6d
- (id)initWithDictionary:(id)dictionary;	// 0x33901a4d
- (id)_currentDsid;	// 0x339018d5
- (id)_currentStoreFront;	// 0x339018a9
// declared property getter: - (id)dateAdded;	// 0x33901bad
- (void)dealloc;	// 0x339019e1
- (void)encodeWithDictionary:(id)dictionary;	// 0x33901b15
- (BOOL)isSaved;	// 0x33901999
// declared property getter: - (id)itemID;	// 0x33901bdd
- (void)remove;	// 0x33901939
- (BOOL)removeUponAcquisition;	// 0x339018a5
- (void)save;	// 0x33901969
// declared property setter: - (void)setDateAdded:(id)added;	// 0x33901bf5
// declared property setter: - (void)setItemID:(id)anId;	// 0x33901c45
// declared property setter: - (void)setTitle:(id)title;	// 0x33901c1d
// declared property getter: - (id)title;	// 0x33901bc5
@end

