/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVFlickrProvider.h"

@class NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVFlickrProviderForSavedSearches : ATVFlickrProvider {
@private
	NSMutableArray *_savedSearchCollections;	// 24 = 0x18
}
+ (id)providerOfSavedSearchCollections;	// 0x338c1f25
- (id)init;	// 0x338c1d19
- (id)_data;	// 0x338c1255
- (BOOL)_handlesObject:(id)object;	// 0x338c1b45
- (void)_newSavedSearchToAddCollectionFor:(id)aFor;	// 0x338c1a49
- (void)_savedSearchTermRemoved:(id)removed;	// 0x338c1949
- (void)dealloc;	// 0x338c1c6d
- (id)hashForDataAtIndex:(long)index;	// 0x338c1c1d
@end

