/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBaseParserDelegate.h> // Unknown library

@class NSMutableDictionary, NSMutableArray, NSString;

__attribute__((visibility("hidden")))
@interface ATVFlickrParserDelegate : BRBaseParserDelegate {
@private
	NSMutableDictionary *_errInfo;	// 12 = 0xc
	NSString *_userNSID;	// 16 = 0x10
	NSString *_userRealName;	// 20 = 0x14
	NSString *_userIconServer;	// 24 = 0x18
	NSString *_userIconFarm;	// 28 = 0x1c
	NSMutableArray *_photoInfos;	// 32 = 0x20
	NSMutableArray *_photosetInfos;	// 36 = 0x24
	BOOL _photosetInfoCreated;	// 40 = 0x28
	int _curPhotosetInfoIndex;	// 44 = 0x2c
	NSMutableArray *_contactInfos;	// 48 = 0x30
	NSMutableDictionary *_photoSizeInfo;	// 52 = 0x34
	long _photoCount;	// 56 = 0x38
}
@property(readonly, retain) NSMutableArray *contactInfos;	// G=0x338c0709; converted property
@property(readonly, retain) NSMutableDictionary *errInfo;	// G=0x338c0689; converted property
@property(readonly, assign) long photoCount;	// G=0x338c06d9; converted property
@property(readonly, retain) NSMutableArray *photoInfos;	// G=0x338c06e9; converted property
@property(readonly, retain) NSMutableArray *photosetInfos;	// G=0x338c06f9; converted property
@property(readonly, retain) NSString *userIconFarm;	// G=0x338c06c9; converted property
@property(readonly, retain) NSString *userIconServer;	// G=0x338c06b9; converted property
@property(readonly, retain) NSString *userNSID;	// G=0x338c0699; converted property
@property(readonly, retain) NSString *userRealName;	// G=0x338c06a9; converted property
+ (id)parserDelegate;	// 0x338c108d
- (BOOL)_originalImageSizeExceedsMaxSize;	// 0x338c0719
// converted property getter: - (id)contactInfos;	// 0x338c0709
- (void)dealloc;	// 0x338c10c9
- (void)endCount;	// 0x338c0ead
- (void)endPhotoset;	// 0x338c0669
- (void)endRealname;	// 0x338c0edd
- (void)endTitle;	// 0x338c11a1
// converted property getter: - (id)errInfo;	// 0x338c0689
- (id)largeImagePath;	// 0x338c07a9
// converted property getter: - (long)photoCount;	// 0x338c06d9
// converted property getter: - (id)photoInfos;	// 0x338c06e9
// converted property getter: - (id)photosetInfos;	// 0x338c06f9
- (id)photosetInfosAlphabetically;	// 0x338c0855
- (void)startContactWithAttributes:(id)attributes;	// 0x338c08e5
- (void)startErrWithAttributes:(id)attributes;	// 0x338c0fc9
- (void)startPersonWithAttributes:(id)attributes;	// 0x338c0f11
- (void)startPhotoWithAttributes:(id)attributes;	// 0x338c0ce9
- (void)startPhotosWithAttributes:(id)attributes;	// 0x338c0e71
- (void)startPhotosetWithAttributes:(id)attributes;	// 0x338c09e5
- (void)startSizeWithAttributes:(id)attributes;	// 0x338c0bbd
- (void)startUserWithAttributes:(id)attributes;	// 0x338c0f89
// converted property getter: - (id)userIconFarm;	// 0x338c06c9
// converted property getter: - (id)userIconServer;	// 0x338c06b9
// converted property getter: - (id)userNSID;	// 0x338c0699
// converted property getter: - (id)userRealName;	// 0x338c06a9
@end

