/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVInternetPhotosMonitor.h"

@class BRBackgroundTask;

@interface ATVFlickrMonitor : ATVInternetPhotosMonitor {
@private
	BRBackgroundTask *_backgroundTask;	// 32 = 0x20
}
@property(readonly, retain) BRBackgroundTask *backgroundTask;	// G=0x338be0b5; converted property
+ (void)initialize;	// 0x338bfab9
+ (void)setSingleton:(id)singleton;	// 0x338be0a9
+ (id)singleton;	// 0x338be09d
- (id)init;	// 0x338bf9dd
- (id)_loadFlickrURL:(id)url;	// 0x338c051d
- (void)_performAccountIconImageLoad:(id)load;	// 0x338be359
- (void)_performAccountLoad:(id)load;	// 0x338bec85
- (void)_performAccountMediaLoad:(id)load;	// 0x338bfb19
- (void)_performAccountSubAccountsLoad:(id)load;	// 0x338beb05
- (void)_performAssetCoverArtImageLoad:(id)load;	// 0x338be461
- (void)_performAssetFullSizeImageLoad:(id)load;	// 0x338be441
- (void)_performAssetImageLoad:(id)load sizeKey:(id)key;	// 0x338be159
- (void)_performAssetThumbnailImageLoad:(id)load;	// 0x338be5b1
- (void)_performCollectionAssetsLoad:(id)load;	// 0x338be5d1
- (void)_performSearch:(id)search;	// 0x338be481
- (id)_savedSearchesFilePath;	// 0x338be101
- (void)addAccount:(id)account;	// 0x338bf875
// converted property getter: - (id)backgroundTask;	// 0x338be0b5
- (void)cancelLoadAccountIconForAccount:(id)account;	// 0x338bf041
- (void)cancelLoadAssetsForCollection:(id)collection;	// 0x338bef6d
- (void)cancelLoadCoverArtImageForAsset:(id)asset;	// 0x338bee8d
- (void)cancelLoadFullSizeImageForAsset:(id)asset;	// 0x338bee1d
- (void)cancelLoadMediaForAccount:(id)account;	// 0x338bf121
- (void)cancelLoadSubAccountsForAccount:(id)account;	// 0x338bf0b1
- (void)cancelLoadThumbnailImageForAsset:(id)asset;	// 0x338beefd
- (void)dealloc;	// 0x338bf95d
- (void)loadAccountIconForAccount:(id)account;	// 0x338bf695
- (void)loadAccountWithName:(id)name;	// 0x338bf815
- (void)loadAssetsForCollection:(id)collection;	// 0x338bf5ed
- (void)loadCoverArtImageForAsset:(id)asset;	// 0x338bf4ed
- (void)loadFullSizeImageForAsset:(id)asset;	// 0x338bf46d
- (void)loadMediaForAccount:(id)account;	// 0x338bf795
- (void)loadSubAccountsForAccount:(id)account;	// 0x338bf715
- (void)loadThumbnailImageForAsset:(id)asset;	// 0x338bf56d
- (void)removeAccountWithName:(id)name;	// 0x338bf8f1
- (void)removeSavedSearchTerm:(id)term;	// 0x338bf211
- (void)saveSearchTerm:(id)term;	// 0x338bf34d
- (id)savedSearchTerms;	// 0x338bf1dd
- (void)searchWithSearchTerm:(id)searchTerm;	// 0x338bf445
- (id)taskContext;	// 0x338be0c5
@end

