/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRSelectionHandler.h"
#import <BRSingleton.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVFavoritesSelectionHandler : BRSingleton <BRSelectionHandler> {
}
+ (void)setSingleton:(id)singleton;	// 0x338aad75
+ (id)singleton;	// 0x338aad69
- (BOOL)_handleFavoriteSelection:(id)selection;	// 0x338aad81
- (BOOL)handleSelectionForControl:(id)control;	// 0x338aae05
@end

