/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRMediaMenuController.h> // Unknown library

@class ATVInternetPhotosAccount;

__attribute__((visibility("hidden")))
@interface ATVFlickrCollectionController : BRMediaMenuController {
@private
	ATVInternetPhotosAccount *_account;	// 132 = 0x84
	BOOL _isScreenSaverMenu;	// 136 = 0x88
}
+ (id)menuControllerForAccount:(id)account;	// 0x338bb1a1
+ (id)screenSaverMenuControllerForAccount:(id)account;	// 0x338bb161
- (id)initWithAccount:(id)account;	// 0x338bb149
- (id)initWithAccount:(id)account forScreenSaver:(BOOL)screenSaver;	// 0x338bb305
- (void)_handleAddSelection:(id)selection;	// 0x338bae31
- (void)_handleCollectionSelection:(id)selection;	// 0x338bafad
- (void)_handleContactsSelection:(id)selection;	// 0x338bad5d
- (void)_handleRemoveSelection:(id)selection;	// 0x338bb7f5
- (void)_providerUpdated:(id)updated;	// 0x338bb251
- (void)dealloc;	// 0x338bb1e1
- (long)defaultIndex;	// 0x338bb115
- (BOOL)isNetworkDependent;	// 0x338bad59
@end

