/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library

@class NSTimer, NSMutableArray;

@interface ATVFavoritesManager : BRSingleton {
@private
	NSMutableArray *_favorites;	// 4 = 0x4
	NSTimer *_saveTimer;	// 8 = 0x8
}
@property(readonly, retain) NSMutableArray *favorites;	// G=0x338aa1b5; converted property
+ (void)setSingleton:(id)singleton;	// 0x338a9a69
+ (id)singleton;	// 0x338a9a5d
- (id)init;	// 0x338aa445
- (void)_keyValueStoreAccountDidSignOut:(id)_keyValueStoreAccount;	// 0x338aa685
- (void)_keyValueStoreIsAvailable:(id)available;	// 0x338aa6b5
- (void)_loadFavorites;	// 0x338aa0f1
- (void)_musicStoreItemAcquired:(id)acquired;	// 0x338aaa09
- (unsigned)_nextUserOrderForType:(int)type;	// 0x33902da9
- (id)_orderedFavoritesForType:(int)type orderedBy:(int)by;	// 0x33902049
- (void)_removeFavorites:(id)favorites;	// 0x338a9fd9
- (void)_saveFavorites;	// 0x338a9b85
- (void)_saveTimerFired:(id)fired;	// 0x338aa7f5
- (void)_updateFavoritesFromDictionaryRepresentations:(id)dictionaryRepresentations;	// 0x338a9d89
- (void)_updateFromKeyValueStoreIfAvailable:(id)keyValueStoreIfAvailable;	// 0x338aa799
- (void)_updateFromKeyValueStoreInternal:(id)keyValueStoreInternal;	// 0x338aa6d5
- (void)dealloc;	// 0x338aa3d5
- (BOOL)favoriteExistsForItemID:(id)itemID;	// 0x338aa1e1
- (id)favoriteForItemID:(id)itemID;	// 0x338aa1fd
// converted property getter: - (id)favorites;	// 0x338aa1b5
- (id)favoritesForType:(int)type;	// 0x33902131
- (id)orderedFavoritesForType:(int)type;	// 0x33901efd
- (id)radioFavorites;	// 0x3390487d
- (void)reloadFavorites;	// 0x338a9b71
- (void)removeFavorite:(id)favorite;	// 0x338aa291
- (void)removeFavorites:(id)favorites;	// 0x338aa269
- (void)saveFavorite:(id)favorite;	// 0x338aa2d9
- (void)saveFavorites;	// 0x338aa2c5
- (void)setNeedsSave;	// 0x338aa821
- (void)sortModeChangedFrom:(int)from to:(int)to;	// 0x33901e69
- (void)updateFromKeyValueStore:(id)keyValueStore;	// 0x338aa1a1
@end

