/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAccount.h> // Unknown library


@interface ATVFlickrManagedAccount : BRAccount {
}
- (void)authenticate;	// 0x338c1281
- (id)type;	// 0x338c1285
@end

