/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSArray, ATVFavoritesControlFactory;

__attribute__((visibility("hidden")))
@interface ATVFavoritesProvider : NSObject <BRProvider> {
@private
	NSArray *_favorites;	// 4 = 0x4
	ATVFavoritesControlFactory *_factory;	// 8 = 0x8
}
+ (id)provider;	// 0x338aad09
+ (id)providerWithFavorites:(id)favorites;	// 0x338aac71
+ (id)providerWithItemType:(int)itemType;	// 0x338aaca5
- (id)initWithFavorites:(id)favorites;	// 0x338aaba9
- (void)_favoritesChanged:(id)changed;	// 0x338aaaa9
- (id)controlFactory;	// 0x338aaa95
- (id)dataAtIndex:(long)index;	// 0x338aab05
- (long)dataCount;	// 0x338aaae5
- (void)dealloc;	// 0x338aab25
- (id)hashForDataAtIndex:(long)index;	// 0x338aaaa5
@end

