/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRPhotoProviderForCollection.h"
#import "ATVFlickrProvider.h"

@class ATVFlickrCollection;

@interface ATVFlickrProviderForCollection : ATVFlickrProvider <BRPhotoProviderForCollection> {
@private
	ATVFlickrCollection *_collection;	// 24 = 0x18
}
@property(readonly, retain) ATVFlickrCollection *collection;	// G=0x338c1265; converted property
@property(assign) BOOL vendPhotoDataOnly;	// G=0x338c127d; S=0x338c1279; converted property
+ (id)providerForCollection:(id)collection;	// 0x338c16ad
- (id)initWithCollection:(id)collection;	// 0x338c373d
- (id)_data;	// 0x338c1591
- (BOOL)_handlesObject:(id)object;	// 0x338c1549
- (BOOL)canHaveZeroData;	// 0x338c1275
// converted property getter: - (id)collection;	// 0x338c1265
- (void)dealloc;	// 0x338c15e5
- (id)hashForDataAtIndex:(long)index;	// 0x338c15b1
// converted property setter: - (void)setVendPhotoDataOnly:(BOOL)only;	// 0x338c1279
// converted property getter: - (BOOL)vendPhotoDataOnly;	// 0x338c127d
@end

