/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPhotoMediaAsset.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVFlickrAsset : BRPhotoMediaAsset {
@private
	NSDictionary *_assetInfo;	// 36 = 0x24
}
+ (id)assetWithAssetInfo:(id)assetInfo;	// 0x338ba789
- (id)initWithAssetInfo:(id)assetInfo;	// 0x338ba695
- (id)_imagePathWithSize:(int)size;	// 0x338ba7bd
- (void)dealloc;	// 0x338ba64d
- (id)flickrIdentifier;	// 0x338ba601
- (id)imageProxy;	// 0x338ba5e1
- (BOOL)isLocal;	// 0x338ba5dd
- (id)mediaType;	// 0x338ba62d
@end

