/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRMediaMenuController.h> // Unknown library

@class ATVInternetPhotosAccount;

__attribute__((visibility("hidden")))
@interface ATVFlickrContactsController : BRMediaMenuController {
@private
	ATVInternetPhotosAccount *_account;	// 132 = 0x84
	BOOL _isScreenSaverMenu;	// 136 = 0x88
}
+ (id)menuControllerForAccount:(id)account;	// 0x338bbba1
+ (id)screenSaverMenuControllerForAccount:(id)account;	// 0x338bbb61
- (id)initWithAccount:(id)account;	// 0x338bbb49
- (id)initWithAccount:(id)account forScreenSaver:(BOOL)screenSaver;	// 0x338bbd11
- (void)_handleAccountSelection:(id)selection;	// 0x338bb93d
- (void)_handleReturnToFlickrSelection:(id)flickrSelection;	// 0x338bbac5
- (void)_providerUpdated:(id)updated;	// 0x338bbc51
- (void)dealloc;	// 0x338bbbe1
- (BOOL)isNetworkDependent;	// 0x338bb939
@end

