/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTextFieldDelegate.h"
#import <BRMediaMenuController.h> // Unknown library

@class ATVFlickrSearchAgent, NSString, ATVFlickrProvider;

@interface ATVFlickrMainMenuController : BRMediaMenuController <BRTextFieldDelegate> {
@private
	BOOL _isScreenSaverMenu;	// 132 = 0x84
	ATVFlickrSearchAgent *_searchAgent;	// 136 = 0x88
	BOOL _searching;	// 140 = 0x8c
	NSString *_activeSearchTerm;	// 144 = 0x90
	ATVFlickrProvider *_persistentAccountProvider;	// 148 = 0x94
}
+ (id)menuController;	// 0x338bcf29
+ (id)screenSaverMenuController;	// 0x338bceed
- (id)init;	// 0x338bced5
- (id)initForScreenSaver:(BOOL)screenSaver;	// 0x338bda75
- (void)_accountLoaded:(id)loaded;	// 0x338bd041
- (void)_handleAccountSelection:(id)selection;	// 0x338bcd99
- (void)_handleAddSelection:(id)selection;	// 0x338bd239
- (void)_handleSavedSearchCollectionSelection:(id)selection;	// 0x338bcbb5
- (void)_handleSearchSelection:(id)selection;	// 0x338bd625
- (void)_searchComplete:(id)complete;	// 0x338bd355
- (id)accessibilityLabel;	// 0x338bd341
- (void)dealloc;	// 0x338bcfad
- (long)defaultIndex;	// 0x338bcea1
- (BOOL)isNetworkDependent;	// 0x338bcb55
- (float)listVerticalOffset;	// 0x338bdf15
- (void)textDidChange:(id)text;	// 0x338bcb51
- (void)textDidEndEditing:(id)text;	// 0x338bd72d
@end

