/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRDisplayInfoLoader.h"
#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVFlickrDisplayInfoLoader : NSObject <BRDisplayInfoLoader> {
@private
	id _object;	// 4 = 0x4
}
@property(retain) id object;	// G=0x338bc53d; S=0x338bc6ed; converted property
+ (id)displayInfoLoaderWithForObject:(id)object;	// 0x338bc725
- (void)cancelLoadDisplayInfo;	// 0x338bc54d
- (void)dealloc;	// 0x338bc775
- (id)defaultImage;	// 0x338bc7bd
- (void)loadDisplayInfo;	// 0x338bc61d
// converted property getter: - (id)object;	// 0x338bc53d
// converted property setter: - (void)setObject:(id)object;	// 0x338bc6ed
@end

