/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControlHeightFactory.h"
#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"


__attribute__((visibility("hidden")))
@interface ATVFavoritesControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
}
+ (id)factory;	// 0x338a7445
- (id)_collectionTypeForFavorite:(id)favorite;	// 0x338a707d
- (id)_menuItemForFavoriteItem:(id)favoriteItem currentControl:(id)control requestedBy:(id)by;	// 0x338a7589
- (id)_placeholderImageForFavorite:(id)favorite;	// 0x338a70ad
- (id)_previewForFavoriteItem:(id)favoriteItem currentControl:(id)control requestedBy:(id)by;	// 0x338a7139
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338a7391
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x338a7475
@end

