/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRSingleton.h> // Unknown library

@class NSConditionLock, NSInvocation, NSThread;

@interface ATVHIDThread : BRSingleton {
@private
	NSThread *_hidThread;	// 4 = 0x4
	CFRunLoopRef _runLoop;	// 8 = 0x8
	NSConditionLock *_startLock;	// 12 = 0xc
	CFRunLoopSourceRef _invocationRunLoopSource;	// 16 = 0x10
	NSInvocation *_pendingInvocation;	// 20 = 0x14
	NSConditionLock *_invocationLock;	// 24 = 0x18
}
+ (void)setSingleton:(id)singleton;	// 0x338eb7dd
+ (id)singleton;	// 0x338eb7d1
- (id)init;	// 0x338eb971
- (void)_hidThreadLoop;	// 0x338ebc25
- (void)_invocationHandler;	// 0x338eb7e9
- (void)dealloc;	// 0x338eb915
- (BOOL)invokeOnHIDThread:(id)thread;	// 0x338eba71
@end

