/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library


@interface ATVHomeShareAccountCreationController : BRController {
}
- (id)init;	// 0x33912ec5
- (long)_askToUseiTunesAccountForHomeSharing:(id)homeSharing;	// 0x33912a11
- (void)_setupHomeShareAccount;	// 0x33912b6d
- (void)controlWasActivated;	// 0x33912bb1
@end

