/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreAuthenticationResources.h"


__attribute__((visibility("hidden")))
@interface ATVHomeShareAuthenticationResources : ATVMusicStoreAuthenticationResources {
}
- (id)accountNameFootnote;	// 0x3391c149
- (id)accountNameInstructions;	// 0x3391c171
- (id)accountNameTitle;	// 0x3391c199
- (id)accountPasswordTitle;	// 0x3391c121
- (id)defaultPasswordKey;	// 0x3391c109
- (id)defaultUserName;	// 0x3391c1dd
- (id)defaultUserNameKey;	// 0x3391c115
- (id)titleImage;	// 0x3391c1c1
@end

