/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library

@class NSArray;

@interface ATVHIDSystemClient : NSObject {
@private
	IOHIDEventSystemClientRef _hidSystemClient;	// 4 = 0x4
	IOHIDServiceClientRef _appleTVIRService;	// 8 = 0x8
	NSArray *_remotes;	// 12 = 0xc
}
@property(readonly, retain) NSArray *remotes;	// G=0x3391d581; converted property
+ (id)sharedInstance;	// 0x3391d7a9
- (id)init;	// 0x3391d755
- (long)_init;	// 0x3391d835
- (void)cancelLearning;	// 0x3391d2c1
- (void)commitLearningRemote;	// 0x3391d3e9
- (void)dealloc;	// 0x3391d7e5
- (void)deleteRemote:(id)remote;	// 0x3391d4d5
- (BOOL)isPairedWithAppleRemote;	// 0x3391d6e5
- (id)mcuVersion;	// 0x3391d715
- (void)pairAppleRemote;	// 0x3391d68d
- (void)processHIDEvent:(IOHIDEventRef)event;	// 0x3391d98d
- (id)propertyForKey:(id)key error:(id *)error;	// 0x3391dbed
// converted property getter: - (id)remotes;	// 0x3391d581
- (void)rereadRemotes;	// 0x3391d52d
- (void)resetLearningRemote;	// 0x3391d42d
- (void)saveLearning;	// 0x3391d2f9
- (void)setName:(id)name ofRemote:(id)remote;	// 0x3391d461
- (BOOL)setProperty:(id)property forKey:(id)key error:(id *)error;	// 0x3391dc1d
- (void)setSILState_HardwareProblem;	// 0x3391d235
- (void)setSILState_Off;	// 0x3391d2a5
- (void)setSILState_On;	// 0x3391d289
- (void)setSILState_RejectedCommand;	// 0x3391d251
- (void)setSILState_Starting;	// 0x3391d26d
- (void)setSILToState:(id)state;	// 0x3391dc89
- (void)sleepDisplay;	// 0x3391d601
- (void)startLearningUsagePage:(unsigned)page usageCode:(unsigned)code forRemoteUUID:(id)remoteUUID;	// 0x3391d341
- (void)unpairAppleRemote;	// 0x3391d635
- (void)wakeDisplay;	// 0x3391d5cd
@end

