/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library


@interface ATVHardwareUtility : BRSingleton {
@private
	BOOL _isEmbeddedHardwareDevice;	// 4 = 0x4
}
+ (BOOL)bootedFromRecoveryPartition;	// 0x338ab721
+ (id)configurationInfo;	// 0x338ab91d
+ (BOOL)isEmbeddedHardwareDevice;	// 0x338ab7d1
+ (id)mediaFolderPath;	// 0x338ab78d
+ (BOOL)pushSeedData;	// 0x338ab725
+ (BOOL)pushSeedSyslog;	// 0x338ab729
+ (BOOL)reboot;	// 0x338ab8dd
+ (void)setSILState_HardwareProblem;	// 0x338ab801
+ (void)setSILState_Off;	// 0x338ab8b1
+ (void)setSILState_On;	// 0x338ab885
+ (void)setSILState_RejectedCommand;	// 0x338ab82d
+ (void)setSILState_Starting;	// 0x338ab859
+ (void)setSingleton:(id)singleton;	// 0x338ab715
+ (id)singleton;	// 0x338ab709
- (id)init;	// 0x338ab741
- (BOOL)_determineIfEmbeddedHardwareDevice;	// 0x338ab73d
- (BOOL)_isEmbeddedHardwareDevice;	// 0x338ab72d
@end

