/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSDate, ATVInternetPhotosCollection, NSString, NSArray;

__attribute__((visibility("hidden")))
@interface ATVInternetPhotosAccount : NSObject {
@private
	NSString *_accountName;	// 4 = 0x4
	NSString *_accountID;	// 8 = 0x8
	NSString *_displayName;	// 12 = 0xc
	NSArray *_mediaAssets;	// 16 = 0x10
	NSArray *_subAccounts;	// 20 = 0x14
	NSArray *_mediaCollections;	// 24 = 0x18
	ATVInternetPhotosCollection *_lastModifiedCollection;	// 28 = 0x1c
	NSDate *_modDate;	// 32 = 0x20
	NSDate *_lastCheckedDate;	// 36 = 0x24
	NSString *_accountIconPath;	// 40 = 0x28
}
@property(retain) NSString *accountID;	// G=0x338c4f41; S=0x338c4e7d; converted property
@property(retain) NSString *accountIconPath;	// G=0x338c44c9; S=0x338c4405; converted property
@property(retain) NSString *accountName;	// G=0x338c50b9; S=0x338c4ff5; converted property
@property(retain) NSString *displayName;	// G=0x338c4dc9; S=0x338c4cd5; converted property
@property(retain) NSDate *lastCheckedDate;	// G=0x338c4641; S=0x338c457d; converted property
@property(retain) ATVInternetPhotosCollection *lastModifiedCollection;	// G=0x338c4c21; S=0x338c4b5d; converted property
@property(retain) NSArray *mediaCollections;	// G=0x338c4931; S=0x338c486d; converted property
@property(retain) NSDate *modDate;	// G=0x338c47b9; S=0x338c46f5; converted property
@property(retain) NSArray *subAccounts;	// G=0x338c4aa9; S=0x338c49e5; converted property
+ (id)account;	// 0x338c42dd
// converted property getter: - (id)accountID;	// 0x338c4f41
// converted property getter: - (id)accountIconPath;	// 0x338c44c9
// converted property getter: - (id)accountName;	// 0x338c50b9
- (void)dealloc;	// 0x338c4319
// converted property getter: - (id)displayName;	// 0x338c4dc9
// converted property getter: - (id)lastCheckedDate;	// 0x338c4641
// converted property getter: - (id)lastModifiedCollection;	// 0x338c4c21
// converted property getter: - (id)mediaCollections;	// 0x338c4931
// converted property getter: - (id)modDate;	// 0x338c47b9
// converted property setter: - (void)setAccountID:(id)anId;	// 0x338c4e7d
// converted property setter: - (void)setAccountIconPath:(id)path;	// 0x338c4405
// converted property setter: - (void)setAccountName:(id)name;	// 0x338c4ff5
// converted property setter: - (void)setDisplayName:(id)name;	// 0x338c4cd5
// converted property setter: - (void)setLastCheckedDate:(id)date;	// 0x338c457d
// converted property setter: - (void)setLastModifiedCollection:(id)collection;	// 0x338c4b5d
// converted property setter: - (void)setMediaCollections:(id)collections;	// 0x338c486d
// converted property setter: - (void)setModDate:(id)date;	// 0x338c46f5
// converted property setter: - (void)setSubAccounts:(id)accounts;	// 0x338c49e5
// converted property getter: - (id)subAccounts;	// 0x338c4aa9
@end

