/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPhotoMediaCollection.h> // Unknown library

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface ATVInternetPhotosCollection : BRPhotoMediaCollection {
@private
	NSDate *_modDate;	// 44 = 0x2c
	NSDate *_lastCheckedDate;	// 48 = 0x30
	NSString *_parentAccountName;	// 52 = 0x34
	NSString *_parentAccountID;	// 56 = 0x38
	NSString *_previewURL;	// 60 = 0x3c
}
@property(retain) NSDate *lastCheckedDate;	// G=0x338c5465; S=0x338c53a1; converted property
@property(retain) NSDate *modDate;	// G=0x338c58cd; S=0x338c5809; converted property
@property(retain) NSString *parentAccountID;	// G=0x338c55dd; S=0x338c5519; converted property
@property(retain) NSString *parentAccountName;	// G=0x338c5755; S=0x338c5691; converted property
@property(retain) NSString *previewURL;	// G=0x338c5229; S=0x338c52dd; converted property
- (id)collectionDictionary;	// 0x338c516d
- (void)dealloc;	// 0x338c5199
- (BOOL)isLocal;	// 0x338c5171
// converted property getter: - (id)lastCheckedDate;	// 0x338c5465
// converted property getter: - (id)modDate;	// 0x338c58cd
- (long)numberOfPhotos;	// 0x338c5175
// converted property getter: - (id)parentAccountID;	// 0x338c55dd
// converted property getter: - (id)parentAccountName;	// 0x338c5755
// converted property getter: - (id)previewURL;	// 0x338c5229
// converted property setter: - (void)setLastCheckedDate:(id)date;	// 0x338c53a1
// converted property setter: - (void)setModDate:(id)date;	// 0x338c5809
// converted property setter: - (void)setParentAccountID:(id)anId;	// 0x338c5519
// converted property setter: - (void)setParentAccountName:(id)name;	// 0x338c5691
// converted property setter: - (void)setPreviewURL:(id)url;	// 0x338c52dd
@end

