/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVInternetPhotosMonitor : BRSingleton {
@private
	NSMutableDictionary *_tasks;	// 4 = 0x4
	NSMutableArray *_dataMonitoredObjects;	// 8 = 0x8
	NSMutableArray *_temporaryDataMonitoredObjects;	// 12 = 0xc
	NSMutableArray *_temporaryUpdateDelegateCandidates;	// 16 = 0x10
	id _updateDelegate;	// 20 = 0x14
	NSMutableArray *_accountListeners;	// 24 = 0x18
	NSMutableArray *_collectionListeners;	// 28 = 0x1c
}
@property(readonly, retain) NSMutableArray *dataMonitoredObjects;	// G=0x338c6d11; converted property
- (void)_cancelDataMonitoringForObject:(id)object;	// 0x338c5c85
- (void)_registerObjectForDataMonitoring:(id)dataMonitoring;	// 0x338c5db9
- (void)_taskComplete:(id)complete;	// 0x338c5b79
- (void)addOneTimeDataMonitoredObject:(id)object;	// 0x338c6be5
- (id)backgroundTask;	// 0x338c59c9
- (void)cancelDataMonitoringForAccount:(id)account;	// 0x338c5a85
- (void)cancelDataMonitoringForCollection:(id)collection;	// 0x338c5a5d
- (void)cancelLoadAccountIconForAccount:(id)account;	// 0x338c59b1
- (void)cancelLoadAccountWithName:(id)name;	// 0x338c5989
- (void)cancelLoadAssetsForCollection:(id)collection;	// 0x338c59b5
- (void)cancelLoadCoverArtImageForAsset:(id)asset;	// 0x338c59bd
- (void)cancelLoadFullSizeImageForAsset:(id)asset;	// 0x338c59c1
- (void)cancelLoadMediaForAccount:(id)account;	// 0x338c59a9
- (void)cancelLoadSubAccountsForAccount:(id)account;	// 0x338c59ad
- (void)cancelLoadThumbnailImageForAsset:(id)asset;	// 0x338c59b9
- (void)cancelTaskWithIdentifier:(id)identifier;	// 0x338c5fe5
- (id)currentUpdateDelegate;	// 0x338c5f0d
// converted property getter: - (id)dataMonitoredObjects;	// 0x338c6d11
- (void)dealloc;	// 0x338c5aad
- (void)invokeUpdateDelegateForObject:(id)object updateData:(id)data;	// 0x338c59fd
- (void)loadAccountIconForAccount:(id)account;	// 0x338c5995
- (void)loadAccountWithName:(id)name;	// 0x338c5985
- (void)loadAssetsForCollection:(id)collection;	// 0x338c5999
- (void)loadCoverArtImageForAsset:(id)asset;	// 0x338c59a1
- (void)loadFullSizeImageForAsset:(id)asset;	// 0x338c59a5
- (void)loadMediaForAccount:(id)account;	// 0x338c598d
- (void)loadSubAccountsForAccount:(id)account;	// 0x338c5991
- (void)loadThumbnailImageForAsset:(id)asset;	// 0x338c599d
- (void)notifyAccountListenersOfChangeToObject:(id)object;	// 0x338c6645
- (void)notifyCollectionListenersOfChangeToObject:(id)object;	// 0x338c62a5
- (void)performDataMonitoring;	// 0x338c6dc5
- (void)postUpdateNotification:(id)notification;	// 0x338c59cd
- (void)queueTaskWithIdentifier:(id)identifier selector:(SEL)selector object:(id)object;	// 0x338c60f1
- (void)registerAccountForDataMonitoring:(id)dataMonitoring;	// 0x338c5a99
- (void)registerAccountListenerWithID:(id)anId;	// 0x338c68f9
- (void)registerCollectionForDataMonitoring:(id)dataMonitoring;	// 0x338c5a71
- (void)registerCollectionListenerWithID:(id)anId;	// 0x338c6559
- (void)registerTemporaryUpdateDelegate:(id)delegate;	// 0x338c6aad
- (void)registerUpdateDelegate:(id)delegate;	// 0x338c6bc1
- (void)removeAccountWithName:(id)name;	// 0x338c5981
- (id)taskContext;	// 0x338c59c5
- (void)unregisterAccountListenerWithID:(id)anId;	// 0x338c6815
- (void)unregisterCollectionListenerWithID:(id)anId;	// 0x338c6475
- (void)unregisterTemporaryUpdateDelegate:(id)delegate;	// 0x338c69e5
- (void)unregisterUpdateDelegate:(id)delegate;	// 0x338c6b99
@end

