/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRControl.h> // Unknown library
#import "BRTextField.h"

@class BRTextControl, ATVIPv4AddressSelectionControl;
@protocol BRTextFieldDelegate;

__attribute__((visibility("hidden")))
@interface ATVIPv4AddressEntryControl : BRControl <BRTextField> {
@private
	ATVIPv4AddressSelectionControl *_addressPicker;	// 40 = 0x28
	BRTextControl *_labelLayer;	// 44 = 0x2c
	CGSize _addressPickerSize;	// 48 = 0x30
	float _labelPadding;	// 56 = 0x38
	id<BRTextFieldDelegate> _textFieldDelegate;	// 60 = 0x3c
}
- (id)init;	// 0x3390830d
- (void)_handlePlayPauseButton:(id)button;	// 0x33907ebd
- (void)_layoutUI;	// 0x339085e1
- (id)accessibilityLabel;	// 0x33907e25
- (id)accessibilityTraits;	// 0x33907e45
- (BOOL)brEventAction:(id)action;	// 0x33907f75
- (void)dealloc;	// 0x339082b1
- (BOOL)isAccessibilityElement;	// 0x33907e21
- (CGSize)preferredSizeFromScreenSize:(CGSize)screenSize;	// 0x339083f1
- (void)reset;	// 0x33908251
- (void)setDelegate:(id)delegate;	// 0x33907e11
- (void)setFrame:(CGRect)frame;	// 0x339081f5
- (void)setInitialAddress:(id)address;	// 0x33908291
- (void)setLabel:(id)label;	// 0x339084c5
- (void)setString:(id)string;	// 0x33907f35
- (id)stringValue;	// 0x33907f55
@end

