/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRControl.h> // Unknown library

@class NSArray, BRTextControl, ATVIPv4AddressSelectionWidget, BRImageControl;

__attribute__((visibility("hidden")))
@interface ATVIPv4AddressSelectionControl : BRControl {
@private
	NSArray *_octetBackgroundLayers;	// 40 = 0x28
	NSArray *_digitLayers;	// 44 = 0x2c
	NSArray *_dotLayers;	// 48 = 0x30
	BRImageControl *_arrowsLayer;	// 52 = 0x34
	ATVIPv4AddressSelectionWidget *_selectionWidget;	// 56 = 0x38
	BRTextControl *_doneLayer;	// 60 = 0x3c
	int _selection;	// 64 = 0x40
}
- (id)init;	// 0x33908f85
- (CGRect)_arrowsFrameForSelection:(int)selection;	// 0x3390a675
- (id)_buildArrowsLayer;	// 0x3390a2b9
- (id)_buildDigitLayers;	// 0x33908bc9
- (id)_buildDoneLayer;	// 0x339089ad
- (id)_buildDotLayers;	// 0x33908a81
- (id)_buildOctetBackgroundLayers;	// 0x33908d0d
- (CGRect)_cellFrameForSelection:(int)selection;	// 0x3390a4b9
- (CGRect)_digitFrameForSelection:(int)selection;	// 0x3390a5ad
- (float)_layoutUIWithHeight:(float)height;	// 0x3390939d
- (CGRect)_selectionWidgetFrameForSelection:(int)selection;	// 0x33909311
- (void)_setDigitHighlighted:(BOOL)highlighted atIndex:(int)index;	// 0x339088ed
- (void)_setDigitValue:(int)value atIndex:(int)index;	// 0x339087e5
- (void)_setSelection:(int)selection;	// 0x33909175
- (float)_singleCellWidth;	// 0x339092c5
- (id)_textEntryGlyphAttributes;	// 0x3390a365
- (id)_textEntryGlyphGrayAttributes;	// 0x3390a385
- (id)accessibilityLabel;	// 0x33908765
- (id)accessibilityTraits;	// 0x339086ed
- (void)controlWasActivated;	// 0x33908e8d
- (void)dealloc;	// 0x33908ee1
- (BOOL)decrementSelection;	// 0x33909bf5
- (BOOL)doneButtonSelected;	// 0x33909a35
- (BOOL)incrementSelection;	// 0x33909e99
- (id)ipAddress;	// 0x33909a5d
- (BOOL)moveSelectionLeft;	// 0x3390a141
- (BOOL)moveSelectionRight;	// 0x3390a1fd
- (CGRect)preferredFrameForScreenSize:(CGSize)screenSize;	// 0x3390a3a9
- (void)reset;	// 0x33908e71
- (void)setFrame:(CGRect)frame;	// 0x3390976d
- (void)setIPAddress:(id)address;	// 0x33909861
@end

