/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableSet;

@interface ATVKeyValueStoreUtilities : NSObject {
@private
	NSMutableSet *_keyValueStores;	// 4 = 0x4
}
+ (id)sharedInstance;	// 0x33927195
- (id)init;	// 0x33927009
- (void)_accountAuthenticationSucceeded:(id)succeeded;	// 0x33926d75
- (void)_accountRemovedNotification:(id)notification;	// 0x3392720d
- (void)_startPeriodicCleanupTaskOnKeyValueStore:(id)store;	// 0x33926e89
- (void)dealloc;	// 0x33926f99
- (BOOL)isKeyValueStoreAvailable;	// 0x33926f2d
- (void)startMonitoringStore:(id)store;	// 0x33927085
@end

