/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRViewController.h> // Unknown library

@class NSDictionary, BRSystemLanguages, NSArray;

@interface ATVLanguageChooserController : BRViewController {
@private
	BRSystemLanguages *_systemLanguages;	// 60 = 0x3c
	NSArray *_languageKeys;	// 64 = 0x40
	NSDictionary *_languageKeysAndPrompts;	// 68 = 0x44
	BOOL _canBePopped;	// 72 = 0x48
	BOOL _isOOB;	// 73 = 0x49
	BOOL _useVoiceOverGreeting;	// 74 = 0x4a
	double _lastPlayButtonPress;	// 76 = 0x4c
	int _playButtonPressCount;	// 84 = 0x54
}
@property(assign) BOOL canBePopped;	// G=0x3389f8d9; S=0x3389f8c9; converted property
@property(assign, nonatomic) BOOL useVoiceOverGreeting;	// G=0x3389f8e9; S=0x3389f8f9; @synthesize=_useVoiceOverGreeting
+ (id)controlOOB;	// 0x3389fb59
- (id)init;	// 0x3389fb41
- (id)initWithOOBLayout:(BOOL)ooblayout;	// 0x3389fcfd
- (void)_collectLanguages;	// 0x338a026d
- (long)_defaultIndex;	// 0x3389f909
- (void)_performLanguageChange:(id)change;	// 0x338a0191
- (void)_showProgressForLanguage:(id)language;	// 0x338a0091
- (BOOL)brEventAction:(id)action;	// 0x3389fef5
// converted property getter: - (BOOL)canBePopped;	// 0x3389f8d9
- (void)dealloc;	// 0x3389fc91
- (void)list:(id)list didSelectItemAtIndexPath:(id)indexPath;	// 0x3389f9c1
- (id)list:(id)list menuItemForRowAtIndexPath:(id)indexPath;	// 0x3389fa69
- (long)list:(id)list numberOfRowsInSection:(long)section;	// 0x3389fa49
// converted property setter: - (void)setCanBePopped:(BOOL)popped;	// 0x3389f8c9
// declared property setter: - (void)setUseVoiceOverGreeting:(BOOL)greeting;	// 0x3389f8f9
// declared property getter: - (BOOL)useVoiceOverGreeting;	// 0x3389f8e9
- (void)wasPushed;	// 0x3389fc05
@end

