/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreMusicMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)initialize;	// 0x338ddd2d
- (void)_populateMusicMetadataDetails:(id)details;	// 0x338dd675
- (void)_populateSongDetails:(id)details;	// 0x338dd38d
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338ddc4d
- (void)populateMetadataForControl:(id)control;	// 0x338ddba1
@end

