/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStorePagedViewController.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreDoubleRowPagedViewController : ATVMusicStorePagedViewController {
}
- (long)_itemsPerPage;	// 0x3390da21
- (long)grid:(id)grid indexForItemID:(id)itemID;	// 0x3390da19
- (id)grid:(id)grid itemIDAtIndex:(long)index;	// 0x3390da25
- (long)numberOfColumnsInGrid:(id)grid;	// 0x3390da15
- (id)view;	// 0x3390e589
@end

