/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreTVSeasonMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)initialize;	// 0x338e65ed
- (id)_item;	// 0x338e650d
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338e6599
- (void)populateMetadataForControl:(id)control;	// 0x338e6565
@end

