/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreItemDetailController.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreTVEpisodeItemController : ATVMusicStoreItemDetailController {
}
- (id)initWithItemDictionary:(id)itemDictionary;	// 0x338e5805
- (id)accessibilityScreenContent;	// 0x338e57e1
@end

