/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVURLDocument.h"

@class NSString, NSURL, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStorePresentsDocument : ATVURLDocument {
@private
	long _collectionNumber;	// 56 = 0x38
	NSString *_requestID;	// 60 = 0x3c
	NSURL *_redirectURL;	// 64 = 0x40
	NSDictionary *_catalogCollection;	// 68 = 0x44
}
@property(readonly, retain) NSDictionary *catalogCollection;	// G=0x3390357d; converted property
@property(readonly, retain) NSURL *redirectURL;	// G=0x3390356d; converted property
+ (id)documentWithURLRequest:(id)urlrequest requestID:(id)anId collectionNumber:(long)number;	// 0x3390358d
- (id)initWithURLRequest:(id)urlrequest requestID:(id)anId collectionNumber:(long)number;	// 0x33904165
// converted property getter: - (id)catalogCollection;	// 0x3390357d
- (void)dealloc;	// 0x339040f9
- (void)documentLoaded;	// 0x339046dd
// converted property getter: - (id)redirectURL;	// 0x3390356d
@end

