/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSDictionary;

@interface ATVMusicStoreCatalogItemProviderFactory : NSObject {
@private
	NSDictionary *_catalogItem;	// 4 = 0x4
	NSDictionary *_actionItems;	// 8 = 0x8
	NSDictionary *_dateItems;	// 12 = 0xc
}
@property(readonly, retain) NSDictionary *actionItems;	// G=0x338d34d1; converted property
+ (id)providerFactoryWithCatalogItem:(id)catalogItem;	// 0x338d3609
- (id)initWithCatalogItem:(id)catalogItem;	// 0x338d3569
- (id)_decomposeDateAvailableStoreOffers;	// 0x338d24a9
- (id)_decomposeStoreOffers;	// 0x338d274d
- (id)_initWithCatalogItem:(id)catalogItem;	// 0x338d363d
- (id)_itemDetailWishListProvider;	// 0x338d372d
- (id)_largestSizeInCollection;	// 0x338d239d
- (id)_metadataProviderWithAbbreviatedForm:(BOOL)abbreviatedForm;	// 0x338d3a31
- (id)_storeOfferMetadataProvider;	// 0x338d22ed
- (id)abbreviatedMetadataProvider;	// 0x338d33a1
// converted property getter: - (id)actionItems;	// 0x338d34d1
- (id)actionProviders;	// 0x338d30f5
- (id)copyrightProvider;	// 0x338d2f95
- (id)dateAvailableProvider;	// 0x338d3315
- (void)dealloc;	// 0x338d34fd
- (id)imageProxy;	// 0x338d33d1
- (id)itemDetailMoreInfoProvider;	// 0x338d38d9
- (id)listProviders;	// 0x338d2e25
- (id)metadataProvider;	// 0x338d33b9
- (id)moreInfoProvider;	// 0x338d3375
- (id)previewBrowserProvider;	// 0x338d22e9
- (id)relatedProvider;	// 0x338d2f69
- (id)rentalActionProviders;	// 0x338d3039
- (id)storeOffersProvider;	// 0x338d3345
- (id)storeOffersSansPreviewsProvider;	// 0x338d320d
@end

