/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreMovieMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)initialize;	// 0x338dc549
- (void)_populateActors:(id)actors;	// 0x338dc23d
- (void)_populateAudio:(id)audio;	// 0x338dbfcd
- (void)_populateDirector:(id)director;	// 0x338dc18d
- (void)_populateMetadataDetails:(id)details withStoreOffer:(id)storeOffer;	// 0x338dc2c9
- (void)_populateMovieDetails:(id)details withStoreOffer:(id)storeOffer;	// 0x338dc891
- (void)_populateProducers:(id)producers;	// 0x338dc0dd
- (void)_populateSubtitles:(id)subtitles;	// 0x338dc055
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338dc3c1
- (void)populateMetadataForControl:(id)control;	// 0x338dc349
@end

