/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreMusicVideoMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)_initializeAbbreviatedTransformers;	// 0x338de3f5
+ (void)_initializeDetailedTransformers;	// 0x338de4ad
+ (void)_initializeMappings:(id)mappings;	// 0x338de59d
+ (void)initialize;	// 0x338de8fd
- (void)_populateAbbreviatedMetadata:(id)metadata;	// 0x338de11d
- (void)_populateDetailedMetadata:(id)metadata;	// 0x338de9c1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338de81d
- (void)populateMetadataForControl:(id)control;	// 0x338de745
@end

