/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class BRURLDocumentManager;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreXMLDocumentPreProcessor : NSObject {
@private
	BRURLDocumentManager *_includesManager;	// 4 = 0x4
}
+ (id)processDocument:(id)document;	// 0x338e839d
- (id)_dictionaryFromElement:(id)element;	// 0x338e77f9
- (BOOL)_evaluateConditional:(id)conditional;	// 0x338e81b5
- (BOOL)_evaluateKey:(id)key operator:(id)anOperator value:(id)value;	// 0x338e7775
- (BOOL)_processConditionalGroupDictionary:(id)dictionary;	// 0x338e828d
- (void)_processConditionalGroupElement:(id)element;	// 0x338e79c5
- (void)_processConditionalGroups:(id)groups;	// 0x338e7ab9
- (BOOL)_processConditionalResult:(BOOL)result isAnd:(BOOL)anAnd isOr:(BOOL)anOr isNot:(BOOL)aNot;	// 0x338e7675
- (id)_processDocument:(id)document;	// 0x338e7c79
- (id)_processIncludeDictionary:(id)dictionary representingElement:(id)element;	// 0x338e78c1
- (id)_processIncludeElement:(id)element;	// 0x338e7a8d
- (void)_processIncludeRequests:(id)requests;	// 0x338e7e51
- (void)_processIncludes:(id)includes;	// 0x338e7b09
- (void)_removeElement:(id)element;	// 0x338e7d91
- (void)_replaceElement:(id)element withContainedElementNamed:(id)containedElementNamed;	// 0x338e768d
- (void)_replaceElement:(id)element withElement:(id)element2;	// 0x338e77a9
- (void)dealloc;	// 0x338e7d49
@end

