/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "ATVMusicStoreCatalogItemController.h"

@class BRMediaListControl, NSNumber;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreCatalogCollectionController : ATVMusicStoreCatalogItemController {
@private
	BRMediaListControl *_mediaListControl;	// 64 = 0x40
	ATVMediaQueryRef _rentalQuery;	// 68 = 0x44
	BOOL _rentalQueryComplete;	// 72 = 0x48
	NSNumber *_seasonID;	// 76 = 0x4c
}
- (id)initWithItemDictionary:(id)itemDictionary;	// 0x338d0ca9
- (void)_blueDotInfoChanged;	// 0x338d0b35
- (BOOL)_checkForItemsRented;	// 0x338d124d
- (id)_favorite;	// 0x338d0845
- (void)_favoriteItemsChanged:(id)changed;	// 0x338d0b15
- (void)_getBlueDotCount:(long *)count nonBlueDotCount:(long *)count2 withProvider:(id)provider;	// 0x338d0425
- (void)_getEpisodeForSelectedItem:(id *)selectedItem andProvider:(id *)provider;	// 0x338d04fd
- (void)_highlightFirstNonHeaderRow;	// 0x338d099d
- (BOOL)_highlightItemSelectedByUser;	// 0x338d0ad5
- (void)_markAllAsWatched:(BOOL)watched;	// 0x338d1395
- (void)_markSelectedEpisodeAsWatched:(BOOL)watched;	// 0x338d1789
- (id)_providerForSelectedItem;	// 0x338d04d9
- (void)_pushEpisodeForUserSelectedItem;	// 0x338d0879
- (void)_rentalQueryComplete;	// 0x338d1525
- (id)_userSelectedItemWithListIndex:(long *)listIndex;	// 0x338d05a9
- (id)accessibilityLabel;	// 0x338d0b99
- (id)accessibilitySecondaryLabel;	// 0x338d0b79
- (void)controlWasActivated;	// 0x338d0bb9
- (void)dealloc;	// 0x338d11b1
- (id)episodeForSelectedItem;	// 0x338d0b55
- (void)markAsUnwatched;	// 0x338d03c1
- (void)markAsWatched;	// 0x338d03d9
- (void)markSeasonAsUnwatched;	// 0x338d035d
- (void)markSeasonAsWatched;	// 0x338d0375
- (id)providersForContextMenu;	// 0x338d185d
- (void)relatedContentLoaded:(id)loaded;	// 0x338d0281
- (void)wasExhumed;	// 0x338d0c01
- (void)wasPushed;	// 0x338d0c41
@end

