/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreControlPopulator.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreMoreInfoControlPopulator : ATVMusicStoreControlPopulator {
}
+ (BOOL)canHandleData:(id)data;	// 0x338db6bd
- (id)listRowForData:(id)data;	// 0x338db519
@end

