/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBaseAppliance.h> // Unknown library


@interface ATVMusicStoreBaseAppliance : BRBaseAppliance {
}
- (id)init;	// 0x338c93d1
- (id)_qualifyRemoteCategoryDescription:(id)description;	// 0x338c9105
- (void)_refreshCategories:(id)categories;	// 0x338c9325
- (void)_storeLoadStateChanged:(id)changed;	// 0x338c92ed
- (id)applianceCategoryDescriptions;	// 0x338c96fd
- (void)applianceChanged:(id)changed;	// 0x338c935d
- (id)applianceSpecificControllerForIdentifier:(id)identifier args:(id)args;	// 0x338c9101
- (id)controllerForIdentifier:(id)identifier args:(id)args;	// 0x338c94c9
- (void)dealloc;	// 0x338c937d
- (id)localizedSearchTitle;	// 0x338c96c1
@end

