/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVSearchAgent.h"

@class NSString;

@interface ATVMusicStoreSearchAgent : ATVSearchAgent {
@private
	NSString *_baseURLString;	// 12 = 0xc
}
- (id)initWithBaseURLString:(id)baseURLString;	// 0x338e29c1
- (void)_loadSearchURL:(id)url forSearchTerm:(id)searchTerm;	// 0x338e281d
- (void)_searchComplete:(id)complete forSearchTerm:(id)searchTerm;	// 0x338e2789
- (void)_searchRequestProcessed:(id)processed;	// 0x338e2a11
- (void)dealloc;	// 0x338e2951
- (BOOL)isNetworkDependent;	// 0x338e2785
- (void)search:(id)search ignoringCache:(BOOL)cache;	// 0x338e2bc1
- (BOOL)showRecentSearches;	// 0x338e2781
@end

