/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVMusicStoreControlPopulator : NSObject {
@private
	unsigned _matchOrder;	// 4 = 0x4
}
@property(readonly, assign) unsigned matchOrder;	// G=0x338d45e1; @synthesize=_matchOrder
+ (BOOL)canHandleData:(id)data;	// 0x338d6051
- (id)init;	// 0x338d5fa5
- (float)_shelfBoxTitleHeightForFeatured:(BOOL)featured related:(BOOL)related;	// 0x338d45f1
- (float)_shelfTitleWidthScaleForCollectionType:(id)collectionType featured:(BOOL)featured moreInfoContent:(BOOL)content showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles related:(BOOL)related;	// 0x338d47b9
- (float)_shelfWidthForData:(id)data;	// 0x338d6091
- (id)buttonForData:(id)data;	// 0x338d5941
- (float)buttonHeightForData:(id)data;	// 0x338d4d55
- (id)coverArtURLForData:(id)data thumbnail:(BOOL)thumbnail;	// 0x338d4b9d
- (id)gridForData:(id)data;	// 0x338d554d
- (float)gridHeightForData:(id)data;	// 0x338d45d5
- (id)listForData:(id)data;	// 0x338d6281
- (float)listHeightForData:(id)data;	// 0x338d45d9
- (id)listRowForData:(id)data;	// 0x338d5069
- (float)listRowHeightForData:(id)data;	// 0x338d616d
- (id)mainMenuButtonForData:(id)data;	// 0x338d57d5
// declared property getter: - (unsigned)matchOrder;	// 0x338d45e1
- (id)mediaPreviewControlForData:(id)data;	// 0x338d4e79
- (float)mediaPreviewHeightForData:(id)data;	// 0x338d45dd
- (id)pagedViewForData:(id)data;	// 0x338d4e4d
- (float)pagedViewHeightForData:(id)data;	// 0x338d6435
- (id)placeholderImageForData:(id)data;	// 0x338d4a11
- (id)placeholderImageForMenuItemData:(id)menuItemData;	// 0x338d4865
- (id)placeholderImageForShelfData:(id)shelfData;	// 0x338d48cd
- (id)playButtonEnabledMenuItem;	// 0x338d4619
- (id)shelfForData:(id)data;	// 0x338d6445
- (float)shelfHeightForData:(id)data;	// 0x338d4c79
@end

