/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStorePagedViewController.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreSingleRowPagedViewController : ATVMusicStorePagedViewController {
}
- (long)_itemsPerPage;	// 0x3390da11
- (long)grid:(id)grid indexForItemID:(id)itemID;	// 0x3390da09
- (id)grid:(id)grid itemIDAtIndex:(long)index;	// 0x3390da5d
- (long)numberOfColumnsInGrid:(id)grid;	// 0x3390da05
- (id)view;	// 0x3390e751
@end

