/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMerchant.h"
#import "AppleTV-Structs.h"


__attribute__((visibility("hidden")))
@interface ATVMerchant_ITMS : ATVMerchant {
}
+ (id)allocWithZone:(NSZone *)zone;	// 0x33911ebd
+ (void)initialize;	// 0x33911a09
- (id)description;	// 0x339112ad
- (id)generateRequestForURL:(id)url headers:(id)headers method:(id)method;	// 0x3391188d
@end

