/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRMusicStoreUtility.h> // Unknown library

@class NSString, NSMutableDictionary, NSDictionary;

@interface ATVMusicStoreShowInfo : BRMusicStoreUtility {
@private
	NSString *_key;	// 4 = 0x4
	ATVMediaTypeRef _mediaType;	// 8 = 0x8
	NSString *_itemID;	// 12 = 0xc
	NSMutableDictionary *_episodeData;	// 16 = 0x10
	NSDictionary *_itemDictionary;	// 20 = 0x14
}
@property(assign) long bookmarkTimeInMS;	// G=0x33913f2d; S=0x33913eed; converted property
@property(assign) BOOL hasBeenPlayed;	// G=0x33913e49; S=0x33913e09; converted property
@property(assign) BOOL hasBeenRented;	// G=0x33913dd5; S=0x33913d7d; converted property
@property(assign) BOOL isMarkedAsUnwatched;	// G=0x33913d49; S=0x33913d09; converted property
@property(readonly, retain) NSDictionary *itemDictionary;	// G=0x338a7835; converted property
@property(readonly, retain) NSString *itemID;	// G=0x33913b25; converted property
@property(readonly, assign) ATVMediaTypeRef mediaType;	// G=0x33913b15; converted property
@property(assign) long playCount;	// G=0x33913ebd; S=0x33913e7d; converted property
+ (id)_guidForItemDictionary:(id)itemDictionary;	// 0x33914491
+ (id)_guidForTypeName:(id)typeName episodeID:(id)anId;	// 0x339141c5
+ (id)_lookupShowInfoForTypeName:(id)typeName forEpisodeID:(id)episodeID initIfNotFound:(BOOL)found;	// 0x33914669
+ (void)beginBulkUpdate;	// 0x339148f1
+ (void)commitBulkUpdate:(id)update;	// 0x339147b1
+ (void)fetchBookmarkTimeForAsset:(id)asset completionHandler:(id)handler;	// 0x33914295
+ (void)fetchRemoteShowInfoForIDs:(id)ids ofType:(ATVMediaTypeRef)type handler:(id)handler;	// 0x33914025
+ (void)fetchRemoteShowInfoForIDs:(id)ids ofTypes:(id)types handler:(id)handler;	// 0x339149bd
+ (id)lookupShowInfoForItemDictionary:(id)itemDictionary initIfNotFound:(BOOL)found;	// 0x33914565
+ (id)lookupShowInfoForMediaItem:(ATVMediaItemRef)mediaItem initIfNotFound:(BOOL)found;	// 0x339143e5
- (id)_initWithDictionary:(id)dictionary withKey:(id)key withItemID:(id)itemID withMediaType:(ATVMediaTypeRef)mediaType;	// 0x33914d5d
- (id)_objectForKey:(id)key;	// 0x33913cbd
- (void)_saveToDictionary:(id)dictionary;	// 0x33913ce5
- (void)_setObject:(id)object forKey:(id)key;	// 0x33913be5
// converted property getter: - (long)bookmarkTimeInMS;	// 0x33913f2d
- (void)dealloc;	// 0x33914205
// converted property getter: - (BOOL)hasBeenPlayed;	// 0x33913e49
// converted property getter: - (BOOL)hasBeenRented;	// 0x33913dd5
// converted property getter: - (BOOL)isMarkedAsUnwatched;	// 0x33913d49
// converted property getter: - (id)itemDictionary;	// 0x338a7835
// converted property getter: - (id)itemID;	// 0x33913b25
- (void)markAsUnwatched;	// 0x33913b35
- (void)markAsWatched;	// 0x33913b85
// converted property getter: - (ATVMediaTypeRef)mediaType;	// 0x33913b15
// converted property getter: - (long)playCount;	// 0x33913ebd
// converted property setter: - (void)setBookmarkTimeInMS:(long)ms;	// 0x33913eed
// converted property setter: - (void)setHasBeenPlayed:(BOOL)played;	// 0x33913e09
// converted property setter: - (void)setHasBeenRented:(BOOL)rented;	// 0x33913d7d
// converted property setter: - (void)setIsMarkedAsUnwatched:(BOOL)unwatched;	// 0x33913d09
// converted property setter: - (void)setPlayCount:(long)count;	// 0x33913e7d
@end

