/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStorePodcastMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)initialize;	// 0x338e1aa1
- (void)_populatePodcastMetadataDetails:(id)details;	// 0x338e1655
- (void)_populateShowDetails:(id)details;	// 0x338e1e81
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338e1a1d
- (void)populateMetadataForControl:(id)control;	// 0x338e1971
@end

