/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreMusicAlbumMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)initialize;	// 0x338dd1d1
- (id)_item;	// 0x338dd0a9
- (void)_populateAlbumDetails:(id)details;	// 0x338dcced
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338dd17d
- (void)populateMetadataForControl:(id)control;	// 0x338dd101
@end

