/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRControlHeightFactory.h"
#import <NSObject.h> // Unknown library
#import "BRControlFactory.h"


@interface ATVMusicStoreControlFactory : NSObject <BRControlFactory, BRControlHeightFactory> {
@private
	BOOL _forMainMenu;	// 4 = 0x4
}
+ (void)initialize;	// 0x338d3ea9
+ (id)mainMenuFactory;	// 0x338d42a9
+ (void)registerPopulator:(Class)populator;	// 0x338d4481
+ (id)standardFactory;	// 0x338d4309
- (id)initForMainMenu:(BOOL)mainMenu;	// 0x338d3c1d
- (id)_populatorForData:(id)data;	// 0x338d43a9
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338d3f91
- (float)heightForControlForData:(id)data requestedBy:(id)by;	// 0x338d3c59
@end

