/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVCatalogAgent.h"
#import <NSObject.h> // Unknown library
#import "AppleTV-Structs.h"


@interface ATVMusicStoreCatalogAgent : NSObject <ATVCatalogAgent> {
}
+ (void)_acquisitionFailed:(id)failed;	// 0x338cecb5
+ (void)_acquisitionSucceeded:(id)succeeded;	// 0x338ce505
+ (id)_backgroundGradientImageForItem:(id)item;	// 0x338cac29
+ (id)_backgroundImageForItem:(id)item;	// 0x338cac49
+ (id)_backgroundImageForItem:(id)item imageName:(id)name;	// 0x338caa59
+ (CGSize)_backgroundImageSizeForItem:(id)item inset:(float *)inset;	// 0x338cfd49
+ (void)_catalogControlRequestProcessed:(id)processed;	// 0x338cd73d
+ (id)_catalogPageControlForItem:(id)item;	// 0x338cd501
+ (id)_collectionControlsForPageItem:(id)pageItem requestedBy:(id)by dividerSeparated:(BOOL)separated;	// 0x338cef65
+ (id)_controlForItem:(id)item;	// 0x338caf69
+ (void)_controlForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x338cee99
+ (void)_controlForURL:(id)url identifier:(id)identifier;	// 0x338cb241
+ (id)_firstControlOfType:(Class)type inArray:(id)array;	// 0x338cdf7d
+ (id)_formattedPageContentCountString:(id)string;	// 0x338ce66d
+ (id)_headerControlsForPageItem:(id)pageItem;	// 0x338cf6d9
+ (id)_listPageForItem:(id)item;	// 0x338cae35
+ (id)_mediaTypeForStoreLink:(id)storeLink;	// 0x338cb3ad
+ (id)_mediaTypeForStoreMediaCollectionType:(id)storeMediaCollectionType;	// 0x338cb405
+ (id)_mediaTypeForStoreMediaType:(id)storeMediaType;	// 0x338cb531
+ (id)_moreInfoHeaderControlsForPageItem:(id)pageItem;	// 0x338cf4a9
+ (void)_popToItemController:(id)itemController;	// 0x338cb6a5
+ (id)_roomDescriptionControlsForPageItem:(id)pageItem;	// 0x338cfe71
+ (id)_roomPageContainerForItem:(id)item withScroller:(id)scroller;	// 0x338cf825
+ (id)_roomPageForItem:(id)item;	// 0x338cacf1
+ (id)_scrollerControlsFromHeaderControls:(id)headerControls collectionControls:(id)controls;	// 0x338cac69
+ (id)_setupScroller;	// 0x338cf3b5
+ (id)_supplementPageForItem:(id)item;	// 0x338caee1
+ (id)_tabbedPageForItem:(id)item;	// 0x338ce1b5
+ (void)acquireItem:(id)item;	// 0x338ccf6d
+ (id)allLeafItemsForItem:(id)item;	// 0x338ce025
+ (Class)catalogAgent;	// 0x338cc735
+ (Class)catalogAgentForMerchant:(id)merchant;	// 0x338cd3d1
+ (id)catalogHandler;	// 0x338cd435
+ (void)checkForPurchases;	// 0x338cc6fd
+ (id)controlForItem:(id)item;	// 0x338cc3d1
+ (void)controlForObject:(id)object;	// 0x338cdccd
+ (id)coverArtForItem:(id)item;	// 0x338cb939
+ (id)coverArtURLForItem:(id)item featured:(BOOL)featured thumbnail:(BOOL)thumbnail;	// 0x338cb879
+ (long)downloadItem:(id)item;	// 0x338cdb25
+ (id)episodeArtURLForItem:(id)item;	// 0x338cb829
+ (void)initialize;	// 0x338cd0f9
+ (BOOL)isItemFeatured:(id)featured;	// 0x338cb7bd
+ (BOOL)isItemOrdered:(id)ordered;	// 0x338cb799
+ (BOOL)isTemplateParameterSet:(id)set forItem:(id)item;	// 0x338cb6e9
+ (long)itemIDForItem:(id)item;	// 0x338cbb15
+ (int)itemType:(id)type;	// 0x338cc139
+ (id)mediaAssetForStoreOffer:(id)storeOffer;	// 0x338cbbed
+ (id)mediaTypeForItem:(id)item;	// 0x338cc0ad
+ (void)playStoreItem:(id)item;	// 0x338c9c91
+ (void)registerCatalogAgent:(Class)agent forMerchant:(id)merchant;	// 0x338cd391
+ (void)registerClass:(Class)aClass withTemplateName:(id)templateName;	// 0x338cc605
+ (void)sendPingForItem:(id)item;	// 0x338cc4c9
+ (void)setCatalogAgent:(Class)agent;	// 0x338c9c55
+ (void)setDownloadFunction:(/*function-pointer*/ void *)function;	// 0x338c9c85
+ (void)setPurchaseFunction:(/*function-pointer*/ void *)function;	// 0x338c9c61
+ (void)setRentalFunction:(/*function-pointer*/ void *)function;	// 0x338c9c6d
+ (void)setSubscribeFunction:(/*function-pointer*/ void *)function;	// 0x338c9c79
+ (BOOL)showAllTitles:(id)titles;	// 0x338cb805
+ (BOOL)showTitleAndSubtitle:(id)subtitle;	// 0x338cb7e1
+ (BOOL)storeVersionIsCompatibileForPageDictionary:(id)pageDictionary redirectURL:(id *)url;	// 0x338cc3e5
+ (void)subscribeToItem:(id)item;	// 0x338cdc5d
@end

