/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRButtonControl.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVMoviesPlayActionButtonControl : BRButtonControl {
}
+ (id)playButtonForAsset:(id)asset;	// 0x33905281
+ (id)playButtonForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x3390524d
- (void)_downloadStateChanged:(id)changed;	// 0x33905221
- (void)_updateButtonStateWithAsset:(id)asset;	// 0x3390542d
- (void)dealloc;	// 0x339053d9
@end

