/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library

@class NSTimer, NSDictionary, BRWaitPromptControl, ATVURLDocument;

@interface ATVMusicStoreMoviePreviewController : BRController {
@private
	BRWaitPromptControl *_waitPrompt;	// 56 = 0x38
	NSTimer *_timer;	// 60 = 0x3c
	NSDictionary *_dictionary;	// 64 = 0x40
	ATVURLDocument *_document;	// 68 = 0x44
}
+ (id)previewControllerWithDictionary:(id)dictionary;	// 0x3390ae99
- (id)init;	// 0x3390a825
- (id)initWithStoreDictionary:(id)storeDictionary;	// 0x3390ac05
- (void)_movieDataFetchRequestProcessed:(id)processed;	// 0x3390aedd
- (void)_showPromptTimer:(id)timer;	// 0x3390a8cd
- (BOOL)brEventAction:(id)action;	// 0x3390a829
- (void)controlWasActivated;	// 0x3390a96d
- (void)controlWasDeactivated;	// 0x3390a901
- (void)dealloc;	// 0x3390ab71
@end

