/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSDictionary, NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface ATVMusicStorePagedViewController : NSObject {
@private
	NSDictionary *_storeDict;	// 4 = 0x4
	NSMutableArray *_pages;	// 8 = 0x8
	NSArray *_items;	// 12 = 0xc
}
+ (id)pagedViewControllerForStoreItem:(id)storeItem;	// 0x3390e225
- (id)init;	// 0x3390d9ed
- (id)initWithStoreItem:(id)storeItem;	// 0x3390dfa5
- (long)_itemsPerPage;	// 0x3390da01
- (long)_pageCount;	// 0x3390da95
- (BOOL)datasourceShouldBeRetainedByPagedView:(id)datasource;	// 0x3390d9f5
- (void)dealloc;	// 0x3390df11
- (BOOL)delegateShouldBeRetainedByPagedView:(id)delegate;	// 0x3390d9fd
- (float)grid:(id)grid heightForItemAtIndex:(long)index;	// 0x3390e579
- (id)grid:(id)grid itemAtIndex:(long)index;	// 0x3390dadd
- (long)numberOfItemsInGrid:(id)grid;	// 0x3390ddc5
- (long)pageCountForPagedView:(id)pagedView;	// 0x3390de49
- (void)pagedView:(id)view didSwitchToPageAtIndex:(long)index fromPageAtIndex:(long)index3;	// 0x3390d9f9
- (id)pagedView:(id)view itemForPage:(long)page;	// 0x3390e2f5
- (void)pagedView:(id)view willSwitchToPageAtIndex:(long)index fromPageAtIndex:(long)index3;	// 0x3390e421
- (void)toggleCursorMode:(id)mode;	// 0x3390de5d
- (id)view;	// 0x3390d9f1
@end

