/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRMetadataProvider.h"

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreBaseMetadataProvider : NSObject <BRMetadataProvider> {
@private
	NSDictionary *_catalogItem;	// 4 = 0x4
	BOOL _useAlternateMetadata;	// 8 = 0x8
}
@property(assign) BOOL useAlternateMetadata;	// G=0x338c9ac1; S=0x338c9ad1; converted property
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x338c9c21
- (id)initWithCatalogItem:(id)catalogItem;	// 0x338c9bd1
- (id)controlFactory;	// 0x338c9af9
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338c9ae1
- (id)dataAtIndex:(long)index;	// 0x338c9afd
- (long)dataCount;	// 0x338c9ae5
- (void)dealloc;	// 0x338c9b89
- (id)hashForDataAtIndex:(long)index;	// 0x338c9b11
- (void)populateMetadataForControl:(id)control;	// 0x338c9b0d
// converted property setter: - (void)setUseAlternateMetadata:(BOOL)metadata;	// 0x338c9ad1
// converted property getter: - (BOOL)useAlternateMetadata;	// 0x338c9ac1
@end

