/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import "ATVCatalogApplianceController.h"

@class BRListControl, BRMediaShelfControl, BRControl, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreMoreInfoController : ATVCatalogApplianceController {
@private
	NSDictionary *_catalogItem;	// 92 = 0x5c
	BRListControl *_list;	// 96 = 0x60
	BRControl *_previousPosterControl;	// 100 = 0x64
	BOOL _localListContentSelected;	// 104 = 0x68
	BRMediaShelfControl *_actionShelfControl;	// 108 = 0x6c
	long _lastSelectedIndex;	// 112 = 0x70
}
- (id)initWithCatalogItem:(id)catalogItem;	// 0x338da635
- (id)_coverArtControl;	// 0x338da971
- (void)_focusedActionChanged:(id)changed;	// 0x338d9dbd
- (id)_grid;	// 0x338d9cb1
- (void)_listSelectionChanged:(id)changed;	// 0x338d9e61
- (void)_loadList;	// 0x338da0d5
- (void)_loadMoreInfoItemContentFromURL:(id)url;	// 0x338dafe1
- (void)_loadMoreInfoItemContentFromURLString:(id)urlstring;	// 0x338d9c7d
- (void)_moreInfoItemContentFeedReceived:(id)received;	// 0x338db0fd
- (BOOL)_selectionIsTopmostSelectable;	// 0x338da865
- (id)_summaryControl;	// 0x338d9da5
- (id)_summaryControlForItem:(id)item;	// 0x338dab45
- (id)accessibilityScreenContent;	// 0x338da83d
- (void)addControls;	// 0x338d9bc1
- (BOOL)brEventAction:(id)action;	// 0x338da375
- (void)controlWasActivated;	// 0x338da4f9
- (void)controlWasDeactivated;	// 0x338da469
- (void)dealloc;	// 0x338da5a1
- (id)focusedControlForEvent:(id)event focusPoint:(CGPoint *)point;	// 0x338da699
- (void)layoutSubcontrols;	// 0x338db40d
- (void)refreshDirtyPage;	// 0x338d9b31
- (BOOL)shouldAllowControllerContent;	// 0x338dafd5
- (id)transitionType;	// 0x338d9b21
- (void)updateContent:(id)content;	// 0x338d9b81
- (void)willEnterCompleteState;	// 0x338d9c59
@end

