/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAuthenticationResources.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVMusicStoreAuthenticationResources : BRAuthenticationResources {
}
- (id)accountNameInstructions;	// 0x3390d8c9
- (id)accountNameLabel;	// 0x3390d8a1
- (id)accountNameTitle;	// 0x3390d8f1
- (id)accountPasswordInstructions;	// 0x3390d851
- (id)accountPasswordLabel;	// 0x3390d829
- (id)accountPasswordTitle;	// 0x3390d879
- (id)authenticationFailureInstructions;	// 0x3390d789
- (id)authenticationFailureTitle;	// 0x3390d7b1
- (id)connectionString;	// 0x3390d919
- (id)defaultPasswordKey;	// 0x3390d771
- (id)defaultUserName;	// 0x3390d955
- (id)defaultUserNameKey;	// 0x3390d77d
- (id)rememberPasswordInstructions;	// 0x3390d7d9
- (id)rememberPasswordTitle;	// 0x3390d801
@end

