/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreMoreInfoProvider : NSObject <BRProvider> {
@private
	NSDictionary *_catalogItem;	// 4 = 0x4
	NSMutableArray *_items;	// 8 = 0x8
}
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x338dba95
- (id)initWithCatalogItem:(id)catalogItem;	// 0x338db9b1
- (id)_flattenMoreInfoSection:(id)section;	// 0x338db719
- (void)_loadMoreInfoData;	// 0x338db80d
- (void)_loadMoreInfoFromURL:(id)url;	// 0x338dbac9
- (void)_supplementalResponseReceived:(id)received;	// 0x338dbbf9
- (id)controlFactory;	// 0x338db90d
- (id)dataAtIndex:(long)index;	// 0x338db8cd
- (long)dataCount;	// 0x338db8ed
- (void)dealloc;	// 0x338db92d
- (id)hashForDataAtIndex:(long)index;	// 0x338db715
@end

