/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRControl.h> // Unknown library
#import "AppleTV-Structs.h"

@class BRImageControl, BRTextControl;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreRottenTomatoesRatingControl : BRControl {
@private
	BRImageControl *_freshnessImageControl;	// 40 = 0x28
	BRTextControl *_percentageNumberControl;	// 44 = 0x2c
	BRTextControl *_percentageGlyphControl;	// 48 = 0x30
}
+ (id)ratingControlWithItem:(id)item;	// 0x33912f79
- (id)initWithItem:(id)item;	// 0x33912fbd
- (id)accessibilityLabel;	// 0x33913251
- (void)dealloc;	// 0x33912f0d
- (void)layoutSubcontrols;	// 0x33913335
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x339132d5
@end

