/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSDictionary, NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreItemProvider : NSObject <BRProvider> {
@private
	NSDictionary *_catalogItem;	// 4 = 0x4
	NSMutableArray *_items;	// 8 = 0x8
	BOOL _reverseOrder;	// 12 = 0xc
	BOOL _isAnyItemBlueDotted;	// 13 = 0xd
	NSMutableDictionary *_watchedStatesForItems;	// 16 = 0x10
}
@property(assign, getter=isOrderReversed) BOOL orderReversed;	// G=0x338d8cb5; S=0x338d932d; converted property
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x338d9559
- (id)initWithCatalogItem:(id)catalogItem;	// 0x338d9411
- (id)_augmentCollectionItem:(id)item atIndex:(long)index;	// 0x338d8cfd
- (void)_checkForBlueDottedItems;	// 0x338d9881
- (void)_resetBlueDottedItems;	// 0x338d8cc9
- (id)accessibilityLabel;	// 0x338d8cb1
- (id)controlFactory;	// 0x338d930d
- (id)dataAtIndex:(long)index;	// 0x338d9639
- (long)dataCount;	// 0x338d92ed
- (void)dealloc;	// 0x338d937d
- (id)hashForDataAtIndex:(long)index;	// 0x338d8cc5
// converted property getter: - (BOOL)isOrderReversed;	// 0x338d8cb5
- (void)loadSupplementalItemsFromURL:(id)url;	// 0x338d90e5
- (void)moreItemSelected:(id)selected;	// 0x338d958d
- (void)registerMoreItem;	// 0x338d9211
// converted property setter: - (void)setOrderReversed:(BOOL)reversed;	// 0x338d932d
- (void)supplementalItemsLoaded:(id)loaded;	// 0x338d8ee9
- (void)supplementalItemsReceived:(id)received;	// 0x338d96dd
@end

