/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRControl.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreUserReviewsControl : BRControl {
@private
	NSDictionary *_itemDictionary;	// 40 = 0x28
}
+ (id)userReviewsControlWithDictionary:(id)dictionary;	// 0x3391dd75
- (id)initWithDictionary:(id)dictionary;	// 0x3391dd25
- (CGRect)_addTextControlWithAttributedString:(id)attributedString maxSize:(CGSize)size xOrigin:(float)origin topLine:(float)line;	// 0x3391e865
- (CGRect)_addTextControlWithText:(id)text attributes:(id)attributes maxSize:(CGSize)size origin:(CGPoint)origin;	// 0x3391e001
- (id)_largeImageForRating:(float)rating;	// 0x3391ddc1
- (id)_smallImageForRating:(float)rating;	// 0x3391dee1
- (id)accessibilityLabel;	// 0x3391dda9
- (void)dealloc;	// 0x3391dcdd
- (void)layoutSubcontrols;	// 0x3391e0ed
@end

