/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBaseMediaAsset.h> // Unknown library

@protocol BRMediaAsset;

__attribute__((visibility("hidden")))
@interface ATVMusicCoversMediaAsset : BRBaseMediaAsset {
@private
	id<BRMediaAsset> _asset;	// 8 = 0x8
}
+ (id)assetWrapperWithAsset:(id)asset;	// 0x33907a31
- (id)initWithAsset:(id)asset;	// 0x33907dc1
- (id)assetID;	// 0x33907a11
- (void)dealloc;	// 0x33907d79
- (id)imageProxy;	// 0x339079f1
- (id)mediaType;	// 0x339079d1
@end

