/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRMerchant.h> // Unknown library
#import "AppleTV-Structs.h"


@interface ATVMerchant : BRMerchant {
}
+ (id)allocWithZone:(NSZone *)zone;	// 0x33911c91
- (BOOL)assignToObject:(id)object;	// 0x33911ce1
- (id)localizedStringForKey:(id)key;	// 0x33911e01
@end

