/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTitleProvider.h"
#import <NSObject.h> // Unknown library

@class NSString, NSURL, BRMediaType, NSDictionary, NSMutableArray;

@interface ATVMusicStorePresentsProvider : NSObject <BRTitleProvider> {
@private
	NSString *_requestID;	// 4 = 0x4
	BRMediaType *_mediaType;	// 8 = 0x8
	NSURL *_url;	// 12 = 0xc
	NSURL *_fallbackURL;	// 16 = 0x10
	NSMutableArray *_items;	// 20 = 0x14
	NSDictionary *_catalogCollection;	// 24 = 0x18
	BOOL _storeLoadInProgress;	// 28 = 0x1c
	double _lastStoreLoadTime;	// 32 = 0x20
	BOOL _networkIsOK;	// 40 = 0x28
	BOOL _storeRestricted;	// 41 = 0x29
	NSString *_title;	// 44 = 0x2c
	unsigned _collectionNumber;	// 48 = 0x30
	unsigned _fallbackCollectionNumber;	// 52 = 0x34
	BOOL _usingFallback;	// 56 = 0x38
}
@property(readonly, retain) NSString *title;	// G=0x33903525; converted property
+ (id)_cachedResultsDirectory;	// 0x33903de1
+ (id)_cachedResultsPathForRequestID:(id)requestID;	// 0x33903d65
+ (id)providerWithMediaType:(id)mediaType forID:(id)anId;	// 0x339040c1
- (id)_cachedResultModDate;	// 0x33903781
- (void)_clearStoreData;	// 0x33903c89
- (id)_initWithMediaType:(id)mediaType forID:(id)anId;	// 0x33904529
- (void)_loadCachedEntry;	// 0x339039b9
- (void)_loadStoreDataFromURL:(id)url;	// 0x339043b1
- (void)_networkChanged:(id)changed;	// 0x33903691
- (BOOL)_okToFetchNewData;	// 0x33903545
- (void)_parentalControlAccessChanged:(id)changed;	// 0x339035d9
- (void)_parseCatalogCollection:(id)collection;	// 0x339037dd
- (void)_resetStoreData;	// 0x339039d9
- (void)_setTitle:(id)title;	// 0x33903e25
- (void)_supplementalResponseReceived:(id)received;	// 0x3390428d
- (id)controlFactory;	// 0x33904059
- (id)dataAtIndex:(long)index;	// 0x33903ef9
- (long)dataCount;	// 0x33904025
- (void)dealloc;	// 0x339041c1
- (id)hashForDataAtIndex:(long)index;	// 0x33903e91
- (BOOL)isLoading;	// 0x33903535
- (void)reloadStoreData;	// 0x33904079
// converted property getter: - (id)title;	// 0x33903525
@end

