/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class ATVFavoritesControlFactory, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreFavoriteListItemProvider : NSObject <BRProvider> {
@private
	ATVFavoritesControlFactory *_factory;	// 4 = 0x4
	NSDictionary *_catalogItem;	// 8 = 0x8
}
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x338d768d
- (id)initWithCatalogItem:(id)catalogItem;	// 0x338d7609
- (id)controlFactory;	// 0x338d759d
- (id)dataAtIndex:(long)index;	// 0x338d7579
- (long)dataCount;	// 0x338d7589
- (void)dealloc;	// 0x338d75ad
- (id)hashForDataAtIndex:(long)index;	// 0x338d756d
@end

