/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPhotoMediaCollection.h> // Unknown library


@interface ATVMusicCoversCollectionProxy : BRPhotoMediaCollection {
}
+ (id)_musicCoversPredicate;	// 0x33907a75
+ (id)collectionProxy;	// 0x33907d39
+ (id)provider;	// 0x33907c71
- (id)collectionID;	// 0x339079b1
- (id)collectionName;	// 0x339079bd
- (id)mediaAssets;	// 0x33907b19
@end

