/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"


__attribute__((visibility("hidden")))
@interface ATVMusicStoreTVMetadataProvider : ATVMusicStoreBaseMetadataProvider {
}
+ (void)_initializeAbbreviatedTransformers;	// 0x338e5e69
+ (void)_initializeDetailedTransformers;	// 0x338e5f21
+ (void)_initializeMappings:(id)mappings;	// 0x338e5f69
+ (void)initialize;	// 0x338e63c5
- (id)_formatControlForStoreOffer:(id)storeOffer requestedBy:(id)by;	// 0x338e6489
- (void)_populateAbbreviatedMetadata:(id)metadata withStoreOffer:(id)storeOffer;	// 0x338e5c39
- (void)_populateDetailedMetadata:(id)metadata withStoreOffer:(id)storeOffer;	// 0x338e586d
- (void)_populateMetadataForControl:(id)control withStoreOffer:(id)storeOffer;	// 0x338e5d8d
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x338e6239
- (void)populateMetadataForControl:(id)control;	// 0x338e6221
@end

