/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library

@class NSMutableDictionary, NSString;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreTabManager : BRSingleton {
@private
	NSMutableDictionary *_tabsContainer;	// 4 = 0x4
	NSString *_savedTabsFilePath;	// 8 = 0x8
}
+ (void)setSingleton:(id)singleton;	// 0x338e40f5
+ (id)singleton;	// 0x338e40e9
- (id)init;	// 0x338e425d
- (void)_loadTabs;	// 0x338e435d
- (void)_saveTabs;	// 0x338e42f1
- (id)_tabs;	// 0x338e4101
- (void)dealloc;	// 0x338e4201
- (BOOL)preferredSegmentExistsForTabName:(id)tabName;	// 0x338e4159
- (id)preferredSegmentNameForTabName:(id)tabName;	// 0x338e41d9
- (BOOL)segmentNamed:(id)named isPreferredSegmentForTabName:(id)tabName;	// 0x338e412d
- (void)setPreferredSegmentName:(id)name forTabName:(id)tabName;	// 0x338e4175
@end

