/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library

@class NSDictionary, BRMerchant;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreCatalogItemController : BRController {
@private
	NSDictionary *_itemDictionary;	// 56 = 0x38
	BRMerchant *_merchant;	// 60 = 0x3c
}
@property(retain) NSDictionary *itemDictionary;	// G=0x338d1c69; S=0x338d1e51; converted property
@property(readonly, retain) BRMerchant *merchant;	// G=0x338d1c79; converted property
- (id)initWithItemDictionary:(id)itemDictionary;	// 0x338d1ef9
- (void)augmentRelatedContentItemsFromPage:(id)page;	// 0x338d21e9
- (void)dealloc;	// 0x338d1e89
- (void)fetchRelatedContent;	// 0x338d1d99
- (void)fetchRelatedContentFromURL:(id)url;	// 0x338d1c89
// converted property getter: - (id)itemDictionary;	// 0x338d1c69
// converted property getter: - (id)merchant;	// 0x338d1c79
- (void)relatedContentLoaded:(id)loaded;	// 0x338d1e29
- (void)relatedContentReceived:(id)received;	// 0x338d2031
// converted property setter: - (void)setItemDictionary:(id)dictionary;	// 0x338d1e51
@end

