/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library

@class NSDictionary, BRWaitPromptControl;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreAcquisitionController : BRController {
@private
	NSDictionary *_offer;	// 56 = 0x38
	BRWaitPromptControl *_waitPrompt;	// 60 = 0x3c
}
- (id)initWithOffer:(id)offer;	// 0x3391b24d
- (void)_acquire;	// 0x3391ae6d
- (void)_acquisitionFailed:(id)failed;	// 0x3391b0e9
- (void)_acquisitionSuccessful:(id)successful;	// 0x3391b409
- (void)_dismiss:(id)dismiss;	// 0x3391adc1
- (void)_enablePrompt:(id)prompt;	// 0x3391ae29
- (void)dealloc;	// 0x3391b079
- (BOOL)requiresAuthentication:(id *)authentication mode:(int *)mode;	// 0x3391b051
- (void)wasPopped;	// 0x3391af75
- (void)wasPushed;	// 0x3391b021
@end

