/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRControl.h> // Unknown library

@class BRDropShadowControl, BRTextControl, BRReflectedImageControl;

@interface ATVMusicStoreDownloadFailurePopup : BRControl {
@private
	BRControl *_boundingControl;	// 40 = 0x28
	BRTextControl *_directionsTextCtl;	// 44 = 0x2c
	BRTextControl *_messageTextCtl;	// 48 = 0x30
	BRTextControl *_optionsTextCtl;	// 52 = 0x34
	BRReflectedImageControl *_warningImage;	// 56 = 0x38
	BRDropShadowControl *_shadow;	// 60 = 0x3c
	CGSize _size;	// 64 = 0x40
}
+ (void)_postDialog:(id)dialog;	// 0x338d6b31
+ (void)_postDialogWhenReady:(id)ready;	// 0x338d6b81
+ (void)postDownloadFailurePopup:(id)popup;	// 0x338d6c1d
- (id)_initWithAsset:(id)asset;	// 0x338d6d09
- (BOOL)brEventAction:(id)action;	// 0x338d6b05
- (void)layoutSubcontrols;	// 0x338d732d
- (CGSize)sizeThatFits:(CGSize)fits;	// 0x338d722d
@end

