/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVCatalogApplianceController.h"
#import "BRTabControlDelegate.h"

@class NSTimer, BRControl, BRTabControl;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreTabbedPageController : ATVCatalogApplianceController <BRTabControlDelegate> {
@private
	BRControl *_contentControl;	// 92 = 0x5c
	BRTabControl *_tabControl;	// 96 = 0x60
	NSTimer *_activeTabSelectionChangedTimer;	// 100 = 0x64
	BOOL _showingWaitContent;	// 104 = 0x68
	BOOL _initialTabContentLoaded;	// 105 = 0x69
	BOOL _transitionInhibited;	// 106 = 0x6a
}
- (id)initWithContentControl:(id)contentControl tabControl:(id)control;	// 0x338e3e05
- (void)_delayedTabSelectionTimerFired:(id)fired;	// 0x338e3c4d
- (void)_focusFirstControlBelowTabControl;	// 0x338e3901
- (void)_focusTabControl;	// 0x338e39bd
- (id)_preferredTabSegmentInTab;	// 0x338e379d
- (void)_replaceScrollerContentBelowTabWithControls:(id)controls;	// 0x338e39ed
- (id)_scrollPlane;	// 0x338e3a99
- (id)_tabDictionary;	// 0x338e38a9
- (id)_tabName;	// 0x338e3879
- (id)contentWithStateControl:(id)stateControl;	// 0x338e4031
- (void)dealloc;	// 0x338e3da9
- (id)errorContent;	// 0x338e3b31
- (BOOL)shouldAllowTransitionOnSwap;	// 0x338e3785
- (BOOL)shouldShowWaitContent;	// 0x338e376d
- (void)tabControl:(id)control didSelectTabItem:(id)item;	// 0x338e3bc1
- (void)tabControl:(id)control willSelectTabItem:(id)item;	// 0x338e3761
- (void)tabControlDidChangeNumberOfTabItems:(id)tabControl;	// 0x338e3765
- (id)waitContent;	// 0x338e3b71
- (float)waitContentDelay;	// 0x338e3769
- (void)willEnterCompleteState;	// 0x338e3ab9
@end

