/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRControl.h> // Unknown library

@class NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVMusicStoreRottenTomatoesControl : BRControl {
@private
	NSDictionary *_itemDictionary;	// 40 = 0x28
}
+ (id)rottenTomatesControlWithDictionary:(id)dictionary;	// 0x3390ea19
- (id)initWithDictionary:(id)dictionary;	// 0x3390e9c9
- (CGRect)_addTextControlWithAttributedString:(id)attributedString maxSize:(CGSize)size origin:(CGPoint)origin;	// 0x3390eafd
- (CGRect)_addTextControlWithAttributedString:(id)attributedString maxSize:(CGSize)size xOrigin:(float)origin topLine:(float)line;	// 0x3390f87d
- (CGRect)_addTextControlWithText:(id)text attributes:(id)attributes maxSize:(CGSize)size origin:(CGPoint)origin;	// 0x3390ea4d
- (id)_imageForFreshnessRating:(int)freshnessRating;	// 0x3390ead5
- (id)_labelForFreshnessRating:(int)freshnessRating locInfo:(id)info;	// 0x3390e919
- (id)accessibilityLabel;	// 0x3390eabd
- (void)dealloc;	// 0x3390e981
- (void)layoutSubcontrols;	// 0x3390ebb1
@end

