/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRPosterControl.h> // Unknown library
#import "AppleTV-Structs.h"

@class NSTimer;

__attribute__((visibility("hidden")))
@interface ATVRentalPosterControl : BRPosterControl {
@private
	NSTimer *_expiryTextTimer;	// 232 = 0xe8
}
+ (id)posterForMediaItem:(ATVMediaItemRef)mediaItem;	// 0x33919da9
- (id)initWithMediaItem:(ATVMediaItemRef)mediaItem;	// 0x33919be5
- (void)_expiryTextTimerFired:(id)fired;	// 0x3391991d
- (void)_itemCacheStateChanged:(id)changed;	// 0x3391a07d
- (void)_rentalItemPropertySet:(id)set;	// 0x33919909
- (void)_startExpiryTextTimer;	// 0x3391999d
- (void)_stopExpiryTextTimer;	// 0x33919971
- (void)_updateTitleStrings;	// 0x33919e3d
- (id)accessibilityLabel;	// 0x3391a10d
- (BOOL)brEventAction:(id)action;	// 0x33919a0d
- (void)controlWasActivated;	// 0x33919b55
- (void)controlWasDeactivated;	// 0x33919b19
- (void)controlWasFocused;	// 0x33919add
- (void)controlWasUnfocused;	// 0x33919aa1
- (void)dealloc;	// 0x33919b91
@end

