/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVRCPatternMatcherDelegate.h"
#import <NSObject.h> // Unknown library
#import "AppleTV-Structs.h"

@class NSString, NSArray;

@interface ATVRemoteSet : NSObject <ATVRCPatternMatcherDelegate> {
@private
	NSArray *_remoteSet;	// 4 = 0x4
	NSString *_name;	// 8 = 0x8
	BOOL _custom;	// 12 = 0xc
}
@property(assign) BOOL custom;	// G=0x338efa49; S=0x338efa59; converted property
@property(retain) NSString *name;	// G=0x338efa39; S=0x338f06a5; converted property
- (id)init;	// 0x338f0a61
- (id)initWithDictionary:(id)dictionary;	// 0x338f0af9
- (id)_initPatternMatcherArray;	// 0x338f0415
- (void)_releasePatternMatchers;	// 0x338f0351
- (void)_setupTargetEventForMatcher:(id)matcher index:(int)index;	// 0x338efa69
- (void)_setupTargetRemoteEvents;	// 0x338f03bd
- (void)applyLearnedButtonsToSet:(id)set buttons:(NSRange)buttons;	// 0x338f056d
// converted property getter: - (BOOL)custom;	// 0x338efa49
- (void)dealloc;	// 0x338f0a0d
- (id)encodeToDictionary;	// 0x338f0761
- (int)findIdenticalButtonPattern:(id)pattern;	// 0x338f0521
- (id)getPatternMatcher:(int)matcher;	// 0x338f0945
- (id)getPatternSet:(int)set;	// 0x338f0965
- (BOOL)hasExtendedSet;	// 0x338f0729
- (BOOL)isEqual:(id)equal;	// 0x338f0649
- (void)matcherButtonDown:(id)down;	// 0x338f08d1
- (void)matcherButtonRelease:(id)release;	// 0x338efa35
// converted property getter: - (id)name;	// 0x338efa39
- (int)processEvent:(id)event;	// 0x338f0989
- (void)resetMatchers;	// 0x338f06dd
// converted property setter: - (void)setCustom:(BOOL)custom;	// 0x338efa59
// converted property setter: - (void)setName:(id)name;	// 0x338f06a5
- (void)setPairingInfo:(unsigned long)info pairingMask:(unsigned long)mask payloadMask:(unsigned long)mask3;	// 0x338f05e5
@end

