/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import "BRSelectionHandler.h"
#import "AppleTV-Structs.h"
#import "BRControlFactory.h"
#import <NSObject.h> // Unknown library

@class NSMutableArray;

@interface ATVRentedMediaProvider : NSObject <BRProvider, BRSelectionHandler, BRControlFactory> {
@private
	ATVMediaTypeRef _mediaType;	// 4 = 0x4
	ATVMediaQueryRef _dataQuery;	// 8 = 0x8
	NSMutableArray *_rentedMovies;	// 12 = 0xc
}
+ (id)providerWithMediaType:(ATVMediaTypeRef)mediaType;	// 0x3390d23d
- (id)init;	// 0x3390d21d
- (id)initWithMediaType:(ATVMediaTypeRef)mediaType;	// 0x3390d281
- (void)_accountLoggedOut:(id)anOut;	// 0x3390d151
- (void)_reloadRentals;	// 0x3390d5e5
- (void)_rentalQueryComplete;	// 0x3390d6c5
- (id)controlFactory;	// 0x3390d075
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x3390d595
- (id)dataAtIndex:(long)index;	// 0x3390d1fd
- (long)dataCount;	// 0x3390d1dd
- (void)dealloc;	// 0x3390d391
- (BOOL)handleSelectionForControl:(id)control;	// 0x3390d4e9
- (id)hashForDataAtIndex:(long)index;	// 0x3390d49d
@end

