/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRViewController.h> // Unknown library

@class NSTimer;

@interface ATVRebootWaitController : BRViewController {
@private
	NSTimer *_holdoffTimer;	// 60 = 0x3c
	float _lastProgressPercent;	// 64 = 0x40
}
- (id)init;	// 0x338a0745
- (void)_holdOffScreenSaver:(id)saver;	// 0x338a0589
- (BOOL)brEventAction:(id)action;	// 0x338a0559
- (void)configureForRebootWait;	// 0x338a06e1
- (void)configureForSoftwareUpdates;	// 0x338a067d
- (void)dealloc;	// 0x338a055d
- (void)setUpdatePercentage:(float)percentage;	// 0x338a0609
- (void)wasDismissed;	// 0x338a05dd
@end

