/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <NSObject.h> // Unknown library

@class ATVRemoteSet, NSTimer, ATVRCCapture, NSMutableArray;

@interface ATVRCManager : NSObject {
@private
	int _runState;	// 4 = 0x4
	ATVRCCapture *_trpCapture;	// 8 = 0x8
	NSMutableArray *_remoteSets;	// 12 = 0xc
	ATVRemoteSet *_learningSet;	// 16 = 0x10
	ATVRemoteSet *_appleRemoteSet;	// 20 = 0x14
	ATVRemoteSet *_temporaryActiveSet;	// 24 = 0x18
	BOOL _appleRemoteInUse;	// 28 = 0x1c
	NSTimer *_discontinuityTrigger;	// 32 = 0x20
	NSTimer *_ledResetTimer;	// 36 = 0x24
	unsigned short _customPage;	// 40 = 0x28
	unsigned short _customUsage;	// 42 = 0x2a
	BOOL _a39LegacyDispatch;	// 44 = 0x2c
	unsigned _pairingUID;	// 48 = 0x30
	opaque_pthread_mutex_t _mutex;	// 52 = 0x34
}
@property(readonly, assign) BOOL appleRemoteInUse;	// G=0x338eda71; converted property
@property(readonly, retain) ATVRemoteSet *learningSet;	// G=0x338ee1b5; converted property
@property(readonly, retain) NSMutableArray *remoteSets;	// G=0x338edb69; converted property
@property(assign) int state;	// G=0x338ee1e5; S=0x338ee215; converted property
@property(readonly, retain) ATVRemoteSet *temporaryActiveSet;	// G=0x338edd89; converted property
+ (id)sharedManager;	// 0x338ed8a1
- (id)init;	// 0x338ed799
- (void)_addRemoteSet:(id)set;	// 0x338ed6dd
- (void)_clearActiveRemoteSets;	// 0x338ed26d
- (id)_defaultCustomName;	// 0x338ed0a9
- (void)_discontinuityTrigger:(id)trigger;	// 0x338ed9e1
- (void)_doSystemActivityNotification;	// 0x338ed3f1
- (void)_enterLearningState;	// 0x338ed5d1
- (void)_eventRecognized:(BOOL)recognized;	// 0x338ed045
- (void)_exitLearningState;	// 0x338ed589
- (id)_findIdenticalActiveRemoteSet:(id)set;	// 0x338ed63d
- (BOOL)_isCustomEvent:(id)event;	// 0x338ed189
- (void)_ledReset:(id)reset;	// 0x338ed999
- (BOOL)_loadActiveRemoteSets;	// 0x338ee6e5
- (id)_loadAppleRemoteSet;	// 0x338ee539
- (id)_loadRemoteSet:(id)set;	// 0x338ed1dd
- (id)_maskToggleBits:(id)bits;	// 0x338ed2b9
- (BOOL)_nameInExistsInSets:(id)sets;	// 0x338ed115
- (void)_pairAppleRemote:(unsigned long)remote;	// 0x338ed735
- (BOOL)_processLearningEvent:(id)event;	// 0x338ed45d
- (void)_resetDiscontinuityTrigger;	// 0x338ed519
- (void)_resetLEDTimer;	// 0x338ecfdd
- (BOOL)_saveActiveRemoteSets;	// 0x338ee845
- (void)_setState:(int)state;	// 0x338ecfcd
- (id)_setTemporaryActiveSet:(id)set;	// 0x338ed6a1
- (void)_unpairAppleRemote;	// 0x338ed711
- (void)addRemoteSet:(id)set;	// 0x338edbd1
// converted property getter: - (BOOL)appleRemoteInUse;	// 0x338eda71
- (void)applyCaptureToButton:(int)button;	// 0x338ee02d
- (void)applyCaptureToPlayButtonOnly;	// 0x338edf8d
- (void)applyLearnedButtonsToSet:(id)set buttons:(NSRange)buttons;	// 0x338ede29
- (id)applyLearningSet;	// 0x338eded9
- (double)captureProgress;	// 0x338ee0f5
- (id)capturedPatternSet;	// 0x338ee0b5
- (void)dealloc;	// 0x338ed8e5
- (void)endLearn;	// 0x338ee145
- (id)findIdenticalActiveRemoteSet:(id)set;	// 0x338edb99
- (int)findPatternInActiveSets:(id)activeSets;	// 0x338ed775
- (int)findPatternInActiveSets:(id)activeSets includeLearningSet:(BOOL)set excludeExtendedRemoteSet:(id)set3 excludeRange:(NSRange)range;	// 0x338edc55
- (id)identifyCapture:(int)capture;	// 0x338ee5b9
// converted property getter: - (id)learningSet;	// 0x338ee1b5
- (void)pairAppleRemote:(unsigned long)remote;	// 0x338edad1
- (BOOL)processEvent:(id)event;	// 0x338ee291
// converted property getter: - (id)remoteSets;	// 0x338edb69
- (void)removeRemoteSet:(id)set;	// 0x338edc05
- (void)resetLearningSet;	// 0x338edb05
- (void)setCustomPage:(unsigned short)page withUsage:(unsigned short)usage;	// 0x338ee249
- (void)setName:(id)name remoteSet:(id)set;	// 0x338eddb9
// converted property setter: - (void)setState:(int)state;	// 0x338ee215
- (id)setTemporaryActiveSet:(id)set;	// 0x338edd49
- (void)startLearn;	// 0x338ee175
// converted property getter: - (int)state;	// 0x338ee1e5
// converted property getter: - (id)temporaryActiveSet;	// 0x338edd89
- (void)unpairAppleRemote;	// 0x338edaa1
@end

