/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSingleton.h> // Unknown library

@class NSTimer, NSURLDownload, NSMutableArray;

@interface ATVRetailDemoModeManager : BRSingleton {
@private
	NSTimer *_retailPlaybackLimitTimer;	// 4 = 0x4
	BOOL _hasStartedPlaying;	// 8 = 0x8
	NSURLDownload *_retailMovieDownload;	// 12 = 0xc
	NSMutableArray *_topPodcastsFavCandidates;	// 16 = 0x10
	NSMutableArray *_topShowsFavCandidates;	// 20 = 0x14
}
+ (void)checkAndStart;	// 0x339222dd
+ (id)retailDemoCacheDir;	// 0x33922155
+ (BOOL)retailDemoMovieDownloadComplete;	// 0x339220a1
+ (id)retailDemoMoviePath;	// 0x33922121
+ (void)setSingleton:(id)singleton;	// 0x33921995
+ (id)singleton;	// 0x33921989
- (id)init;	// 0x339221ed
- (void)_downloadRetailDemoMovie;	// 0x33922379
- (void)_fetchNextPodcastFav;	// 0x33922841
- (void)_fetchNextTVShowFav;	// 0x33922cf5
- (void)_nowPlayingStateChanged:(id)changed;	// 0x33921fad
- (void)_podcastReady:(id)ready;	// 0x33921b89
- (id)_retailDemoMovieURL;	// 0x33921d29
- (void)_retailPlaybackLimitTimerFired:(id)fired;	// 0x33921e3d
- (void)_retryMovieDownloadLater;	// 0x33921cf5
- (BOOL)_shouldLimitPlaybackForAsset:(id)asset;	// 0x33921f41
- (void)_startPlaybackLimitTimer;	// 0x33921e89
- (void)_topPodcastsReady:(id)ready;	// 0x339229ad
- (void)_topTVShowsReady:(id)ready;	// 0x339224f9
- (void)_tvShowReady:(id)ready;	// 0x339219f5
- (void)_updatePodcastFavorites;	// 0x33922b0d
- (void)_updateTVShowFavorites;	// 0x33922659
- (void)dealloc;	// 0x33922199
- (void)download:(id)download didFailWithError:(id)error;	// 0x33922335
- (void)downloadDidFinish:(id)download;	// 0x339219a1
- (void)updateRetailFavorites;	// 0x33922079
@end

