/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSArray;

__attribute__((visibility("hidden")))
@interface ATVRCButtonPatternSet : NSObject {
@private
	NSArray *_commandPattern;	// 4 = 0x4
	NSArray *_repeatPattern;	// 8 = 0x8
	double _maxRepeatInterval;	// 12 = 0xc
}
@property(retain) NSArray *commandPattern;	// G=0x338ebdb9; S=0x338ec48d; converted property
@property(assign) double maxRepeatInterval;	// G=0x338ebded; S=0x338ebdd9; converted property
@property(retain) NSArray *repeatPattern;	// G=0x338ebdc9; S=0x338ec455; converted property
- (id)initWithDictionary:(id)dictionary;	// 0x338ec521
- (id)_decodePatternFromDictionary:(id)dictionary;	// 0x338ebe11
- (id)_encodePatternToDictionary:(id)dictionary;	// 0x338ebf5d
- (void)clear;	// 0x338ec3c5
// converted property getter: - (id)commandPattern;	// 0x338ebdb9
- (void)dealloc;	// 0x338ec4c5
- (id)description;	// 0x338ec1b5
- (id)encodeToDictionary;	// 0x338ec2fd
- (BOOL)isEqual:(id)equal;	// 0x338ec095
- (BOOL)isOneShot;	// 0x338ec415
- (BOOL)isValid;	// 0x338ebdfd
// converted property getter: - (double)maxRepeatInterval;	// 0x338ebded
// converted property getter: - (id)repeatPattern;	// 0x338ebdc9
// converted property setter: - (void)setCommandPattern:(id)pattern;	// 0x338ec48d
// converted property setter: - (void)setMaxRepeatInterval:(double)interval;	// 0x338ebdd9
// converted property setter: - (void)setRepeatPattern:(id)pattern;	// 0x338ec455
@end

