/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


@interface ATVScreenSaverArchiver : NSObject {
}
+ (void)_dataClientConnectionHandler:(id)handler;	// 0x339107dd
+ (id)_iTunesServerIDFromArchivedServerID:(id)archivedServerID;	// 0x3390f935
+ (id)_parentalControlVerificationForArchive:(id)archive;	// 0x3390fa49
+ (void)_postScreenSaverDataReadyNotificationForCollection:(id)collection;	// 0x3390fd91
+ (id)_providerForCollection:(id)collection;	// 0x3390fb6d
+ (BOOL)_queryScreenSaverDataForArchive:(id)archive useDefaultServer:(BOOL)server connect:(BOOL)connect;	// 0x33910589
+ (id)archiveForCollection:(id)collection;	// 0x33910205
+ (void)requestScreenSaverFromArchive:(id)archive;	// 0x339101ed
+ (void)requestScreenSaverFromArchive:(id)archive connect:(BOOL)connect;	// 0x3390ffbd
+ (id)screenSaverCollectionIDFromArchive:(id)archive;	// 0x3390ff0d
+ (id)screenSaverCollectionNameFromArchive:(id)archive;	// 0x3390ff65
+ (id)screenSaverServerIDFromArchive:(id)archive;	// 0x3390fe95
+ (id)screenSaverTypeFromArchive:(id)archive;	// 0x3390fed5
@end

