/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRControl.h> // Unknown library

@class BRProgressBarWidget, BRImageControl, BRTextControl;

__attribute__((visibility("hidden")))
@interface ATVSWUProgressView : BRControl {
@private
	BRImageControl *_image;	// 40 = 0x28
	BRProgressBarWidget *_progress;	// 44 = 0x2c
	BRTextControl *_text;	// 48 = 0x30
	float _lastProgressPercentage;	// 52 = 0x34
}
- (id)init;	// 0x3390cb11
- (id)initForUpdateProgress;	// 0x3390c9c5
- (void)dealloc;	// 0x3390c959
- (void)layoutSubcontrols;	// 0x3390cc19
- (void)setUpdatePercentage:(float)percentage;	// 0x3390c915
@end

