/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVFavorite.h"

@class ATVStoreFavoriteRefreshTask, NSDate, NSString, NSDictionary, NSSet;

@interface ATVStoreFavorite : ATVFavorite {
@private
	int _itemType;	// 16 = 0x10
	NSString *_dsid;	// 20 = 0x14
	NSString *_storeFront;	// 24 = 0x18
	NSString *_artworkURL;	// 28 = 0x1c
	NSString *_thumbnailArtworkURL;	// 32 = 0x20
	NSString *_latestContentURL;	// 36 = 0x24
	NSDictionary *_latestSeason;	// 40 = 0x28
	ATVStoreFavoriteRefreshTask *_refreshTask;	// 44 = 0x2c
	unsigned _userOrder;	// 48 = 0x30
	NSDate *_autoBlueDotStartDate;	// 52 = 0x34
	id _completionHandler;	// 56 = 0x38
	NSSet *_autoBlueDotSeasons;	// 60 = 0x3c
}
@property(readonly, retain) NSSet *autoBlueDotSeasons;	// G=0x33901d71; converted property
@property(readonly, retain) NSDate *autoBlueDotStartDate;	// G=0x33901d61; converted property
@property(readonly, retain) NSString *dsid;	// G=0x33901d11; converted property
@property(assign) int itemType;	// G=0x33901da5; S=0x33901db5; @synthesize=_itemType
@property(readonly, retain) NSString *storeFront;	// G=0x33901d21; converted property
@property(assign) unsigned userOrder;	// G=0x33901d95; S=0x33901d81; @synthesize=_userOrder
+ (id)lookupStoreFavoriteFromFeed:(id)feed initIfNotFound:(BOOL)found;	// 0x339026a5
- (id)initWithCatalogItem:(id)catalogItem;	// 0x33902d51
- (id)initWithDictionary:(id)dictionary;	// 0x33902b3d
- (void)_cancelRefreshBackgroundTask;	// 0x33901dc5
- (id)_dateOfMostRecentEpisodeWithBlueDot;	// 0x33902f3d
- (void)_setupRefreshBackgroundTask;	// 0x33901e0d
- (BOOL)_setupWithCatalogItem:(id)catalogItem;	// 0x33902399
- (id)artworkURLString;	// 0x33901d31
// converted property getter: - (id)autoBlueDotSeasons;	// 0x33901d71
// converted property getter: - (id)autoBlueDotStartDate;	// 0x33901d61
- (void)dealloc;	// 0x33902a55
- (void)didCompleteRefreshStoreDataAttempt;	// 0x339022f5
// converted property getter: - (id)dsid;	// 0x33901d11
- (void)encodeWithDictionary:(id)dictionary;	// 0x339028b1
// declared property getter: - (int)itemType;	// 0x33901da5
- (id)itemsFromLatestSeason;	// 0x339022c9
- (id)latestContentURLString;	// 0x33901d51
- (id)latestSeasonID;	// 0x3390225d
- (void)refreshStoreData:(id)data;	// 0x3390234d
- (void)remove;	// 0x339027f5
- (void)save;	// 0x33902831
// declared property setter: - (void)setItemType:(int)type;	// 0x33901db5
// declared property setter: - (void)setUserOrder:(unsigned)order;	// 0x33901d81
// converted property getter: - (id)storeFront;	// 0x33901d21
- (id)thumbnailArtworkURLString;	// 0x33901d41
- (void)updateWithPageDictionaryFromLatestSeason:(id)latestSeason;	// 0x33902fad
// declared property getter: - (unsigned)userOrder;	// 0x33901d95
@end

