/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library
#import "BRProvider.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaRateListItemProvider : NSObject <BRProvider> {
@private
	ATVSedonaCatalogItem *_catalogItem;	// 4 = 0x4
}
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x3391ec19
- (id)init;	// 0x3391ec01
- (id)initWithCatalogItem:(id)catalogItem;	// 0x3391ec95
- (id)controlFactory;	// 0x3391eb99
- (id)dataAtIndex:(long)index;	// 0x3391eb75
- (long)dataCount;	// 0x3391eb85
- (void)dealloc;	// 0x3391ec4d
- (id)hashForDataAtIndex:(long)index;	// 0x3391ebb9
@end

