/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class BRMerchant, NSString, NSArray, NSMutableDictionary, NSDictionary;

__attribute__((visibility("hidden")))
@interface ATVSedonaCatalogItem : NSObject {
@private
	NSMutableDictionary *_catalogItem;	// 4 = 0x4
	NSMutableDictionary *_parentItem;	// 8 = 0x8
	BRMerchant *_merchant;	// 12 = 0xc
	int _itemType;	// 16 = 0x10
}
@property(assign) float averageUserRating;	// G=0x33918c5d; S=0x339192d1; 
@property(readonly, assign) BOOL canBeQueued;	// G=0x33918f09; 
@property(readonly, assign) BOOL canBeRated;	// G=0x33918ed5; 
@property(readonly, assign) NSArray *coverArt;	// G=0x33918f3d; 
@property(readonly, assign) NSDictionary *data;	// G=0x33918825; @synthesize=_catalogItem
@property(readonly, assign) BOOL isMovie;	// G=0x33918de5; 
@property(readonly, assign) BOOL isQueued;	// G=0x33918e35; 
@property(readonly, assign) BOOL isTV;	// G=0x33918da9; 
@property(readonly, assign) BOOL isTVEpisode;	// G=0x33918d09; 
@property(readonly, assign) BOOL isTVSeason;	// G=0x33918d59; 
@property(readonly, assign) int ratingType;	// G=0x33918c01; 
@property(readonly, assign) NSString *title;	// G=0x33918f69; 
@property(readonly, assign) unsigned userRatingCount;	// G=0x33918b45; 
+ (id)itemWithCatalogItem:(id)catalogItem;	// 0x339190c9
- (id)init;	// 0x33919005
- (id)initWithCatalogItem:(id)catalogItem;	// 0x3391901d
- (id)_neValueForKey:(id)key;	// 0x33918995
- (void)_queueRequestComplete:(id)complete;	// 0x33918835
- (void)_rateRequestComplete:(id)complete;	// 0x339190fd
- (void)_setNeValue:(id)value forKey:(id)key;	// 0x33918929
- (void)addOrRemoveFromQueue;	// 0x339189fd
// declared property getter: - (float)averageUserRating;	// 0x33918c5d
// declared property getter: - (BOOL)canBeQueued;	// 0x33918f09
// declared property getter: - (BOOL)canBeRated;	// 0x33918ed5
// declared property getter: - (id)coverArt;	// 0x33918f3d
// declared property getter: - (id)data;	// 0x33918825
- (void)dealloc;	// 0x33918f95
// declared property getter: - (BOOL)isMovie;	// 0x33918de5
// declared property getter: - (BOOL)isQueued;	// 0x33918e35
// declared property getter: - (BOOL)isTV;	// 0x33918da9
// declared property getter: - (BOOL)isTVEpisode;	// 0x33918d09
// declared property getter: - (BOOL)isTVSeason;	// 0x33918d59
// declared property getter: - (int)ratingType;	// 0x33918c01
- (id)requestForAction:(int)action;	// 0x339191a5
// declared property setter: - (void)setAverageUserRating:(float)rating;	// 0x339192d1
// declared property getter: - (id)title;	// 0x33918f69
- (id)titleForAction:(int)action;	// 0x33918cc9
// declared property getter: - (unsigned)userRatingCount;	// 0x33918b45
@end

