/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRControl.h> // Unknown library

@class BRImageControl;

__attribute__((visibility("hidden")))
@interface ATVSedonaRateControl : BRControl {
@private
	float _initialRating;	// 40 = 0x28
	float _curRating;	// 44 = 0x2c
	float _actualRating;	// 48 = 0x30
	BRImageControl *_starImageControl;	// 52 = 0x34
}
@property(readonly, assign) float actualRating;	// G=0x339154bd; converted property
+ (float)postSedonaRateDialogWithItem:(id)item;	// 0x33915755
+ (id)rateControlWithItem:(id)item;	// 0x33915721
- (id)initWithItem:(id)item;	// 0x33915ae9
- (id)_imageForKey:(id)key;	// 0x33915671
- (id)_starImageForRating:(float)rating predicted:(BOOL)predicted;	// 0x339154d1
- (id)accessibilityLabel;	// 0x33915ad1
// converted property getter: - (float)actualRating;	// 0x339154bd
- (BOOL)brEventAction:(id)action;	// 0x339157b9
- (void)dealloc;	// 0x339156d9
- (BOOL)isAccessibilityElement;	// 0x339154cd
@end

