/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

//#import "AppleTV-Structs.h"
//#import <BRSettingsFacade.h> // Unknown library


@interface ATVSettingsFacade : BRSettingsFacade {
}
@property(assign) BOOL airTunesControlFromSpeakerIsEnabled;	// G=0x338fa5c9; S=0x338fa545; converted property
@property(assign) BOOL airTunesIsEnabled;	// G=0x338fa869; S=0x338fa789; converted property
@property(retain) id airTunesPassword;	// G=0x338fa6e5; S=0x338fa605; converted property
@property(assign) BOOL musicUseSoundCheck;	// G=0x338fab45; S=0x338faad9; converted property
@property(assign) BOOL screenSaverPanAndZoom;	// G=0x338fad85; S=0x338fad49; converted property
@property(assign) BOOL screenSaverPrefetchComplete;	// G=0x338fb1e1; S=0x338fb1a5; converted property
@property(assign) int screenSaverSecondsPerSlide;	// G=0x338fae2d; S=0x338fadf1; converted property
@property(retain) id screenSaverSelectedPath;	// G=0x338fb32d; S=0x338fb291; converted property
@property(assign) BOOL screenSaverShufflePhotos;	// G=0x338facdd; S=0x338faca1; converted property
@property(retain) id screenSaverSlideshowTheme;	// G=0x338fb259; S=0x338fb21d; converted property
@property(assign) int screenSaverTimeout;	// G=0x338fb111; S=0x338fb055; converted property
@property(retain) id screenSaverTransition;	// G=0x338fac45; S=0x338fac09; converted property
@property(assign) int sleepTimeout;	// G=0x338fb001; S=0x338faf51; converted property
+ (id)getMobileGestaltString:(CFStringRef)string;	// 0x338fbd95
+ (void)initializePlatformFacade;	// 0x338fb7e1
- (SCNetworkServiceRef)_copyNetworkServiceForInterface:(int)interface withPrefs:(SCPreferencesRef)prefs;	// 0x338fbe09
- (long)_itemCountForMediaType:(id)mediaType;	// 0x338fa451
- (BOOL)_saveConfiguration:(id)configuration forInterface:(int)interface withPrefs:(SCPreferencesRef)prefs;	// 0x338fbea9
- (BOOL)_setDNSWithAddresses:(id)addresses forService:(SCNetworkServiceRef)service;	// 0x338fc235
- (void)_setScreenSaverCollection:(id)collection;	// 0x338fa4f1
// converted property getter: - (BOOL)airTunesControlFromSpeakerIsEnabled;	// 0x338fa5c9
// converted property getter: - (BOOL)airTunesIsEnabled;	// 0x338fa869
// converted property getter: - (id)airTunesPassword;	// 0x338fa6e5
- (BOOL)airTunesPasswordIsEnabled;	// 0x338fa755
- (BOOL)bootedFromRecoveryPartition;	// 0x338fabe9
- (void)dealloc;	// 0x338fb9f9
- (id)hwSerialNumber;	// 0x338faab1
- (BOOL)hwSetSystemLanguage:(id)language;	// 0x338fbc15
- (long)mediaPhotoCount;	// 0x338fb621
- (long)mediaSongCount;	// 0x338fb765
- (long)mediaVideoCount;	// 0x338fb6e9
// converted property getter: - (BOOL)musicUseSoundCheck;	// 0x338fab45
- (void)resetAllSettings;	// 0x338fb801
- (BOOL)saveConfiguration:(id)configuration;	// 0x338fbb5d
- (id)screenSaverCollectionArchive;	// 0x338fb16d
- (id)screenSaverInvocation;	// 0x338fae95
// converted property getter: - (BOOL)screenSaverPanAndZoom;	// 0x338fad85
- (id)screenSaverPathForIdentifier:(id)identifier;	// 0x338fb2cd
- (id)screenSaverPaths;	// 0x338fb50d
- (int)screenSaverPhotoSpinFrequency;	// 0x338faef9
// converted property getter: - (BOOL)screenSaverPrefetchComplete;	// 0x338fb1e1
// converted property getter: - (int)screenSaverSecondsPerSlide;	// 0x338fae2d
// converted property getter: - (id)screenSaverSelectedPath;	// 0x338fb32d
// converted property getter: - (BOOL)screenSaverShufflePhotos;	// 0x338facdd
// converted property getter: - (id)screenSaverSlideshowTheme;	// 0x338fb259
// converted property getter: - (int)screenSaverTimeout;	// 0x338fb111
// converted property getter: - (id)screenSaverTransition;	// 0x338fac45
// converted property setter: - (void)setAirTunesControlFromSpeakerIsEnabled:(BOOL)speakerIsEnabled;	// 0x338fa545
// converted property setter: - (void)setAirTunesIsEnabled:(BOOL)enabled;	// 0x338fa789
// converted property setter: - (void)setAirTunesPassword:(id)password;	// 0x338fa605
// converted property setter: - (void)setMusicUseSoundCheck:(BOOL)check;	// 0x338faad9
// converted property setter: - (void)setScreenSaverPanAndZoom:(BOOL)zoom;	// 0x338fad49
- (void)setScreenSaverPhotoCollection:(id)collection;	// 0x338fba4d
// converted property setter: - (void)setScreenSaverPrefetchComplete:(BOOL)complete;	// 0x338fb1a5
// converted property setter: - (void)setScreenSaverSecondsPerSlide:(int)slide;	// 0x338fadf1
// converted property setter: - (void)setScreenSaverSelectedPath:(id)path;	// 0x338fb291
// converted property setter: - (void)setScreenSaverShufflePhotos:(BOOL)photos;	// 0x338faca1
// converted property setter: - (void)setScreenSaverSlideshowTheme:(id)theme;	// 0x338fb21d
// converted property setter: - (void)setScreenSaverTimeout:(int)timeout;	// 0x338fb055
// converted property setter: - (void)setScreenSaverTransition:(id)transition;	// 0x338fac09
// converted property setter: - (void)setSleepTimeout:(int)timeout;	// 0x338faf51
// converted property getter: - (int)sleepTimeout;	// 0x338fb001
- (id)slideshowScreensaverPlaybackOptions;	// 0x338fa44d
- (BOOL)syncIsSynced;	// 0x338fab81
- (id)versionEFI;	// 0x338fa97d
- (id)versionGF;	// 0x338fa8ed
- (id)versionIR;	// 0x338fa95d
- (id)versionOS;	// 0x338faa35
- (id)versionOSBuild;	// 0x338faa15
- (id)versionSoftwareBuild;	// 0x338faa55
@end

