/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAuthenticationResources.h> // Unknown library


@interface ATVSedonaAuthenticationResources : BRAuthenticationResources {
}
- (id)accountNameInstructions;	// 0x339183cd
- (id)accountNameLabel;	// 0x33918399
- (id)accountNameTitle;	// 0x33918379
- (id)accountPasswordTitle;	// 0x3391837d
- (id)connectionString;	// 0x33918401
- (id)defaultPasswordKey;	// 0x33918381
- (id)defaultUserNameKey;	// 0x3391838d
- (id)titleImage;	// 0x33918435
@end

