/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBackgroundTask.h> // Unknown library

@class ATVStoreFavorite, BRURLPlist;

__attribute__((visibility("hidden")))
@interface ATVStoreFavoriteRefreshTask : BRBackgroundTask {
@private
	ATVStoreFavorite *_favorite;	// 44 = 0x2c
	BRURLPlist *_curDocumentBeingFetched;	// 48 = 0x30
}
- (id)initWithFavorite:(id)favorite;	// 0x3390c685
- (void)_catalogControlRequestProcessed:(id)processed;	// 0x3390c6f1
- (void)dealloc;	// 0x3390c615
- (void)disable:(id)disable;	// 0x3390c4c1
- (BOOL)perform:(id)perform;	// 0x3390c4fd
- (void)stop;	// 0x3390c485
@end

