/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAccount.h> // Unknown library


@interface ATVSedonaAccount : BRAccount {
}
- (id)initWithAccountName:(id)accountName;	// 0x3391614d
- (id)_authenticate;	// 0x339161cd
- (void)_authenticationComplete:(id)complete;	// 0x33915ec1
- (void)authenticate;	// 0x33916021
- (void)dealloc;	// 0x339160f9
- (BOOL)isAuthenticated;	// 0x33915eb9
- (BOOL)isPasswordRequired;	// 0x33915ebd
- (void)resetAccountOptions;	// 0x33915fad
- (id)rootURL;	// 0x339160cd
- (id)searchURL;	// 0x33915eb5
- (id)type;	// 0x339160ad
@end

