/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaTVMetadataProvider : ATVMusicStoreBaseMetadataProvider {
@private
	ATVSedonaCatalogItem *_sedonaItem;	// 12 = 0xc
}
+ (void)_initializeAbbreviatedTransformers;	// 0x3391c275
+ (void)_initializeDetailedTransformers;	// 0x3391c2f5
+ (void)_initializeMappings:(id)mappings;	// 0x3391c33d
+ (void)initialize;	// 0x3391c785
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x3391c751
- (id)init;	// 0x3391c739
- (id)initWithCatalogItem:(id)catalogItem;	// 0x3391c891
- (void)_populateAbbreviatedMetadata:(id)metadata;	// 0x3391cce5
- (void)_populateDetailedMetadata:(id)metadata;	// 0x3391c8f5
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x3391c691
- (void)dealloc;	// 0x3391c849
- (void)populateMetadataForControl:(id)control;	// 0x3391c5b9
@end

