/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAlertController.h> // Unknown library
#import "BRTextFieldDelegate.h"

@class ATVIPv4AddressEntryControl, NSString;

__attribute__((visibility("hidden")))
@interface ATVSWUpdateServerIPController : BRAlertController <BRTextFieldDelegate> {
@private
	NSString *_serverIP;	// 84 = 0x54
	ATVIPv4AddressEntryControl *_editor;	// 88 = 0x58
}
- (id)init;	// 0x3390110d
- (id)_defaultServerIPAddress;	// 0x33901001
- (BOOL)_handleEventForAlertController:(id)alertController;	// 0x33901059
- (void)dealloc;	// 0x339010b1
- (void)layoutSubcontrols;	// 0x339012d9
- (void)textDidChange:(id)text;	// 0x33900ffd
- (void)textDidEndEditing:(id)text;	// 0x3390107d
@end

