/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBackgroundTask.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVSWUpdateCheckTask : BRBackgroundTask {
}
+ (BOOL)_shouldPerformCheck;	// 0x3390cdfd
+ (void)scheduleCheckAgainSoonTask;	// 0x3390cf41
+ (void)scheduleCheckRightAwayTask;	// 0x3390cea1
+ (void)scheduleNormalCheckTask;	// 0x3390cfe1
- (BOOL)perform:(id)perform;	// 0x3390ce6d
@end

