/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "AppleTV-Structs.h"
#import <BRSingleton.h> // Unknown library


@interface ATVSettingsHelper : BRSingleton {
}
+ (void)setSingleton:(id)singleton;	// 0x338fc355
+ (id)singleton;	// 0x338fc349
- (id)init;	// 0x338fc435
- (void)dealloc;	// 0x338fc371
- (BOOL)haveWeQuitSinceBoot;	// 0x338fc39d
- (BOOL)performObliterate;	// 0x338fc4f5
- (BOOL)performRestore;	// 0x338fc36d
- (BOOL)performUpdates:(id)updates;	// 0x338fc4bd
- (void)reboot;	// 0x338fc4a9
- (BOOL)setLowPowerMode:(BOOL)mode;	// 0x338fc369
- (BOOL)setNetworkSettings:(id)settings forInterface:(int)interface;	// 0x338fc365
- (void)setSSHEnabled:(BOOL)enabled;	// 0x338fc495
- (BOOL)setSystemLanguage:(id)language;	// 0x338fc361
- (BOOL)setTimeZoneFromMessage:(XXStruct_ScK7BA)message;	// 0x338fc4d1
@end

