/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreBaseMetadataProvider.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaTVSeasonMetadataProvider : ATVMusicStoreBaseMetadataProvider {
@private
	ATVSedonaCatalogItem *_sedonaItem;	// 12 = 0xc
}
+ (void)initialize;	// 0x3391f1c9
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x3391f195
- (id)init;	// 0x3391f17d
- (id)initWithCatalogItem:(id)catalogItem;	// 0x3391f2f1
- (id)controlForData:(id)data currentControl:(id)control requestedBy:(id)by;	// 0x3391f145
- (void)dealloc;	// 0x3391f2a9
- (void)populateMetadataForControl:(id)control;	// 0x3391f095
@end

