/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreCatalogAgent.h"
#import "AppleTV-Structs.h"


@interface ATVSedonaCatalogAgent : ATVMusicStoreCatalogAgent {
}
+ (void)_controlForURL:(id)url identifier:(id)identifier;	// 0x3391771d
+ (id)_headerControlsForPageItem:(id)pageItem;	// 0x339179b5
+ (id)_scrollerControlsFromHeaderControls:(id)headerControls collectionControls:(id)controls;	// 0x33917875
+ (id)catalogHandler;	// 0x33916c29
+ (id)mediaAssetForStoreOffer:(id)storeOffer;	// 0x339171f9
+ (void)playStoreItem:(id)item;	// 0x33917641
@end

