/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRTextFieldDelegate.h"
#import <BRMenuController.h> // Unknown library

@class BRMediatorProvider, ATVSearchAgent, NSString, BRTextEntryControl, BRImageControl;

@interface ATVSearchController : BRMenuController <BRTextFieldDelegate> {
@private
	BRTextEntryControl *_editor;	// 100 = 0x64
	BRImageControl *_arrow;	// 104 = 0x68
	ATVSearchAgent *_agent;	// 108 = 0x6c
	BRMediatorProvider *_recentSearchesProvider;	// 112 = 0x70
	NSString *_activeSearchRequest;	// 116 = 0x74
}
- (id)initWithSearchAgent:(id)searchAgent;	// 0x338f9a8d
- (void)_handleContextMenuSelection:(id)selection;	// 0x338f8f9d
- (void)_performSearchWithString:(id)string;	// 0x338f904d
- (void)_recentSearchTermSelected:(id)selected;	// 0x338f8f71
- (void)_searchComplete:(id)complete;	// 0x338f9fc5
- (BOOL)brEventAction:(id)action;	// 0x338f948d
- (id)controlToDim;	// 0x338f8f6d
- (void)dealloc;	// 0x338f98f9
- (long)defaultIndex;	// 0x338f93b9
- (BOOL)isNetworkDependent;	// 0x338f98d5
- (BOOL)isValidAfterDataUpdate;	// 0x338f8f59
- (void)layoutSubcontrols;	// 0x338f9dcd
- (id)providersForContextMenu;	// 0x338f91b9
- (id)searchAgent;	// 0x338f8f5d
- (void)searchWithString:(id)string;	// 0x338f989d
- (void)setHeaderTitle:(id)title;	// 0x338f9405
- (void)setKeyboardTextEntryStyle:(int)style;	// 0x338f987d
- (void)setSearchFieldLabel:(id)label;	// 0x338f946d
- (void)textDidChange:(id)text;	// 0x338f938d
- (void)textDidEndEditing:(id)text;	// 0x338f928d
@end

