/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRControl.h> // Unknown library

@class BRMediaPlayer;

__attribute__((visibility("hidden")))
@interface ATVScreenSaverControl : BRControl {
@private
	BRMediaPlayer *_player;	// 40 = 0x28
}
+ (id)screenSaverControlWithPlugin:(id)plugin screenSaverAutoFired:(BOOL)fired;	// 0x338f6a41
- (id)initWithPlugin:(id)plugin screenSaverAutoFired:(BOOL)fired;	// 0x338f6a79
- (BOOL)_nextTrackAction:(id)action;	// 0x338f6669
- (BOOL)_playPauseAction:(id)action;	// 0x338f66cd
- (void)_playerStateChanged:(id)changed;	// 0x338f673d
- (BOOL)_previousTrackAction:(id)action;	// 0x338f6605
- (void)_setNewPlayer:(id)player;	// 0x338f6775
- (id)accessibilityLabel;	// 0x338f65dd
- (BOOL)brEventAction:(id)action;	// 0x338f68f1
- (void)controlWasActivated;	// 0x338f6891
- (void)controlWasDeactivated;	// 0x338f6831
- (void)dealloc;	// 0x338f69d1
- (BOOL)isAccessibilityElement;	// 0x338f65d9
- (void)layoutSubcontrols;	// 0x338f6b4d
@end

