/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRSimpleMenuItem.h> // Unknown library

@class NSDate, NSString;

__attribute__((visibility("hidden")))
@interface ATVSearchTerm : BRSimpleMenuItem {
@private
	NSString *_searchTerm;	// 20 = 0x14
	NSDate *_lastUsed;	// 24 = 0x18
}
@property(readonly, retain) NSDate *lastUsed;	// G=0x338fa29d; converted property
@property(readonly, retain) NSString *searchTerm;	// G=0x338fa28d; converted property
+ (id)searchTermWithString:(id)string;	// 0x338fa3f9
- (id)initWithSearchTerm:(id)searchTerm date:(id)date;	// 0x338fa389
- (void)dealloc;	// 0x338fa32d
// converted property getter: - (id)lastUsed;	// 0x338fa29d
- (int)menuItemType;	// 0x338fa2b1
- (id)rightJustifiedText;	// 0x338fa2b5
// converted property getter: - (id)searchTerm;	// 0x338fa28d
- (id)title;	// 0x338fa2d9
- (int)titlePosition;	// 0x338fa2ad
- (void)updateLastUsed;	// 0x338fa2ed
@end

