/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "BRProvider.h"
#import <NSObject.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface ATVSedonaItemProvider : NSObject <BRProvider> {
@private
	NSMutableDictionary *_catalogItem;	// 4 = 0x4
	NSMutableArray *_items;	// 8 = 0x8
	BOOL _reverseOrder;	// 12 = 0xc
}
@property(assign, getter=isOrderReversed) BOOL orderReversed;	// G=0x3391510d; S=0x33915219; converted property
+ (id)providerWithCatalogItem:(id)catalogItem;	// 0x33915269
- (id)initWithCatalogItem:(id)catalogItem;	// 0x339153ed
- (void)_augmentCollectionItem:(id)item atIndex:(long)index;	// 0x3391511d
- (id)controlFactory;	// 0x339151f9
- (id)dataAtIndex:(long)index;	// 0x33915311
- (long)dataCount;	// 0x339151d9
- (void)dealloc;	// 0x339153a5
- (id)hashForDataAtIndex:(long)index;	// 0x3391529d
// converted property getter: - (BOOL)isOrderReversed;	// 0x3391510d
// converted property setter: - (void)setOrderReversed:(BOOL)reversed;	// 0x33915219
@end

