/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreSearchAgent.h"


__attribute__((visibility("hidden")))
@interface ATVSedonaSearchAgent : ATVMusicStoreSearchAgent {
}
- (void)_loadSearchURL:(id)url forSearchTerm:(id)searchTerm;	// 0x3391aa95
- (void)_searchComplete:(id)complete forSearchTerm:(id)searchTerm;	// 0x3391aa01
- (void)_searchRequestProcessed:(id)processed;	// 0x3391abf1
- (void)dealloc;	// 0x3391ab9d
@end

