/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRBackgroundTask.h> // Unknown library

@class NSTimer, NSArray, NSMutableDictionary, NSMutableArray;

@interface ATVScreenSaverPrefetchTask : BRBackgroundTask {
@private
	int _index;	// 44 = 0x2c
	NSArray *_assets;	// 48 = 0x30
	NSMutableArray *_loadingIDs;	// 52 = 0x34
	NSMutableDictionary *_faces;	// 56 = 0x38
	NSTimer *_timer;	// 60 = 0x3c
	BOOL _waitingForScreenSaverData;	// 64 = 0x40
	int _loadAttemptCount;	// 68 = 0x44
}
- (void)_imageLoadFailed:(id)failed;	// 0x3391090d
- (void)_imageLoadSucceeded:(id)succeeded;	// 0x33910979
- (void)_prefetch;	// 0x33910a9d
- (void)_reset;	// 0x33910f75
- (void)_screenSaverDataReady:(id)ready;	// 0x33910e45
- (void)_startPrefetchForItems:(id)items;	// 0x33910cd9
- (void)_updateFacesCacheWithFaces:(id)faces;	// 0x339108d9
- (void)dealloc;	// 0x33910a09
- (BOOL)isActive;	// 0x339109e5
- (BOOL)perform:(id)perform;	// 0x339110c5
- (void)stop;	// 0x33911075
@end

