/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVMusicStoreCatalogItemProviderFactory.h"

@class ATVSedonaCatalogItem;

__attribute__((visibility("hidden")))
@interface ATVSedonaCatalogItemProviderFactory : ATVMusicStoreCatalogItemProviderFactory {
@private
	ATVSedonaCatalogItem *_sedonaItem;	// 16 = 0x10
}
- (id)_addToQueueButtonProvider;	// 0x339168b1
- (id)_addToQueueListProvider;	// 0x339163cd
- (id)_initWithCatalogItem:(id)catalogItem;	// 0x339167ed
- (id)_rateButtonProvider;	// 0x33916a09
- (id)_rateListProvider;	// 0x33916419
- (id)abbreviatedMetadataProvider;	// 0x33916685
- (id)actionProviders;	// 0x339165a5
- (id)listProviders;	// 0x33916465
- (id)metadataProvider;	// 0x33916739
@end

