/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableDictionary, NSMutableArray;

@interface ATVSearchAgent : NSObject {
@private
	NSMutableDictionary *_resultsCache;	// 4 = 0x4
	NSMutableArray *_resultsCacheTerms;	// 8 = 0x8
}
+ (id)_searchTermCache;	// 0x338f8751
- (id)init;	// 0x338f86dd
- (void)cacheResults:(id)results forSearchTerm:(id)searchTerm;	// 0x338f88c5
- (long)cacheSize;	// 0x338f8629
- (id)cachedResultsForSearchTerm:(id)searchTerm;	// 0x338f881d
- (void)clearSavedSearchTerms;	// 0x338f8aad
- (id)contextMenuUtility;	// 0x338f8635
- (void)dealloc;	// 0x338f8681
- (id)defaultPreviewImage;	// 0x338f863d
- (BOOL)handlePlayForObject:(id)object;	// 0x338f8639
- (BOOL)isNetworkDependent;	// 0x338f8631
- (void)saveSearchTerm:(id)term;	// 0x338f8c69
- (id)savedSearchTerms;	// 0x338f8b79
- (void)search:(id)search;	// 0x338f8669
- (void)search:(id)search ignoringCache:(BOOL)cache;	// 0x338f8625
- (BOOL)showRecentSearches;	// 0x338f862d
@end

