/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRController.h> // Unknown library

@class ATVSedonaAccount, NSString;

@interface ATVSedonaController : BRController {
@private
	ATVSedonaAccount *_account;	// 56 = 0x38
	NSString *_preferredURL;	// 60 = 0x3c
	BOOL _autoPlay;	// 64 = 0x40
}
@property(assign, nonatomic) BOOL autoPlay;	// G=0x33918499; S=0x339184a9; @synthesize=_autoPlay
+ (id)controller;	// 0x33918801
+ (id)controllerWithPreferredURL:(id)preferredURL;	// 0x339187cd
- (id)init;	// 0x33918709
- (id)initWithPreferredURL:(id)preferredURL;	// 0x339186d1
// declared property getter: - (BOOL)autoPlay;	// 0x33918499
- (void)controlWasActivated;	// 0x339184e5
- (void)dealloc;	// 0x3391864d
- (BOOL)isNetworkDependent;	// 0x33918495
- (BOOL)requiresAuthentication:(id *)authentication mode:(int *)mode;	// 0x339184b9
// declared property setter: - (void)setAutoPlay:(BOOL)play;	// 0x339184a9
- (void)wasPushed;	// 0x339185fd
@end

