/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVDottedQuadEntryDelegate.h"
#import "BRMenuListItemProvider.h"
#import <BRMenuController.h> // Unknown library

@class NSString, ATVDottedQuadEntryController;
@protocol ATVTCPIPConfigDelegate;

@interface ATVTCPIPConfigController : BRMenuController <BRMenuListItemProvider, ATVDottedQuadEntryDelegate> {
@private
	id<ATVTCPIPConfigDelegate> _delegate;	// 100 = 0x64
	NSString *_address;	// 104 = 0x68
	NSString *_subnetMask;	// 108 = 0x6c
	NSString *_router;	// 112 = 0x70
	NSString *_dns;	// 116 = 0x74
	ATVDottedQuadEntryController *_ipController;	// 120 = 0x78
	ATVDottedQuadEntryController *_maskController;	// 124 = 0x7c
	ATVDottedQuadEntryController *_routerController;	// 128 = 0x80
	ATVDottedQuadEntryController *_dnsController;	// 132 = 0x84
	unsigned _forWireless : 1;	// 136 = 0x88
	unsigned _useDHCP : 1;	// 136 = 0x88
}
- (id)initWithWireless:(BOOL)wireless notifying:(id)notifying;	// 0x338eb531
- (void)_readCurrentConfiguration;	// 0x338eac39
- (void)_saveConfiguration;	// 0x338eb689
- (void)dealloc;	// 0x338ead59
- (void)entryComplete:(id)complete;	// 0x338eae31
- (float)heightForRow:(long)row;	// 0x338eac31
- (long)itemCount;	// 0x338eac2d
- (id)itemForRow:(long)row;	// 0x338eb2dd
- (void)itemSelected:(long)selected;	// 0x338eb375
- (BOOL)rowSelectable:(long)selectable;	// 0x338eac35
- (id)titleForRow:(long)row;	// 0x338eb295
@end

