/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRURLDocument.h> // Unknown library


@interface ATVURLDocument : BRURLDocument {
@private
	id _requestBlock;	// 52 = 0x34
}
+ (id)documentWithRequestBlock:(id)requestBlock;	// 0x338e85dd
- (id)initWithRequestBlock:(id)requestBlock;	// 0x338e858d
- (id)URLRequest;	// 0x338e84f1
- (void)dealloc;	// 0x338e8545
- (void)documentLoaded;	// 0x338e8611
@end

