/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


@interface ATVVersionInfo : NSObject {
}
+ (int)compareEFIVersion:(id)version withEFIVersion:(id)efiversion;	// 0x33901541
+ (int)compareIRVersion:(id)version withIRVersion:(id)irversion;	// 0x339017ad
+ (int)compareOSVersion:(id)version andBuild:(id)build withOSVersion:(id)osversion andBuild:(id)build4;	// 0x33901571
+ (int)compareSIVersion:(id)version withSIVersion:(id)siversion;	// 0x33901669
+ (id)currentEFIVersion;	// 0x3390146d
+ (id)currentIRVersion;	// 0x33901441
+ (id)currentOSBuildVersion;	// 0x339014d5
+ (id)currentOSVersion;	// 0x339014fd
+ (id)currentSIBootVersion;	// 0x33901525
+ (id)currentSIMainVersion;	// 0x33901431
+ (BOOL)isSIFirmwareValid;	// 0x3390143d
@end

