/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRVideoCacheManager.h> // Unknown library
#import "AppleTV-Structs.h"

@class AVAssetCache, BRStreamingMediaAsset, BRKeyValueObservingRegistry, NSMutableDictionary, NSTimer, AVPlayerLayer, AVQueuePlayer, AVPlayerItem, NSArray;
@protocol BRVideoCacheManagerDelegate;

@interface ATVVideoCacheManager : BRVideoCacheManager {
@private
	AVAssetCache *_rentalCache;	// 4 = 0x4
	AVAssetCache *_otherCache;	// 8 = 0x8
	AVAssetCache *_avFoundationPrivateCache;	// 12 = 0xc
	NSMutableDictionary *_cacheKeys;	// 16 = 0x10
	BRStreamingMediaAsset *_assetBeingCached;	// 20 = 0x14
	BRKeyValueObservingRegistry *_kvoRegistry;	// 24 = 0x18
	id<BRVideoCacheManagerDelegate> _delegate;	// 28 = 0x1c
	AVPlayerLayer *_playerLayer;	// 32 = 0x20
	AVQueuePlayer *_player;	// 36 = 0x24
	AVPlayerItem *_playerItem;	// 40 = 0x28
	NSArray *_selectableAudioTracks;	// 44 = 0x2c
	NSArray *_subtitleTracks;	// 48 = 0x30
	BOOL _isItemLikelyToKeepUp;	// 52 = 0x34
	BOOL _itemPrepared;	// 53 = 0x35
	NSTimer *_progressSampleTimer;	// 56 = 0x38
	double _computedBandwidth;	// 60 = 0x3c
	double _cacheStartTime;	// 68 = 0x44
	double _computedLikelyToKeepUpTime;	// 76 = 0x4c
	unsigned _consecutiveZeroBytesNeeded;	// 84 = 0x54
	unsigned long long _numSamplesTakenToComputeTime;	// 88 = 0x58
}
@property(readonly, retain) NSArray *selectableAudioTracks;	// G=0x3391f80d; converted property
@property(readonly, retain) NSArray *subtitleTracks;	// G=0x3391f81d; converted property
- (id)init;	// 0x339201b5
- (BOOL)_assetIsLiveStreaming:(id)streaming;	// 0x3391fb41
- (void)_cacheNotification:(BOOL)notification;	// 0x3391f945
- (long long)_clearSpaceInCache:(id)cache smallestFirst:(BOOL)first upTo:(unsigned long long)to;	// 0x3392119d
- (void)_handleDiskSpaceRequest:(id)request;	// 0x33921651
- (void)_networkStatusChanged:(id)changed;	// 0x3391f8e5
- (id)_otherCache;	// 0x3391fb89
- (void)_postItemStateChangedNotification:(ATVMediaItemRef)notification;	// 0x3391f855
- (void)_progressSampleTimerHandler:(id)handler;	// 0x33920e91
- (id)_rentalCache;	// 0x3391fccd
- (BOOL)_verifyDirectoryExists:(id)exists;	// 0x339217d1
- (BRTimeRange)bufferedRange;	// 0x33921939
- (id)cacheInfoForAsset:(id)asset;	// 0x3391feb9
- (id)currentPlayer;	// 0x3391f7ed
- (id)currentPlayerItem;	// 0x3391f7fd
- (id)currentPlayerLayer;	// 0x3391f7dd
- (void)dealloc;	// 0x3392007d
- (double)duration;	// 0x339218c9
- (double)elapsedTime;	// 0x3392186d
- (void)evictAsset:(id)asset;	// 0x3392062d
- (BOOL)isItemLoading:(ATVMediaItemRef)loading;	// 0x33920e49
- (BOOL)isItemReadyToPlay:(ATVMediaItemRef)play;	// 0x33920db5
- (int)playerState;	// 0x3391f82d
- (void)saveCacheKey:(id)key forAsset:(id)asset;	// 0x3391fe6d
- (double)secondsUntilItemWillBeReadyToPlay:(ATVMediaItemRef)secondsUntilItem;	// 0x3392031d
// converted property getter: - (id)selectableAudioTracks;	// 0x3391f80d
- (void)setDelegate:(id)delegate;	// 0x3391f7cd
- (void)setDownloadKeyCookieForAsset:(id)asset;	// 0x33921345
- (void)startCachingItem:(ATVMediaItemRef)item;	// 0x3391fe4d
- (void)startCachingItem:(ATVMediaItemRef)item withElapsedTime:(double)elapsedTime;	// 0x33920721
- (void)stopCaching;	// 0x339203d9
// converted property getter: - (id)subtitleTracks;	// 0x3391f81d
@end

