/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSValueTransformer.h> // Unknown library


__attribute__((visibility("hidden")))
@interface ATVVersionStringTransformer : NSValueTransformer {
}
+ (BOOL)allowsReverseTransformation;	// 0x3390b20d
+ (Class)transformedValueClass;	// 0x3390b3f9
- (id)reverseTransformedValue:(id)value;	// 0x3390b2a9
- (id)transformedValue:(id)value;	// 0x3390b2dd
@end

