/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "ATVStoreFavorite.h"

@class NSString;

__attribute__((visibility("hidden")))
@interface ATVWishListFavorite : ATVStoreFavorite {
@private
	NSString *_adamID;	// 64 = 0x40
}
- (id)initWithDictionary:(id)dictionary;	// 0x338ab461
- (BOOL)_setupWithCatalogItem:(id)catalogItem;	// 0x338ab125
- (void)dealloc;	// 0x338ab419
- (void)encodeWithDictionary:(id)dictionary;	// 0x338ab3c5
- (id)itemID;	// 0x338ab111
- (void)remove;	// 0x338ab2fd
- (BOOL)removeUponAcquisition;	// 0x338ab121
- (void)save;	// 0x338ab361
@end

