/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface AudioData : NSObject {
@private
	int flags;	// 4 = 0x4
	int pid;	// 8 = 0x8
	int audioFormat;	// 12 = 0xc
	int channelCount;	// 16 = 0x10
	int sampleCount;	// 20 = 0x14
	NSString *audioLanguageCode;	// 24 = 0x18
}
- (id)initWithBuffer:(id)buffer;	// 0x3392e838
- (void)dealloc;	// 0x3392e7d8
- (int)getAudioFormat;	// 0x3392e788
- (id)getAudioLanguageCode;	// 0x3392e7c4
- (int)getChannelCount;	// 0x3392e79c
- (int)getFlags;	// 0x3392e760
- (int)getPID;	// 0x3392e774
- (int)getSampleCount;	// 0x3392e7b0
@end

