/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Base64 : NSObject {
}
+ (id)decode:(id)decode;	// 0x3394522c
+ (id)decode:(const char *)decode length:(int)length;	// 0x33945298
+ (id)encode:(id)encode;	// 0x33945408
+ (id)encode:(const char *)encode length:(int)length;	// 0x33945470
+ (void)initialize;	// 0x339455e4
@end

