/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRAccountType.h> // Unknown library


@interface BRAccountType (ATVAdditions)
+ (id)airTunes;	// 0x338c765d
+ (id)dotMac;	// 0x338c730d
+ (id)dotMacSecondary;	// 0x338c7239
+ (id)flickr;	// 0x338c73e1
+ (id)homeShare;	// 0x338c74b5
+ (id)iTunes;	// 0x338c7589
+ (id)sedona;	// 0x338c7091
+ (id)youTube;	// 0x338c7165
@end

