/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRDownloadManager.h> // Unknown library


@interface BRDownloadManager (BRDownloadManagerATVExtensions)
- (id)downloadsWithQualifiedState:(int)qualifiedState;	// 0x338a6fcd
- (void)pauseCurrentDownloads;	// 0x338a6f7d
@end

