/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRMerchant.h> // Unknown library


@interface BRMerchant (ATVMerchant)
+ (id)itms;	// 0x33911ac5
+ (id)sedona;	// 0x33911aa5
- (Class)catalogAgent;	// 0x33911a55
@end

