/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <BRThemeInfo.h> // Unknown library


@interface BRThemeInfo (ATVImageCaching)
- (id)_atvImageForFile:(id)file ofType:(id)type;	// 0x338a11bd
- (id)_cachedATVImageForFile:(id)file ofType:(id)type;	// 0x338a0835
@end

@interface BRThemeInfo (ATVExtensions)
- (id)appleTVIconGlow;	// 0x338a0cf5
- (id)ccBadge;	// 0x338a0c89
- (id)checkForPurchasesTextAttributes;	// 0x338a0d5d
- (id)dolbyDigitalBadge;	// 0x338a0cad
- (id)downloadMenuItemPrimaryTextAttributes;	// 0x338a0d3d
- (id)downloadMenuItemSecondaryTextAttributes;	// 0x338a0d7d
- (id)hdPosterBadge;	// 0x338a0cd1
- (float)heightForDownloadItemRow;	// 0x338a0dbd
- (id)loadMoreRectangleImage;	// 0x338a0c41
- (id)loadMoreSquareImage;	// 0x338a0c65
- (id)localContentProviderImage;	// 0x338a0d19
- (id)moreActionHighlightedImage;	// 0x338a0a91
- (id)moreActionImage;	// 0x338a0ab5
- (id)musicFeaturedPlaceholderImage;	// 0x338a0b21
- (id)musicPlaceholderImage;	// 0x338a0bb1
- (id)pauseButtonImage;	// 0x338a1089
- (id)podcastFeaturedPlaceholderImage;	// 0x338a0afd
- (id)podcastPlaceholderImage;	// 0x338a0b8d
- (id)progressBarActive_Endcap;	// 0x338a0f85
- (id)progressBarComponents_ActiveEmpty;	// 0x338a0fa1
- (id)progressBarComponents_ActiveFilled;	// 0x338a1015
- (id)progressBarComponents_PausedEmpty;	// 0x338a0e9d
- (id)progressBarComponents_PausedFilled;	// 0x338a0f11
- (id)progressBarComponents_Waiting;	// 0x338a0e0d
- (id)progressBarPaused_Endcap;	// 0x338a0e81
- (int)shelfColumnCountForCollectionType:(id)collectionType featured:(BOOL)featured related:(BOOL)related moreInfoContent:(BOOL)content showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles;	// 0x338a089d
- (float)shelfCoverflowMarginForCollectionType:(id)collectionType featured:(BOOL)featured related:(BOOL)related showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles;	// 0x338a07fd
- (float)shelfHeightForCollectionType:(id)collectionType featured:(BOOL)featured related:(BOOL)related showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles;	// 0x338a10a5
- (float)shelfHorizontalGapForCollectionType:(id)collectionType featured:(BOOL)featured related:(BOOL)related showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles;	// 0x338a09e5
- (float)shelfReflectionAmountForCollectionType:(id)collectionType featured:(BOOL)featured showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles related:(BOOL)related;	// 0x338a0915
- (BOOL)shelfScrollabilityForCollectionType:(id)collectionType featured:(BOOL)featured showTitleAndSubtitle:(BOOL)subtitle showAllTitles:(BOOL)titles;	// 0x338a0829
- (id)storeRentalFeaturedPlaceholderImage;	// 0x338a0b69
- (float)storeRentalIconHorizontalOffset;	// 0x338a07f1
- (float)storeRentalIconKerningFactor;	// 0x338a07f5
- (id)storeRentalPlaceholderImage;	// 0x338a0c1d
- (id)storeRentalPlaceholderImageLarge;	// 0x338a0bf9
- (id)tvShowFeaturedPlaceholderImage;	// 0x338a0b45
- (id)tvShowPlaceholderImage;	// 0x338a0bd5
- (id)tvShowPlaceholderImageForMenuItem;	// 0x338a0ad9
- (id)wishListActionHighlightedImage;	// 0x338a0a49
- (id)wishListActionImage;	// 0x338a0a6d
@end

