/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Buffer : NSObject {
@private
	char *buf;	// 4 = 0x4
	int index;	// 8 = 0x8
	int bitMask;	// 12 = 0xc
	int length;	// 16 = 0x10
}
- (id)initWithData:(char *)data length:(unsigned)length;	// 0x3392f174
- (id)initWithData:(char *)data offset:(unsigned)offset length:(unsigned)length;	// 0x3392f1a0
- (int)getBits:(unsigned)bits;	// 0x3392ed30
- (int)getByte;	// 0x3392ee28
- (id)getBytes:(unsigned)bytes;	// 0x3392eedc
- (int)getIndex;	// 0x3392eccc
- (int)getInt;	// 0x3392ee70
- (int)getLength;	// 0x3392ecb8
- (long long)getLong;	// 0x3392f114
- (id)getNullTerminatedString;	// 0x3392ef7c
- (int)getShort;	// 0x3392edd0
- (id)getString:(unsigned)string;	// 0x3392f064
- (char *)getUnreadData;	// 0x3392ed08
- (int)getUnreadLength;	// 0x3392ece0
@end

