/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NflxhlsAuthenticationPrimer;

__attribute__((visibility("hidden")))
@interface HTTPServer : NSObject {
@private
	NflxhlsAuthenticationPrimer *primer;	// 4 = 0x4
	BOOL serverRunning;	// 8 = 0x8
	BOOL serverFinihed;	// 9 = 0x9
}
+ (void)cleanUp;	// 0x33929618
+ (id)instance;	// 0x33929668
- (id)init;	// 0x33929724
- (void)dealloc;	// 0x339296bc
- (void)debugHTTP:(BOOL)http;	// 0x33929a7c
- (void)httpServerMain:(id)main;	// 0x33929aac
- (void)start;	// 0x339297a4
- (void)stop;	// 0x339299ec
@end

