/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface LogCollectorWrapper : NSObject {
}
+ (void)cleanUp;	// 0x33a3b730
+ (id)instance;	// 0x33a3c7a0
- (id)init;	// 0x33a3b7cc
- (void)cdnSelected:(long long)selected selcdnbw:(long long)selcdnbw;	// 0x33a3bfbc
- (void)cleanUp;	// 0x33a3b708
- (void)dealloc;	// 0x33a3b790
- (void)endPlaybackSession:(id)session;	// 0x33a3c3e8
- (void)loadNewPlaylistFile:(long long)file vdlid:(long long)vdlid;	// 0x33a3c0a4
- (void)logErrorMessageOnce:(id)once;	// 0x33a3b9d0
- (void)networkSelection:(const char *)selection;	// 0x33a3bee8
- (void)playbackDidPause;	// 0x33a3bc2c
- (void)playbackDidSeeking;	// 0x33a3bb60
- (void)playbackDisrupted;	// 0x33a3be1c
- (void)playlistGenerated:(id)generated;	// 0x33a3b8dc
- (void)sendErrorMessage:(id)message;	// 0x33a3c644
- (void)startBuffering;	// 0x33a3c578
- (void)startOrResumePlayCancelled;	// 0x33a3c18c
- (void)startOrResumePlayFailed:(id)failed;	// 0x33a3c258
- (void)startOrResumePlaybackSucceded:(long long)succeded nccplt:(long long)nccplt nccpmdt:(long long)nccpmdt nccpudt:(long long)nccpudt cdnt:(long long)cdnt plt:(long long)plt;	// 0x33a3bcf8
- (void)startPlaybackSession:(long long)session;	// 0x33a3b808
- (void)startUp;	// 0x33a3b6f0
@end

