/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NetflixTopHeader : NSObject {
@private
	int startOffset;	// 4 = 0x4
}
- (id)initWithData:(char *)data length:(unsigned)length;	// 0x3392df34
- (void)dealloc;	// 0x3392def8
- (int)getStartOffset;	// 0x3392dee4
@end

