/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSURLProtocol.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NfhlsProtocol : NSURLProtocol {
}
+ (BOOL)canInitWithRequest:(id)request;	// 0x33939bd8
+ (id)canonicalRequestForRequest:(id)request;	// 0x33939bb8
+ (void)registerSpecialProtocol;	// 0x33939cbc
+ (void)setDebug:(BOOL)debug;	// 0x33939bc0
+ (id)specialProtocolScheme;	// 0x33939b98
+ (id)specialProtocolVarsKey;	// 0x33939ba8
+ (void)unregisterSpecialProtocol;	// 0x33939c4c
- (void)startLoading;	// 0x33939e1c
- (void)stopLoading;	// 0x33939bd4
@end

