/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface Nflxhls : NSObject {
}
@property(retain) id userId;	// G=0x3393a320; S=0x3393a334; converted property
+ (id)instance;	// 0x3394021c
- (id)init;	// 0x339408fc
- (void)_logout;	// 0x3393b788
- (void)appLogError:(id)error withInfoMessage:(id)infoMessage withException:(id)exception withStacktrace:(id)stacktrace;	// 0x3393a4d4
- (BOOL)configure:(id)configure forView:(id)view;	// 0x3393e2e0
- (id)cookieExpiresForNameKey:(id)nameKey;	// 0x3393d7f4
- (id)cookieValueForNameKey:(id)nameKey;	// 0x3393d8ec
- (id)createURLRequest:(id)request;	// 0x3393ba98
- (void)dealloc;	// 0x33940694
- (void)debugHttp:(BOOL)http;	// 0x3393a494
- (void)debugNfhlsProtocol:(BOOL)protocol;	// 0x3393a468
- (void)deleteConfig;	// 0x3393ffa0
- (void)deleteNetflixCookies;	// 0x3394174c
- (void)deleteNflxId;	// 0x33940120
- (void)deleteUserExistence;	// 0x3393d540
- (void)didEnterBackground;	// 0x3393dad8
- (id)encodedURLParameterString:(id)string;	// 0x33941864
- (id)esn;	// 0x3393f15c
- (char *)esnPrefix;	// 0x3393f194
- (void)generateNewUUIDStartTime;	// 0x3393f66c
- (id)genericFeedURL;	// 0x3393f1cc
- (id)getAPIRequestContextParameters;	// 0x3393f2b8
- (id)getCountry;	// 0x3393a400
- (id)getNCTS;	// 0x3393a348
- (int)getTarget;	// 0x3393a454
- (id)getTestNCCPDataURL;	// 0x3393a384
- (id)getTestNCCPIdentityURL;	// 0x3393a398
- (id)getTestNCCPLoggingURL;	// 0x3393a3ac
- (id)getUUID;	// 0x3393f4dc
- (BOOL)isNato;	// 0x33940464
- (BOOL)isUsingStagingNCCP;	// 0x3393a3c0
- (BOOL)isUsingTestEnv;	// 0x3393a35c
- (BOOL)login:(id)login password:(id)password error:(id *)error;	// 0x3393b488
- (BOOL)loginRequired:(id *)required;	// 0x3393b890
- (void)logout;	// 0x3393b838
- (void)notifyErrorMessage:(id)message;	// 0x3393a5c8
- (void)notifyNetworkStatus:(id)status;	// 0x3393a62c
- (BOOL)notifyPlayerEnd:(double)end reason:(id)reason error:(id *)error;	// 0x3393acec
- (void)notifyPlayerLoadState:(double)state playing:(BOOL)playing;	// 0x3393ac40
- (void)notifyPlayerPause:(double)pause;	// 0x3393aa84
- (void)notifyPlayerResume:(double)resume;	// 0x3393abac
- (void)notifyPlayerSeek:(double)seek;	// 0x3393a9f0
- (BOOL)notifyPlayerStart:(double)start reason:(id)reason error:(id *)error;	// 0x3393a68c
- (BOOL)notifyPlayerStop:(double)stop reason:(id)reason error:(id *)error;	// 0x3393a858
- (void)notifyProgress:(double)progress;	// 0x3393ab18
- (id)oAuthSignRequest:(id)request params:(id)params withHTTPMethod:(id)httpmethod;	// 0x3394239c
- (BOOL)preparePlayList:(id)list returningPlayUrl:(id *)url audioEncoding:(int *)encoding position:(double *)position duration:(double *)duration error:(id *)error;	// 0x3393ae84
- (void)registerNfhlsProtocol;	// 0x3393db9c
- (void)reportAndAssignAuthorizationToken:(id)token;	// 0x3393c5c0
- (void)requestAccessToken:(id)token didFailWithError:(id)error;	// 0x3393bbbc
- (void)requestAccessToken:(id)token didFinishWithData:(id)data;	// 0x3393bcc8
- (void)requestAccessTokenWorker;	// 0x3393c1e0
- (void)requestAuthorizationToken:(id)token didFailWithError:(id)error;	// 0x3393c608
- (void)requestAuthorizationToken:(id)token didFinishWithData:(id)data;	// 0x3393c354
- (void)requestAuthorizationTokenWorker;	// 0x3393c714
- (void)requestNetflixLogin;	// 0x33940f80
- (BOOL)restoreNeededConfigCookies:(BOOL)cookies;	// 0x3393c86c
- (BOOL)restoreNeededLoginCookies;	// 0x3393ce94
- (BOOL)saveNeededConfigCookies:(id)cookies;	// 0x3393cad0
- (BOOL)saveNeededLoginCookies:(id)cookies;	// 0x3393d240
- (void)setCred:(id)cred idtype:(id)idtype secid:(id)secid secidtype:(id)secidtype;	// 0x3393fdb8
- (BOOL)setCredentialFromCookie;	// 0x3393fb14
- (BOOL)setCredentialUsingCookie;	// 0x3393febc
- (void)setDeviceUserAgent:(id)agent;	// 0x3393f8d4
- (void)setExpiresThreshold:(double)threshold;	// 0x3393a414
- (void)setKeyUseCustom:(BOOL)custom;	// 0x3393f9e0
- (void)setPlayListUseCustom:(BOOL)custom;	// 0x3393fa20
- (void)setUseHttp:(BOOL)http;	// 0x3393fa70
// converted property setter: - (void)setUserId:(id)anId;	// 0x3393a334
- (void)setm3u8bandwithSource:(int)source;	// 0x3393f960
- (void)setupFujiTarget:(int)target;	// 0x33940498
- (void)showCookies;	// 0x3393d690
- (void)startWithParams:(id)params;	// 0x33940b68
- (void)startWithParams:(id)params withSettings:(id)settings;	// 0x3393dbc4
- (void)stop;	// 0x33940270
- (BOOL)supportDD5_1;	// 0x3393a370
- (id)uibootURL;	// 0x3393a3d4
- (void)unregisterNfhlsProtocol;	// 0x3393db74
- (void)useHighDef:(BOOL)def;	// 0x3393f9a0
- (void)useStagingNCCP:(BOOL)nccp;	// 0x3393f744
- (void)useTestEnv:(BOOL)env;	// 0x3393f80c
// converted property getter: - (id)userId;	// 0x3393a320
- (id)version;	// 0x3393feec
- (void)webServiceEnableBackgroundQueuing:(BOOL)queuing;	// 0x3393a588
- (long long)webServiceGetLogTimeInMS;	// 0x3393a534
- (void)webServiceLogActivity:(id)activity forAction:(id)action onView:(id)view withStartTimeInMS:(long long)ms withResponseTimeInMS:(long long)ms5;	// 0x33942054
- (void)webServiceLogError:(id)error withNSError:(id)nserror withInfoMessage:(id)infoMessage forAction:(id)action onView:(id)view;	// 0x33941c3c
- (void)webServiceLogError:(id)error withSubCodeError:(int)subCodeError withInfoMessage:(id)infoMessage forAction:(id)action onView:(id)view;	// 0x339418bc
- (void)willEnterForeground;	// 0x3393da30
@end

