/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NflxhlsStrings : NSObject {
}
+ (void)cleanUp;	// 0x339472b8
+ (id)instance;	// 0x339472f4
- (id)init;	// 0x3394727c
- (void)dealloc;	// 0x33947240
- (id)getString:(int)string;	// 0x3394722c
@end

