/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface NflxhlsAuthenticationPrimer : NSObject {
@private
	BOOL myPassword[100];	// 4 = 0x4
}
- (id)init;	// 0x339456d0
- (void)connection:(id)connection didFailWithError:(id)error;	// 0x339458a0
- (void)connection:(id)connection didReceiveAuthenticationChallenge:(id)challenge;	// 0x33945918
- (void)connection:(id)connection didReceiveData:(id)data;	// 0x3394567c
- (void)connection:(id)connection didReceiveResponse:(id)response;	// 0x339458f8
- (void)connectionDidFinishLoading:(id)connection;	// 0x339458d8
- (void)dealloc;	// 0x33945694
- (char *)getGeneratedPassword;	// 0x33945680
- (void)prime;	// 0x339457cc
- (void)primeAuthorization;	// 0x339457e8
@end

