/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSString.h> // Unknown library


@interface NSString (NSString_SBJSON)
- (id)JSONFragmentValue;	// 0x33936280
- (id)JSONValue;	// 0x339361f0
@end

@interface NSString (AOSStringAdditions)
- (id)stringByURLQuoting;	// 0x33b3f101
- (id)stringByURLQuotingWithCharactersToEscape:(id)escape;	// 0x33b3f425
@end

