/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSValueTransformer.h> // Unknown library


@interface NSValueTransformer (ATVValueTransformerAdditions)
+ (id)dateToMonthDayYearString;	// 0x3390bd4d
+ (id)releaseDateAsInTheatersDateString;	// 0x3390bf79
+ (id)releaseDateAsOriginalAirDateString;	// 0x3390bf3d
+ (id)releaseDateAsReleasedDateString;	// 0x3390bfb5
+ (id)releaseDateAsYearReleasedString;	// 0x3390c031
+ (id)tomatoMeter;	// 0x3390bc19
+ (id)tvEpisodeTitleToNumberedTitle;	// 0x3390bc95
+ (id)userRatingAndNumReviewsToControl;	// 0x3390bdc9
+ (id)userRatingToImageControl;	// 0x3390bec1
+ (id)userReviewsNumberToTextControl;	// 0x3390be45
+ (id)versionStringToVersionComponentsArray;	// 0x3390bd11
@end

@interface NSValueTransformer (ATVSedonaValueTransformers)
+ (id)sedonaUserRatingAndNumReviewsToControl;	// 0x3391ee89
+ (id)sedonaUserRatingToImageControl;	// 0x3391eef5
@end

