/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface OAConsumer : NSObject {
@private
	NSString *key;	// 4 = 0x4
	NSString *secret;	// 8 = 0x8
	NSString *callback;	// 12 = 0xc
	NSString *verifier;	// 16 = 0x10
}
@property(copy) NSString *callback;	// G=0x3394399c; S=0x33943a24; @synthesize
@property(copy) NSString *key;	// G=0x3394395c; S=0x339439bc; @synthesize
@property(copy) NSString *secret;	// G=0x3394397c; S=0x339439f0; @synthesize
+ (id)consumerWithKey:(id)key secret:(id)secret callback:(id)callback;	// 0x339437dc
- (id)initWithKey:(id)key secret:(id)secret callback:(id)callback;	// 0x33943844
// declared property getter: - (id)callback;	// 0x3394399c
- (void)dealloc;	// 0x339438d8
// declared property getter: - (id)key;	// 0x3394395c
// declared property getter: - (id)secret;	// 0x3394397c
// declared property setter: - (void)setCallback:(id)callback;	// 0x33943a24
// declared property setter: - (void)setKey:(id)key;	// 0x339439bc
// declared property setter: - (void)setSecret:(id)secret;	// 0x339439f0
@end

