/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSMutableURLRequest.h> // Unknown library

@class OAConsumer, OAToken, NSString;

__attribute__((visibility("hidden")))
@interface OAMutableURLRequest : NSMutableURLRequest {
@private
	OAConsumer *consumer;	// 8 = 0x8
	OAToken *token;	// 12 = 0xc
	NSString *realm;	// 16 = 0x10
	NSString *verifier;	// 20 = 0x14
	NSString *signature;	// 24 = 0x18
	NSString *nonce;	// 28 = 0x1c
	NSString *timestamp;	// 32 = 0x20
}
@property(retain) OAConsumer *consumer;	// G=0x33943588; S=0x33943668; @synthesize
@property(copy) NSString *nonce;	// G=0x33943628; S=0x33943774; @synthesize
@property(copy) NSString *realm;	// G=0x339435c8; S=0x339436d8; @synthesize
@property(copy) NSString *signature;	// G=0x33943608; S=0x33943740; @synthesize
@property(copy) NSString *timestamp;	// G=0x33943648; S=0x339437a8; @synthesize
@property(retain) OAToken *token;	// G=0x339435a8; S=0x339436a0; @synthesize
@property(copy) NSString *verifier;	// G=0x339435e8; S=0x3394370c; @synthesize
+ (id)requestWithURL:(id)url consumer:(id)consumer token:(id)token realm:(id)realm verifier:(id)verifier;	// 0x33942db0
- (id)initWithURL:(id)url consumer:(id)consumer token:(id)token realm:(id)realm verifier:(id)verifier;	// 0x33942ef4
// declared property getter: - (id)consumer;	// 0x33943588
- (void)dealloc;	// 0x33942e28
// declared property getter: - (id)nonce;	// 0x33943628
- (void)prepare;	// 0x3394296c
// declared property getter: - (id)realm;	// 0x339435c8
// declared property setter: - (void)setConsumer:(id)consumer;	// 0x33943668
// declared property setter: - (void)setNonce:(id)nonce;	// 0x33943774
// declared property setter: - (void)setRealm:(id)realm;	// 0x339436d8
// declared property setter: - (void)setSignature:(id)signature;	// 0x33943740
// declared property setter: - (void)setTimestamp:(id)timestamp;	// 0x339437a8
// declared property setter: - (void)setToken:(id)token;	// 0x339436a0
// declared property setter: - (void)setVerifier:(id)verifier;	// 0x3394370c
// declared property getter: - (id)signature;	// 0x33943608
- (id)signatureBaseString;	// 0x33943100
// declared property getter: - (id)timestamp;	// 0x33943648
// declared property getter: - (id)token;	// 0x339435a8
// declared property getter: - (id)verifier;	// 0x339435e8
@end

