/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class OAMutableURLRequest, NSURLResponse;

__attribute__((visibility("hidden")))
@interface OAServiceTicket : NSObject {
@private
	OAMutableURLRequest *request;	// 4 = 0x4
	NSURLResponse *response;	// 8 = 0x8
	BOOL succeeded;	// 12 = 0xc
	long long startRequestTime;	// 16 = 0x10
	long long endRequestTime;	// 24 = 0x18
}
@property(assign) long long endRequestTime;	// G=0x33944320; S=0x339442e0; @synthesize
@property(retain) OAMutableURLRequest *request;	// G=0x33944360; S=0x339443a0; @synthesize
@property(retain) NSURLResponse *response;	// G=0x33944380; S=0x339443d8; @synthesize
@property(assign) long long startRequestTime;	// G=0x339442a0; S=0x33944260; @synthesize
@property(assign) BOOL succeeded;	// G=0x33944020; S=0x33944034; @synthesize
+ (id)ticketWithRequest:(id)request response:(id)response succeeded:(BOOL)succeeded withRequestStartTime:(long long)requestStartTime withRequestEndTime:(long long)requestEndTime;	// 0x33944048
- (id)initWithRequest:(id)request response:(id)response succeeded:(BOOL)succeeded withRequestStartTime:(long long)requestStartTime withRequestEndTime:(long long)requestEndTime;	// 0x339440cc
- (void)dealloc;	// 0x339441a4
// declared property getter: - (long long)endRequestTime;	// 0x33944320
// declared property getter: - (id)request;	// 0x33944360
// declared property getter: - (id)response;	// 0x33944380
// declared property setter: - (void)setEndRequestTime:(long long)time;	// 0x339442e0
// declared property setter: - (void)setRequest:(id)request;	// 0x339443a0
// declared property setter: - (void)setResponse:(id)response;	// 0x339443d8
// declared property setter: - (void)setStartRequestTime:(long long)time;	// 0x33944260
// declared property setter: - (void)setSucceeded:(BOOL)succeeded;	// 0x33944034
// declared property getter: - (long long)startRequestTime;	// 0x339442a0
// declared property getter: - (BOOL)succeeded;	// 0x33944020
@end

