/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSDictionary, NSString;

__attribute__((visibility("hidden")))
@interface OAToken : NSObject {
@private
	NSString *key;	// 4 = 0x4
	NSString *secret;	// 8 = 0x8
	NSDictionary *fields;	// 12 = 0xc
}
@property(retain) NSDictionary *fields;	// G=0x33943f60; S=0x33943fe8; @synthesize
@property(copy) NSString *key;	// G=0x33943f20; S=0x33943f80; @synthesize
@property(copy) NSString *secret;	// G=0x33943f40; S=0x33943fb4; @synthesize
+ (id)tokenWithHTTPResponseBody:(id)httpresponseBody;	// 0x33943a58
+ (id)tokenWithKey:(id)key secret:(id)secret;	// 0x33943aa8
- (id)init;	// 0x33943b7c
- (id)initWithHTTPResponseBody:(id)httpresponseBody;	// 0x33943c80
- (id)initWithKey:(id)key secret:(id)secret;	// 0x33943b00
- (void)dealloc;	// 0x33943bfc
// declared property getter: - (id)fields;	// 0x33943f60
// declared property getter: - (id)key;	// 0x33943f20
// declared property getter: - (id)secret;	// 0x33943f40
// declared property setter: - (void)setFields:(id)fields;	// 0x33943fe8
// declared property setter: - (void)setKey:(id)key;	// 0x33943f80
// declared property setter: - (void)setSecret:(id)secret;	// 0x33943fb4
@end

