/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PlaydataController : NSObject {
}
- (id)init;	// 0x33a3aac0
- (void)dealloc;	// 0x33a3aa84
- (void)downloadableDidChange:(unsigned)downloadable playbackPosition:(double)position;	// 0x33a3ab64
- (void)playbackDidEnd:(double)playback;	// 0x33a3b52c
- (void)playbackDidPause:(double)playback;	// 0x33a3b3e4
- (void)playbackDidResume:(double)playback;	// 0x33a3b2a4
- (void)playbackDidStart:(unsigned)playback position:(double)position;	// 0x33a3ae5c
- (void)playbackUpdateProgress:(double)progress;	// 0x33a3b178
- (void)updatePersistor:(double)persistor;	// 0x33a3abc0
@end

