/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class AppNccpHandlerDelegate, NSLock, NSConditionLock, NSDate, NSString, PlaydataController, NSMutableDictionary, NSDictionary;

__attribute__((visibility("hidden")))
@interface PlaybackController : NSObject {
@private
	AppNccpHandlerDelegate *nccpDelegate;	// 4 = 0x4
	PlaydataController *playdataController;	// 8 = 0x8
	BOOL playListGenError;	// 12 = 0xc
	NSLock *playListLock;	// 16 = 0x10
	NSConditionLock *theConditionLock;	// 20 = 0x14
	NSMutableDictionary *playListThreads;	// 24 = 0x18
	NSMutableDictionary *playListInprogress;	// 28 = 0x1c
	NSMutableDictionary *plbwInprogress;	// 32 = 0x20
	NSDictionary *playListDict;	// 36 = 0x24
	NSDictionary *playListBandwidthDict;	// 40 = 0x28
	NSString *playListDictReqPath;	// 44 = 0x2c
	NSDate *playListDictExpiration;	// 48 = 0x30
	int playbackState;	// 52 = 0x34
	double playbackPosition;	// 56 = 0x38
	int playListGenTimeElapsed;	// 64 = 0x40
	long movieID;	// 68 = 0x44
	long episodeID;	// 72 = 0x48
	BOOL isUsing3G;	// 76 = 0x4c
	BOOL isUsingHighDef;	// 77 = 0x4d
	BOOL keyUseCustom;	// 78 = 0x4e
	BOOL playListUseCustom;	// 79 = 0x4f
	BOOL firstNccpCall;	// 80 = 0x50
	double lastPingTime;	// 84 = 0x54
	int m3u8BandwidthSetting;	// 92 = 0x5c
}
+ (void)cleanUp;	// 0x33933934
+ (id)instance;	// 0x33933968
- (id)init;	// 0x33933b18
- (void)changeState:(int)state;	// 0x33931c0c
- (void)closeActiveSession;	// 0x339334ec
- (void)dealloc;	// 0x339339bc
- (void)doGeneratePlayListTh:(id)th;	// 0x3393240c
- (BOOL)ensureInitializedWithID:(id)anId idvalue:(id)idvalue secretkey:(id)secretkey secretvalue:(id)secretvalue ncts:(id)ncts;	// 0x339335a8
- (int)getMovieDuration;	// 0x33933cb4
- (int)getPlayListGenTE;	// 0x33931adc
- (void)loadState:(double)state playing:(BOOL)playing;	// 0x33932c08
- (void)logout;	// 0x339334d0
- (void)playBackEnd:(double)end reason:(id)reason;	// 0x33932db8
- (void)playBackPause:(double)pause;	// 0x339331a8
- (void)playBackResume:(double)resume;	// 0x33932f18
- (void)playBackSeek:(double)seek;	// 0x339330fc
- (void)playBackStart:(double)start reason:(id)reason;	// 0x33933294
- (void)playBackStop:(double)stop reason:(id)reason;	// 0x33932ea8
- (void)playBackUpdate:(double)update;	// 0x33933254
- (id)playListSendData:(id)data;	// 0x339329e0
- (BOOL)preparePlayList:(id)list withAudioEncoding:(int *)audioEncoding;	// 0x33934d3c
- (void)setKeyUseCustom:(BOOL)custom;	// 0x33931b04
- (void)setPlayListUseCustom:(BOOL)custom;	// 0x33931af0
- (void)setPlaylists:(id)playlists bandwidth:(id)bandwidth reqpath:(id)reqpath expiration:(unsigned long long)expiration;	// 0x33933804
- (void)setPosition:(int)position;	// 0x33931b44
- (void)setUsing3g:(BOOL)g;	// 0x33931b18
- (void)setUsingHighDef:(BOOL)def;	// 0x33931b1c
- (void)setm3u8bandwithSource:(int)source;	// 0x33931b30
- (id)stringWithState:(int)state;	// 0x33931b64
- (void)triggerGeneratePlayList:(id)list url:(id)url getKey:(BOOL)key keyType:(BOOL)type;	// 0x33932208
- (BOOL)triggerPlay:(int *)play ncts:(id)ncts idkey:(id)idkey idvalue:(id)idvalue secretkey:(id)secretkey secretvalue:(id)secretvalue movieid:(long)movieid trackid:(long)trackid episodeid:(long)episodeid;	// 0x33933d70
@end

