/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library


__attribute__((visibility("hidden")))
@interface PlayReady : NSObject {
}
+ (id)PlayReadyErrorToString:(int)string;	// 0x33928d80
+ (void)cleanup;	// 0x33929598
+ (id)getKey:(int *)key;	// 0x33929508
+ (void)setUniqueId:(char *)anId :(unsigned long)arg2;	// 0x33929334
+ (void)startWithId:(const char *)anId;	// 0x3392934c
+ (void)triggerKeyRetrieval:(id)retrieval :(id)arg2 :(int)arg3;	// 0x339293a4
- (id)init;	// 0x33928dac
- (int)decryptData:(char *)data :(unsigned long)arg2;	// 0x33929274
- (void)doGetKey:(id)key;	// 0x33928e04
- (int)generateChallenge:(const char *)challenge :(unsigned long)arg2 :(char *)arg3 :(unsigned long *)arg4;	// 0x33929224
- (int)getPRKey:(char *)key :(unsigned long)arg2;	// 0x33929244
- (int)isInitialized;	// 0x33929324
- (int)sendRequest:(const char *)request :(unsigned long)arg2 :(char *)arg3 :(unsigned long *)arg4;	// 0x33929138
- (int)setIv:(char *)iv :(unsigned long)arg2;	// 0x3392925c
- (void)unInitialize;	// 0x3392928c
@end

