/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString, NSData;

__attribute__((visibility("hidden")))
@interface PlayListGenerator : NSObject {
@private
	NSString *playlist;	// 4 = 0x4
	NSData *data;	// 8 = 0x8
	int streamduration;	// 12 = 0xc
	int avgBandwidth;	// 16 = 0x10
	int peakBandwidth;	// 20 = 0x14
}
- (id)initWithName:(id)name getKey:(BOOL)key keyType:(BOOL)type;	// 0x3392f560
- (void)dealloc;	// 0x33930330
- (int)getAverageBw;	// 0x3392f538
- (int)getDuration;	// 0x3392f54c
- (int)getPeakBw;	// 0x3392f524
- (id)getPlayList;	// 0x3392f510
@end

