/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableArray, NSArray;

__attribute__((visibility("hidden")))
@interface SBJsonBase : NSObject {
@private
	NSMutableArray *errorTrace;	// 4 = 0x4
	unsigned depth;	// 8 = 0x8
	unsigned maxDepth;	// 12 = 0xc
}
@property(readonly, copy) NSArray *errorTrace;	// G=0x33936c50; @synthesize
@property(assign) unsigned maxDepth;	// G=0x33936958; S=0x3393696c; @synthesize
- (id)init;	// 0x33936bf4
- (void)addErrorWithCode:(unsigned)code description:(id)description;	// 0x339369f8
- (void)clearErrorTrace;	// 0x33936980
- (void)dealloc;	// 0x33936b94
// declared property getter: - (id)errorTrace;	// 0x33936c50
// declared property getter: - (unsigned)maxDepth;	// 0x33936958
// declared property setter: - (void)setMaxDepth:(unsigned)depth;	// 0x3393696c
@end

