/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import "SBJsonWriter.h"
#import "SBJsonBase.h"


@protocol SBJsonWriter
@property(assign) BOOL humanReadable;
@property(assign) BOOL sortKeys;
// declared property getter: - (BOOL)humanReadable;
// declared property setter: - (void)setHumanReadable:(BOOL)readable;
// declared property setter: - (void)setSortKeys:(BOOL)keys;
// declared property getter: - (BOOL)sortKeys;
- (id)stringWithObject:(id)object;
@end

__attribute__((visibility("hidden")))
@interface SBJsonWriter : SBJsonBase <SBJsonWriter> {
@private
	BOOL sortKeys;	// 16 = 0x10
	BOOL humanReadable;	// 17 = 0x11
}
@property(assign) BOOL humanReadable;	// G=0x339385f4; S=0x33938608; @synthesize
@property(assign) BOOL sortKeys;	// G=0x3393861c; S=0x33938630; @synthesize
+ (void)initialize;	// 0x33938b70
- (BOOL)appendArray:(id)array into:(id)into;	// 0x33939050
- (BOOL)appendDictionary:(id)dictionary into:(id)into;	// 0x33938bd8
- (BOOL)appendString:(id)string into:(id)into;	// 0x3393931c
- (BOOL)appendValue:(id)value into:(id)into;	// 0x33938644
// declared property getter: - (BOOL)humanReadable;	// 0x339385f4
- (id)indent;	// 0x33938940
// declared property setter: - (void)setHumanReadable:(BOOL)readable;	// 0x33938608
// declared property setter: - (void)setSortKeys:(BOOL)keys;	// 0x33938630
// declared property getter: - (BOOL)sortKeys;	// 0x3393861c
- (id)stringWithFragment:(id)fragment;	// 0x33938ae4
- (id)stringWithObject:(id)object;	// 0x339389a0
@end

