/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class StreamData, IndexData, DRMData, AudioData, VideoData;

__attribute__((visibility("hidden")))
@interface StreamHeader : NSObject {
@private
	StreamData *streamData;	// 4 = 0x4
	VideoData *videoData;	// 8 = 0x8
	AudioData *audioData;	// 12 = 0xc
	DRMData *playReady;	// 16 = 0x10
	DRMData *netflixKeyEnvelope;	// 20 = 0x14
	IndexData *indexData;	// 24 = 0x18
}
- (id)initWithBuffer:(id)buffer;	// 0x3392d8d0
- (void)dealloc;	// 0x3392d7f4
- (id)getAudioData;	// 0x3392d7a4
- (id)getIndexData;	// 0x3392d7e0
- (id)getNetflixKeyEnvelope;	// 0x3392d7cc
- (id)getPlayReady;	// 0x3392d7b8
- (id)getStreamData;	// 0x3392d77c
- (id)getVideoData;	// 0x3392d790
@end

