/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSString;

__attribute__((visibility("hidden")))
@interface StreamData : NSObject {
@private
	int fileSize;	// 4 = 0x4
	NSString *fileID;	// 8 = 0x8
	long long creationTime;	// 12 = 0xc
	long long preroll;	// 20 = 0x14
	long long duration;	// 28 = 0x1c
	long long wrapInterval;	// 36 = 0x24
	int alignmentOffset;	// 44 = 0x2c
	long long toolsVersion;	// 48 = 0x30
}
- (id)initWithBuffer:(id)buffer;	// 0x3392dd1c
- (void)dealloc;	// 0x3392dcbc
- (int)getAlignmentOffset;	// 0x3392dc90
- (long long)getCreationTime;	// 0x3392dc30
- (long long)getDuration;	// 0x3392dc60
- (id)getFileID;	// 0x3392dc1c
- (int)getFileSize;	// 0x3392dc08
- (long long)getPreroll;	// 0x3392dc48
- (long long)getToolsVersion;	// 0x3392dca4
- (long long)getWrapInterval;	// 0x3392dc78
@end

