/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSMutableDictionary;

__attribute__((visibility("hidden")))
@interface UrlParser : NSObject {
@private
	NSMutableDictionary *dict;	// 4 = 0x4
}
- (id)initWithString:(id)string;	// 0x33945b24
- (void)dealloc;	// 0x33945ac4
- (int)intValue:(id)value;	// 0x33945a38
- (id)urlDecodedValue:(id)value;	// 0x339459fc
- (id)value:(id)value;	// 0x33945a70
@end

