/**
 * This header is generated by class-dump-z 0.2a.
 * class-dump-z is Copyright (C) 2009 by KennyTM~, licensed under GPLv3.
 *
 * Source: /System/Library/PrivateFrameworks/AppleTV.framework/AppleTV
 */

#import <NSObject.h> // Unknown library

@class NSConditionLock, NSTimer, NSMutableDictionary, NSMutableArray;

__attribute__((visibility("hidden")))
@interface WSLogging : NSObject {
@private
	NSMutableDictionary *deviceInfoDictionary;	// 4 = 0x4
	NSMutableDictionary *clientInfoDictionary;	// 8 = 0x8
	NSMutableArray *activities;	// 12 = 0xc
	NSMutableArray *wsErrors;	// 16 = 0x10
	NSMutableArray *appErrors;	// 20 = 0x14
	int numItemsQueued;	// 24 = 0x18
	BOOL enableSendCheckTimer;	// 28 = 0x1c
	BOOL running;	// 29 = 0x1d
	NSTimer *sendCheckTimer;	// 32 = 0x20
	NSConditionLock *senderThreadLock;	// 36 = 0x24
}
+ (void)cleanUp;	// 0x33948cc8
+ (id)instance;	// 0x33948d04
- (id)init;	// 0x33949150
- (void)_send;	// 0x33947348
- (void)addActivity:(id)activity withHostName:(id)hostName withVersion:(id)version withUUID:(id)uuid withURL:(id)url forAction:(id)action onView:(id)view withStartTime:(long long)startTime withResponseTime:(long long)responseTime;	// 0x339481ac
- (void)addAppError:(id)error withInfoMessage:(id)infoMessage withException:(id)exception withStacktrace:(id)stacktrace;	// 0x339478b8
- (void)addWebServiceError:(id)error withHostName:(id)hostName withVersion:(id)version withUUID:(id)uuid withURL:(id)url forAction:(id)action onView:(id)view withInfoID:(id)infoID withInfoMessage:(id)infoMessage withStatusCode:(id)statusCode withSubCode:(id)subCode;	// 0x33947be4
- (void)dealloc;	// 0x33948fc0
- (void)enableSendCheckTimer:(BOOL)timer;	// 0x33948d58
- (void)queueLogItemAndSendIfNecessary;	// 0x33948c38
- (void)send;	// 0x33947850
- (void)sendLogs:(id)logs;	// 0x33948f30
- (void)sendThreadFunc:(id)func;	// 0x33948e28
- (void)setClientInfo:(id)info withHostName:(id)hostName withVersion:(id)version;	// 0x339486b0
- (void)setDeviceInfo:(id)info withESN:(id)esn withCertificationVersion:(id)certificationVersion;	// 0x33948974
@end

